//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSDate, NSString, NSUUID;
@protocol OS_nw_agent_client;

@interface _TtC16DaemoniOSLibrary20SDAirDropAgentClient : NSObject
{
    MISSING_TYPE *client;	// 8 = 0x8
    MISSING_TYPE *id;	// 7444856 = 0x719978
    MISSING_TYPE *bundleID;	// 2065 = 0x811
    MISSING_TYPE *pid;	// 7444856 = 0x719978
    MISSING_TYPE *startTime;	// 0 = 0x0
    MISSING_TYPE *applicationServiceEndpointsOnly;	// 0 = 0x0
    MISSING_TYPE *browseResponse;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x00400000005c6080
- (id)initWithClient:(id)arg1 browseDescriptor:(id)arg2 browseResponse:(CDUnknownBlockType)arg3;	// IMP=0x00100000005c5fb0
- (id)init;	// IMP=0x00100000005c5f70
@property(nonatomic, readonly) CDUnknownBlockType browseResponse;
@property(nonatomic, readonly) NSDate *startTime;
@property(nonatomic, readonly) int pid; // @synthesize pid;
@property(nonatomic, readonly) NSString *bundleID;
@property(nonatomic, readonly) NSUUID *id;
@property(nonatomic, readonly) id <OS_nw_agent_client> client; // @synthesize client;

@end

