//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSString;

@interface SDAuthenticationConfirmation : PBCodable
{
    unsigned int _errorCode;	// 8 = 0x8
    NSString *_sessionID;	// 16 = 0x10
    unsigned int _version;	// 24 = 0x18
    _Bool _success;	// 28 = 0x1c
    struct {
        unsigned int errorCode:1;
        unsigned int version:1;
        unsigned int success:1;
    } _has;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000001cf5a1
@property(nonatomic) unsigned int errorCode; // @synthesize errorCode=_errorCode;
@property(nonatomic) _Bool success; // @synthesize success=_success;
@property(retain, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000001cf4a9
- (unsigned long long)hash;	// IMP=0x00100000001cf416
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000001cf2fa
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000001cf228
- (void)copyTo:(id)arg1;	// IMP=0x00100000001cf185
- (void)writeTo:(id)arg1;	// IMP=0x00100000001cf0d5
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000001cf0c8
- (id)dictionaryRepresentation;	// IMP=0x00100000001cec35
- (id)description;	// IMP=0x00100000001ceb86
@property(nonatomic) _Bool hasErrorCode;
@property(nonatomic) _Bool hasSuccess;
@property(readonly, nonatomic) _Bool hasSessionID;
@property(nonatomic) _Bool hasVersion;

@end

