//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UITextView.h>

@class MISSING_TYPE;

@interface _TtC19FontPickerUIServiceP33_364789B77C608B517795CE5B8DEADC4419_UIAnimatedTextView : UITextView
{
    MISSING_TYPE *shouldAnimate;	// 8 = 0x8
}

- (id)initWithCoder:(id)arg1;	// IMP=0x004000000005d660
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;	// IMP=0x001000000005d5f0
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x001000000005cda0

@end

