//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CHPowerLogger;
@protocol OS_dispatch_queue, OS_os_transaction;

@interface CHRemoteBasicRequestHandler : NSObject
{
    NSObject<OS_os_transaction> *_transaction;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_serverQueue;	// 16 = 0x10
    CHPowerLogger *_modelPowerLogger;	// 24 = 0x18
}

+ (id)invalidInputErrorWithDescription:(id)arg1 failureReason:(id)arg2 recoverySuggestion:(id)arg3 errorCode:(long long)arg4;	// IMP=0x004000000000b250
+ (_Bool)_hasIdleLifetimeElapsed:(double)arg1 targetIdleLifetime:(double)arg2;	// IMP=0x001000000000b0f0
- (void).cxx_destruct;	// IMP=0x002000000000b4a0
@property(readonly, nonatomic) CHPowerLogger *modelPowerLogger; // @synthesize modelPowerLogger=_modelPowerLogger;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *serverQueue; // @synthesize serverQueue=_serverQueue;
- (void)_stageEvictionOfResourceWithTargetLifetime:(double)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x001000000000b140
- (void)optimizeResourceUsage;	// IMP=0x001000000000b0e0
- (void)setIdle;	// IMP=0x001000000000b0c0
- (void)setDirty;	// IMP=0x001000000000b080
- (id)initWithServerQueue:(id)arg1;	// IMP=0x001000000000afd0

@end

