//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ClassKit/CLSServerAlert.h>

@class NSArray, NSObject, NSString;
@protocol PDDatabaseValue;

@interface CLSServerAlert (PDDatabaseEntity)
+ (long long)migrationOrder;	// IMP=0x00200000000f238f
+ (_Bool)migrateFromVersion:(unsigned long long)arg1 finalVersion:(out unsigned long long *)arg2 inDatabase:(id)arg3;	// IMP=0x00100000000f2310
+ (id)hashableColumnNames;	// IMP=0x00100000000f19e0
+ (id)entityName;	// IMP=0x00100000000f19d3
- (void)bindTo:(id)arg1;	// IMP=0x00200000000f1f5b
- (id)initWithDatabaseRow:(id)arg1;	// IMP=0x00100000000f1c12
@property(readonly, nonatomic) NSArray *immutableColumnNames;
@property(readonly, nonatomic) unsigned long long changeHash;
// Preceding property had unknown attributes: ?
// Original attribute string: TQ,?,R,N


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, nonatomic, getter=isDeleteTracked) _Bool deleteTracked;
// Preceding property had unknown attributes: ?
// Original attribute string: TB,?,R,N,GisDeleteTracked

@property(readonly, copy) NSString *description;
@property(nonatomic, getter=isImmutabilityEnforced) _Bool enforceImmutability;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<PDDatabaseValue> *identityValue;
@property(readonly) Class superclass;
@end

