//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray, NSString, PDDPAttachmentEventDetails, PDDPDate, PDDPHandoutEventDetails, PDDPProgressEventDetails;

@interface PDDPEvent : PBCodable
{
    PDDPAttachmentEventDetails *_attachmentEventDetails;	// 8 = 0x8
    PDDPDate *_dateCreated;	// 16 = 0x10
    PDDPDate *_dateLastModified;	// 24 = 0x18
    int _eventDetails;	// 32 = 0x20
    int _eventDetailsType;	// 36 = 0x24
    int _eventType;	// 40 = 0x28
    NSMutableArray *_extraInfos;	// 48 = 0x30
    PDDPHandoutEventDetails *_handoutEventDetails;	// 56 = 0x38
    NSString *_objectId;	// 64 = 0x40
    PDDPProgressEventDetails *_progressEventDetails;	// 72 = 0x48
    struct {
        unsigned int eventDetails:1;
        unsigned int eventDetailsType:1;
        unsigned int eventType:1;
    } _has;	// 80 = 0x50
}

+ (Class)extraInfoType;	// IMP=0x002000000017bf62
- (void).cxx_destruct;	// IMP=0x002000000017df79
@property(retain, nonatomic) PDDPProgressEventDetails *progressEventDetails; // @synthesize progressEventDetails=_progressEventDetails;
@property(retain, nonatomic) PDDPAttachmentEventDetails *attachmentEventDetails; // @synthesize attachmentEventDetails=_attachmentEventDetails;
@property(retain, nonatomic) PDDPHandoutEventDetails *handoutEventDetails; // @synthesize handoutEventDetails=_handoutEventDetails;
@property(retain, nonatomic) NSMutableArray *extraInfos; // @synthesize extraInfos=_extraInfos;
@property(retain, nonatomic) PDDPDate *dateLastModified; // @synthesize dateLastModified=_dateLastModified;
@property(retain, nonatomic) PDDPDate *dateCreated; // @synthesize dateCreated=_dateCreated;
@property(retain, nonatomic) NSString *objectId; // @synthesize objectId=_objectId;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000017db91
- (unsigned long long)hash;	// IMP=0x001000000017da39
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000017d80e
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000017d4d8
- (void)copyTo:(id)arg1;	// IMP=0x001000000017d2f9
- (void)writeTo:(id)arg1;	// IMP=0x001000000017d0bd
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000017d0b0
- (id)dictionaryRepresentation;	// IMP=0x001000000017c4a1
- (id)description;	// IMP=0x001000000017c3f2
- (void)clearOneofValuesForEventDetails;	// IMP=0x001000000017c380
- (int)StringAsEventDetails:(id)arg1;	// IMP=0x001000000017c2cc
- (id)eventDetailsAsString:(int)arg1;	// IMP=0x001000000017c283
@property(nonatomic) _Bool hasEventDetails;
@property(nonatomic) int eventDetails; // @synthesize eventDetails=_eventDetails;
@property(readonly, nonatomic) _Bool hasProgressEventDetails;
@property(readonly, nonatomic) _Bool hasAttachmentEventDetails;
@property(readonly, nonatomic) _Bool hasHandoutEventDetails;
- (int)StringAsEventDetailsType:(id)arg1;	// IMP=0x001000000017c024
- (id)eventDetailsTypeAsString:(int)arg1;	// IMP=0x001000000017bfdb
@property(nonatomic) _Bool hasEventDetailsType;
@property(nonatomic) int eventDetailsType; // @synthesize eventDetailsType=_eventDetailsType;
- (id)extraInfoAtIndex:(unsigned long long)arg1;	// IMP=0x001000000017bf45
- (unsigned long long)extraInfosCount;	// IMP=0x001000000017bf28
- (void)addExtraInfo:(id)arg1;	// IMP=0x001000000017bebe
- (void)clearExtraInfos;	// IMP=0x001000000017bea1
@property(readonly, nonatomic) _Bool hasDateLastModified;
@property(readonly, nonatomic) _Bool hasDateCreated;
- (int)StringAsEventType:(id)arg1;	// IMP=0x001000000017bbb0
- (id)eventTypeAsString:(int)arg1;	// IMP=0x001000000017ba1b
@property(nonatomic) _Bool hasEventType;
@property(nonatomic) int eventType; // @synthesize eventType=_eventType;
@property(readonly, nonatomic) _Bool hasObjectId;

@end

