//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSString, PDDPBinaryValue, PDDPQuantityValue, PDDPScoreValue;

@interface PDDPActivityReportItem : PBCodable
{
    PDDPBinaryValue *_binaryValue;	// 8 = 0x8
    NSString *_identifier;	// 16 = 0x10
    PDDPQuantityValue *_quantityValue;	// 24 = 0x18
    PDDPScoreValue *_scoreValue;	// 32 = 0x20
    NSString *_title;	// 40 = 0x28
    int _type;	// 48 = 0x30
    CDStruct_f953fb60 _has;	// 52 = 0x34
}

- (void).cxx_destruct;	// IMP=0x002000000009ef91
@property(retain, nonatomic) PDDPScoreValue *scoreValue; // @synthesize scoreValue=_scoreValue;
@property(retain, nonatomic) PDDPQuantityValue *quantityValue; // @synthesize quantityValue=_quantityValue;
@property(retain, nonatomic) PDDPBinaryValue *binaryValue; // @synthesize binaryValue=_binaryValue;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000009edb3
- (unsigned long long)hash;	// IMP=0x001000000009ece0
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000009eb72
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000009ea36
- (void)copyTo:(id)arg1;	// IMP=0x001000000009e953
- (void)writeTo:(id)arg1;	// IMP=0x001000000009e879
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000009e86c
- (id)dictionaryRepresentation;	// IMP=0x001000000009e345
- (id)description;	// IMP=0x001000000009e296
@property(readonly, nonatomic) _Bool hasScoreValue;
@property(readonly, nonatomic) _Bool hasQuantityValue;
@property(readonly, nonatomic) _Bool hasBinaryValue;
- (int)StringAsType:(id)arg1;	// IMP=0x001000000009e1a3
- (id)typeAsString:(int)arg1;	// IMP=0x001000000009e15a
@property(nonatomic) _Bool hasType;
@property(nonatomic) int type; // @synthesize type=_type;
@property(readonly, nonatomic) _Bool hasIdentifier;
@property(readonly, nonatomic) _Bool hasTitle;

@end

