//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface WCDProtoPairedSyncComplicationsStartedAck : PBCodable
{
    unsigned int _version;	// 8 = 0x8
    _Bool _success;	// 12 = 0xc
    struct {
        unsigned int version:1;
        unsigned int success:1;
    } _has;	// 16 = 0x10
}

@property(nonatomic) _Bool success; // @synthesize success=_success;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000011577
- (unsigned long long)hash;	// IMP=0x0010000000011532
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000001146f
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000113f0
- (void)copyTo:(id)arg1;	// IMP=0x0010000000011394
- (void)writeTo:(id)arg1;	// IMP=0x0010000000011320
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000011313
- (id)dictionaryRepresentation;	// IMP=0x0010000000010fdc
- (id)description;	// IMP=0x0010000000010f2d
@property(nonatomic) _Bool hasSuccess;
@property(nonatomic) _Bool hasVersion;

@end

