//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSAsset, CSAttSiriController, CSAudioRecordContext, NSArray, NSHashTable, NSString, SLProgressiveCheckerAnalyzer, SLProgressiveCheckerResult;
@protocol OS_dispatch_queue;

@interface CSAttSiriAFTMNode : NSObject
{
    _Bool _isReady;	// 8 = 0x8
    _Bool _sessionInProgress;	// 9 = 0x9
    _Bool _isShadowModeEnabled;	// 10 = 0xa
    _Bool _makeStandaloneMitigation;	// 11 = 0xb
    CSAttSiriController *_attSiriController;	// 16 = 0x10
    unsigned long long _type;	// 24 = 0x18
    NSArray *_requiredNodes;	// 32 = 0x20
    NSString *_mhId;	// 40 = 0x28
    CSAsset *_prefetchedAsset;	// 48 = 0x30
    CSAsset *_currentAsset;	// 56 = 0x38
    NSHashTable *_receivers;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_queue;	// 72 = 0x48
    NSString *_taskName;	// 80 = 0x50
    NSString *_configFile;	// 88 = 0x58
    SLProgressiveCheckerAnalyzer *_acousticAnalyzer;	// 96 = 0x60
    NSArray *_thresholds;	// 104 = 0x68
    unsigned long long _supportedRecordType;	// 112 = 0x70
    SLProgressiveCheckerResult *_latestResult;	// 120 = 0x78
    CSAudioRecordContext *_context;	// 128 = 0x80
    NSString *_requestId;	// 136 = 0x88
}

- (void).cxx_destruct;	// IMP=0x00200000000af5b2
@property(retain, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(retain, nonatomic) CSAudioRecordContext *context; // @synthesize context=_context;
@property(retain, nonatomic) SLProgressiveCheckerResult *latestResult; // @synthesize latestResult=_latestResult;
@property(nonatomic) _Bool makeStandaloneMitigation; // @synthesize makeStandaloneMitigation=_makeStandaloneMitigation;
@property(nonatomic) _Bool isShadowModeEnabled; // @synthesize isShadowModeEnabled=_isShadowModeEnabled;
@property(nonatomic) _Bool sessionInProgress; // @synthesize sessionInProgress=_sessionInProgress;
@property(nonatomic) unsigned long long supportedRecordType; // @synthesize supportedRecordType=_supportedRecordType;
@property(retain, nonatomic) NSArray *thresholds; // @synthesize thresholds=_thresholds;
@property(retain, nonatomic) SLProgressiveCheckerAnalyzer *acousticAnalyzer; // @synthesize acousticAnalyzer=_acousticAnalyzer;
@property(retain, nonatomic) NSString *configFile; // @synthesize configFile=_configFile;
@property(retain, nonatomic) NSString *taskName; // @synthesize taskName=_taskName;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSHashTable *receivers; // @synthesize receivers=_receivers;
@property(retain, nonatomic) CSAsset *currentAsset; // @synthesize currentAsset=_currentAsset;
@property(retain, nonatomic) CSAsset *prefetchedAsset; // @synthesize prefetchedAsset=_prefetchedAsset;
@property(retain, nonatomic) NSString *mhId; // @synthesize mhId=_mhId;
@property(nonatomic) _Bool isReady; // @synthesize isReady=_isReady;
@property(retain, nonatomic) NSArray *requiredNodes; // @synthesize requiredNodes=_requiredNodes;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) __weak CSAttSiriController *attSiriController; // @synthesize attSiriController=_attSiriController;
- (void)_reportResultToAnalytics;	// IMP=0x00100000000af2b3
- (id)_createResultDict;	// IMP=0x00100000000aeffe
- (void)_logResultToVTDirectory;	// IMP=0x00100000000aec88
- (void)_logAFTMEndMsgWithScore:(float)arg1 analyzedSamples:(unsigned long long)arg2;	// IMP=0x00100000000aec82
- (void)_logAFTMStartMsg:(id)arg1 taskType:(id)arg2;	// IMP=0x00100000000aec7c
- (void)analyzer:(id)arg1 hasPartialResult:(id)arg2;	// IMP=0x00100000000aebc5
- (void)analyzer:(id)arg1 hasFinalResult:(id)arg2;	// IMP=0x00000000000aeb0e
- (void)_handleAFTMResults:(id)arg1;	// IMP=0x00100000000ae6cd
- (_Bool)_shouldHandleMitigationDecision:(_Bool)arg1;	// IMP=0x00100000000ae689
- (void)_reset;	// IMP=0x00100000000ae5ee
- (void)_addAudio:(id)arg1;	// IMP=0x00100000000ae47a
- (void)_startRequestWithContext:(id)arg1 withVtei:(id)arg2 withRequestId:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000000add7f
- (void)_setAsset:(id)arg1 forTask:(id)arg2;	// IMP=0x00100000000ad9b7
- (void)attSiriAudioSrcNodeDidStop:(id)arg1;	// IMP=0x00100000000ad96c
- (void)attSiriAudioSrcNodeLPCMRecordBufferAvailable:(id)arg1 audioChunk:(id)arg2;	// IMP=0x00100000000ad8df
- (void)attSiriAudioSrcNodeDidStartRecording:(id)arg1 successfully:(_Bool)arg2 error:(id)arg3;	// IMP=0x00100000000ad8d9
- (void)endAudio;	// IMP=0x00100000000ad88e
- (void)addAudio:(id)arg1;	// IMP=0x00100000000ad801
- (void)startRequestWithContext:(id)arg1 withVtei:(id)arg2 taskType:(id)arg3 withRequestId:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x00100000000ad6c1
- (void)_startRequestWithContext:(id)arg1 withVtei:(id)arg2 withVTAssets:(id)arg3 taskType:(id)arg4 withRequestId:(id)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x00100000000ad4fb
- (void)startRequestWithContext:(id)arg1 withVtei:(id)arg2 withVTAssets:(id)arg3 taskType:(id)arg4 withRequestId:(id)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x00100000000ad38b
- (void)pause;	// IMP=0x00100000000ad2f8
- (void)stop;	// IMP=0x00100000000ad2ad
- (void)start;	// IMP=0x00100000000ad2a7
- (void)removeReceiver:(id)arg1;	// IMP=0x00100000000ad291
- (void)addReceiver:(id)arg1;	// IMP=0x00100000000ad198
- (id)initWithAttSiriController:(id)arg1;	// IMP=0x00100000000ad14a
- (id)init;	// IMP=0x00100000000acfdf

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

