//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol CSVoiceTriggerXPCConnectionDelegate, OS_dispatch_queue, OS_xpc_object;

@interface CSVoiceTriggerXPCConnection : NSObject
{
    id <CSVoiceTriggerXPCConnectionDelegate> _delegate;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSObject<OS_xpc_object> *_connection;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000fe922
@property(retain, nonatomic) NSObject<OS_xpc_object> *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak id <CSVoiceTriggerXPCConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_handleVoiceTriggerStatsFetchEvent:(id)arg1 client:(id)arg2;	// IMP=0x00100000000fe7c8
- (void)_handleServiceConnectionLostIfNeeded;	// IMP=0x00100000000fe7c2
- (void)_handleEnableVoiceTriggerWithSiriAssertionRequest:(id)arg1;	// IMP=0x00100000000fe6ee
- (void)_handleVoiceTriggeredSiriSessionCancelled;	// IMP=0x00100000000fe632
- (void)_handleRaiseToSpeakBypassRequest:(id)arg1;	// IMP=0x00100000000fe597
- (void)_handlePhraseSpotterBypassRequest:(id)arg1;	// IMP=0x00100000000fe474
- (void)_handleVoiceTriggerXPCServiceMessage:(id)arg1 client:(id)arg2;	// IMP=0x00100000000fe284
- (void)_sendReply:(id)arg1 client:(id)arg2 result:(_Bool)arg3 error:(id)arg4;	// IMP=0x00100000000fe223
- (void)_handleClientError:(id)arg1 client:(id)arg2;	// IMP=0x00100000000fe028
- (void)_handleClientMessage:(id)arg1 client:(id)arg2;	// IMP=0x00100000000fdec0
- (void)_handleClientEvent:(id)arg1;	// IMP=0x00100000000fdd5a
- (void)activateConnection;	// IMP=0x00100000000fdcab
- (id)initWithConnection:(id)arg1;	// IMP=0x00100000000fdbdf

@end

