//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSDAccountController, IDSKeyTransparencyVerifier, IDSSystemAccountAdapter, IMDispatchTimer;
@protocol IMUserDefaults;

@interface IDSAccountRepair : NSObject
{
    _Bool _shouldSupressRepairLogic;	// 8 = 0x8
    _Bool _waitingForMigration;	// 9 = 0x9
    IDSDAccountController *_accountController;	// 16 = 0x10
    IDSSystemAccountAdapter *_systemAccountAdapter;	// 24 = 0x18
    id <IMUserDefaults> _userDefaults;	// 32 = 0x20
    IDSKeyTransparencyVerifier *_keyTransparencyVerifier;	// 40 = 0x28
    IMDispatchTimer *_repairTimer;	// 48 = 0x30
    IMDispatchTimer *_phoneRepairTimer;	// 56 = 0x38
    double _lastBagRepairInterval;	// 64 = 0x40
}

+ (double)_phoneNumberRepairIntervalForCount:(long long)arg1;	// IMP=0x00400000001238e8
+ (double)_phoneNumberRepairMaxInterval;	// IMP=0x001000000012384d
+ (double)_phoneNumberRepairInterval;	// IMP=0x001000000012379f
- (void).cxx_destruct;	// IMP=0x00200000001246fe
@property(nonatomic) _Bool waitingForMigration; // @synthesize waitingForMigration=_waitingForMigration;
@property(nonatomic) double lastBagRepairInterval; // @synthesize lastBagRepairInterval=_lastBagRepairInterval;
@property(retain, nonatomic) IMDispatchTimer *phoneRepairTimer; // @synthesize phoneRepairTimer=_phoneRepairTimer;
@property(retain, nonatomic) IMDispatchTimer *repairTimer; // @synthesize repairTimer=_repairTimer;
@property(retain, nonatomic) IDSKeyTransparencyVerifier *keyTransparencyVerifier; // @synthesize keyTransparencyVerifier=_keyTransparencyVerifier;
@property(retain, nonatomic) id <IMUserDefaults> userDefaults; // @synthesize userDefaults=_userDefaults;
@property(retain, nonatomic) IDSSystemAccountAdapter *systemAccountAdapter; // @synthesize systemAccountAdapter=_systemAccountAdapter;
@property(retain, nonatomic) IDSDAccountController *accountController; // @synthesize accountController=_accountController;
@property(nonatomic) _Bool shouldSupressRepairLogic; // @synthesize shouldSupressRepairLogic=_shouldSupressRepairLogic;
- (_Bool)_repairPhoneNumberAccounts;	// IMP=0x001000000012461a
- (void)_phoneNumberRepairTimerHit:(id)arg1;	// IMP=0x001000000012429c
- (void)_resetPhoneNumberRepairCounter;	// IMP=0x00100000001241e9
- (void)recalculatePhoneRepairTimer;	// IMP=0x00100000001241e3
- (void);	// IMP=0x0010000000123aae
- (id)_totalRepairCountFromPrefs;	// IMP=0x0010000000123a57
- (id)_lastRepairIntervalFromPrefs;	// IMP=0x0010000000123a00
- (_Bool)_shouldNotSetupPhoneNumberRepairTimer;	// IMP=0x00100000001239f8
- (void)_repairKVSEntriesForKT;	// IMP=0x00100000001236a1
- (void)_repairKTAccount:(id)arg1;	// IMP=0x00100000001233fb
- (void)repairiCloudBasedAccounts;	// IMP=0x0010000000122dca
- (void)_repairiTunesBasedAccounts;	// IMP=0x00100000001228f1
- (void)_createAndEnableExistingSystemAccounts;	// IMP=0x0010000000122599
- (id)_createiTunesAccountFromSystemIfNeeded;	// IMP=0x0010000000122210
- (_Bool)_hasActiveAppleIDBasedAccountOnService:(id)arg1;	// IMP=0x0010000000121ffa
- (id)_activeAppleIDAccount;	// IMP=0x0010000000121e01
- (void)repairService:(id)arg1 withPrimaryUserName:(id)arg2;	// IMP=0x0010000000120834
- (void)repairAccounts;	// IMP=0x001000000011ee88
- (void)_registerForAccountRepairActivity;	// IMP=0x001000000011eaf2
- (void)_repairAccountsWithSuccessfullAppleIDRegistrationForDSID:(id)arg1 service:(id)arg2;	// IMP=0x001000000011e19c
- (_Bool)_checkForOtherRegisteredTopLevelPhoneAccountMatchingThisAccount:(id)arg1;	// IMP=0x001000000011dff5
- (_Bool)_isPhoneAccount:(id)arg1 registeredAndMatchingThisAccount:(id)arg2;	// IMP=0x001000000011df13
- (void)_repairAccountsWithSuccessfulPhoneNumberRegistration;	// IMP=0x001000000011cd07
- (void)kickRepairForAllRegistrationsSucceeded:(id)arg1;	// IMP=0x001000000011c4f0
- (_Bool)_shouldBypassRepairLogic;	// IMP=0x001000000011c3d9
- (void)_repairTimerHit:(id)arg1;	// IMP=0x001000000011c256
- (void)forceRepairAccounts:(id)arg1;	// IMP=0x001000000011bece
- (id)initWithAccountController:(id)arg1 systemAccountAdapter:(id)arg2 userDefaults:(id)arg3 keyTransparencyVerifier:(id)arg4;	// IMP=0x001000000011bc60

@end

