//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;

@interface IDSGroupStableKeyMaterialCollection : NSObject
{
    NSArray *_stableKeyMaterials;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000226339
@property(readonly, nonatomic) NSArray *stableKeyMaterials; // @synthesize stableKeyMaterials=_stableKeyMaterials;
- (id);	// IMP=0x001000000022629a
- (id)initWithStableKeyMaterials:(id)arg1;	// IMP=0x001000000022622f

@end

