//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDSKeyTransparencyRegistrationDataSource : NSObject
{
}

- (_Bool)isiCloudSignedIn;	// IMP=0x00200000004af267
- (id)currentLocalKeyTransparencyEnrolledURIsForServiceIdentifier:(id)arg1;	// IMP=0x00100000004aef39
- (id)currentLocalKeyTransparencyEligibleServiceIdentifiers;	// IMP=0x00100000004aee54
- (_Bool)iCloudAccountDoesMatchAccountForIdentifier:(id)arg1;	// IMP=0x00100000004ae9eb
- (long long);	// IMP=0x00100000004ae754
- (id)trustedRemoteKeyTransparencySignatureForServiceIdentifier:(id)arg1 pushToken:(id)arg2;	// IMP=0x00100000004ae2bd
- (id)_dependentRegistrationPropertyForKey:(id)arg1 serviceIdentifier:(id)arg2 pushToken:(id)arg3;	// IMP=0x00100000004ade79

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

