//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProxCardKit/PRXPasscodeEntryViewController.h>

@class MISSING_TYPE;

@interface _TtC16TVSetupUIService25TVSetupAuthViewController : PRXPasscodeEntryViewController
{
    MISSING_TYPE *delegate;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0040000000004e30
- (id)initWithContentView:(id)arg1;	// IMP=0x0010000000004da0
- (void)didCompleteTextEntry:(id)arg1;	// IMP=0x0010000000004d50
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000004b30

@end

