//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MAAutoAssetSelector, MADAutoSetPolicy, NSString;

__attribute__((visibility("hidden")))
@interface MADMarker : NSObject
{
    _Bool _isSetJob;	// 8 = 0x8
    NSString *_assetType;	// 16 = 0x10
    NSString *_clientDomainName;	// 24 = 0x18
    NSString *_assetSetIdentifier;	// 32 = 0x20
    MADAutoSetPolicy *_setPolicy;	// 40 = 0x28
    MADAutoSetPolicy *_pushedPolicy;	// 48 = 0x30
    MAAutoAssetSelector *_assetSelector;	// 56 = 0x38
}

+ (_Bool)supportsSecureCoding;	// IMP=0x001000000003c553
- (void).cxx_destruct;	// IMP=0x000000000003cabc
@property(readonly, retain, nonatomic) MAAutoAssetSelector *assetSelector; // @synthesize assetSelector=_assetSelector;
@property(retain, nonatomic) MADAutoSetPolicy *pushedPolicy; // @synthesize pushedPolicy=_pushedPolicy;
@property(readonly, retain, nonatomic) MADAutoSetPolicy *setPolicy; // @synthesize setPolicy=_setPolicy;
@property(readonly, retain, nonatomic) NSString *assetSetIdentifier; // @synthesize assetSetIdentifier=_assetSetIdentifier;
@property(readonly, retain, nonatomic) NSString *clientDomainName; // @synthesize clientDomainName=_clientDomainName;
@property(readonly, retain, nonatomic) NSString *assetType; // @synthesize assetType=_assetType;
@property(readonly, nonatomic) _Bool isSetJob; // @synthesize isSetJob=_isSetJob;
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000000003c8bf
- (id)summary;	// IMP=0x000000000003c70d
- (id)description;	// IMP=0x000000000003c55b
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000000003c417
- (id)initWithCoder:(id)arg1;	// IMP=0x000000000003c2bd
- (id)initForAssetType:(id)arg1 forClientDomainName:(id)arg2 forAssetSetIdentifier:(id)arg3 forAssetSelector:(id)arg4 forSetJob:(_Bool)arg5 withSetPolicy:(id)arg6 withPushedPolicy:(id)arg7;	// IMP=0x000000000003c176

@end

