//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PayLaterFinancingPlanTermsDetails
{
}

+ (id)_propertySettersForPayLaterFinancingPlanTermsDetails;	// IMP=0x00400000004eaeb6
+ (id)_propertyValuesForPayLaterTermsDetails:(id)arg1;	// IMP=0x00100000004eae2b
+ (id)_predicateForFinancingPlanPID:(long long)arg1;	// IMP=0x00100000004eadba
+ (void)deletePayLaterFinancingPlanTermsDetailsForFinancingPlanPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000004eab83
+ (id)anyInDatabase:(id)arg1 forFinancingPlanPID:(long long)arg2;	// IMP=0x00100000004eaaf7
+ (id)insertOrUpdatePayLaterFinancingPlanTermsDetails:(id)arg1 forFinancingPlanPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00100000004ea98c
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x00100000004ea87f
+ (id)databaseTable;	// IMP=0x00100000004ea872
- (id)termsDetails;	// IMP=0x00400000004eac4b
- (_Bool)deleteFromDatabase;	// IMP=0x00100000004eac1c
- (void)updateWithPayLaterFinancingPlanTermsDetails:(id)arg1;	// IMP=0x00100000004eaa7d
- (id)initWithPayLaterFinancingPlanTermsDetails:(id)arg1 forFinancingPlanPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00100000004ea8ae

@end

