//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class PKAccount;

@interface PDAccountOverdrawnBalanceUserNotification
{
    PKAccount *_account;	// 136 = 0x88
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00200000002deb36
+ (id)notificationIdentifierForAccountIdentifier:(id)arg1;	// IMP=0x00100000002de748
- (void).cxx_destruct;	// IMP=0x00200000002dec67
@property(readonly, nonatomic) PKAccount *account; // @synthesize account=_account;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000002debd9
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000002deb3e
- (id)applicationMessageContent;	// IMP=0x00100000002de990
- (id)notificationContentWithDataSource:(id)arg1;	// IMP=0x00100000002de887
- (_Bool)isValid;	// IMP=0x00100000002de87a
- (unsigned long long)notificationType;	// IMP=0x00100000002de86f
- (id)initWithAccount:(id)arg1;	// IMP=0x00100000002de76d

@end

