//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, NSMutableArray, NSMutableSet, NSString, NSXPCListener, PDAssertionCoordinator, RBSProcessMonitor;
@protocol OS_dispatch_queue;

@interface PDAssertionManager : NSObject
{
    NSXPCListener *_coordinatorListener;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_replyQueue;	// 16 = 0x10
    struct os_unfair_lock_s _lock;	// 24 = 0x18
    NSHashTable *_observers;	// 32 = 0x20
    PDAssertionCoordinator *_localCoordinator;	// 40 = 0x28
    NSMutableArray *_coordinators;	// 48 = 0x30
    NSMutableSet *_monitoredPIDs;	// 56 = 0x38
    RBSProcessMonitor *_processStateMonitor;	// 64 = 0x40
    _Bool _configuredProcessUpdateHandler;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x002000000043881a
- (void)logAssertionsOfTypes:(id)arg1;	// IMP=0x001000000043779b
- (void)unregisterObserver:(id)arg1;	// IMP=0x0010000000437747
- (void)registerObserver:(id)arg1;	// IMP=0x00100000004376d6
- (_Bool)hasAssertionsOfType:(unsigned long long)arg1;	// IMP=0x001000000043755c
- (id)assertionsOfType:(unsigned long long)arg1;	// IMP=0x0010000000437373
- (_Bool)assertionCoordinator:(id)arg1 assertionExistsOfType:(unsigned long long)arg2;	// IMP=0x001000000043735e
- (void)assertionCoordinator:(id)arg1 didInvalidateAssertion:(id)arg2;	// IMP=0x0010000000437108
- (void)assertionCoordinator:(id)arg1 didAcquireAssertion:(id)arg2;	// IMP=0x0010000000436eb2
- (_Bool)assertionCoordinator:(id)arg1 canAcquireAssertion:(id)arg2;	// IMP=0x0010000000436d09
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00100000004365cc
- (void)dealloc;	// IMP=0x00100000004364ca
- (id)init;	// IMP=0x0010000000436397
- (void)invalidateAssertionOfType:(unsigned long long)arg1 withIdentifier:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x001000000043896d
- (void)acquireAssertionOfType:(unsigned long long)arg1 withIdentifier:(id)arg2 reason:(id)arg3 handler:(CDUnknownBlockType)arg4;	// IMP=0x0010000000438879

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

