//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSSet, NSString;

@interface PDPaymentOffersManagerCatalogFetchRequest : NSObject
{
    NSMutableSet *_completionHandlers;	// 8 = 0x8
    _Bool _fromPush;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000055fb28
@property(readonly, copy, nonatomic) NSSet *completionHandlers; // @synthesize completionHandlers=_completionHandlers;
@property(readonly, nonatomic) _Bool fromPush; // @synthesize fromPush=_fromPush;
@property(readonly, copy) NSString *description;
- (void)callCompletionsWithCatalog:(id)arg1 error:(id)arg2;	// IMP=0x001000000055f8c9
- (void)addCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000055f893
- (_Bool)coalesceWithRequest:(id)arg1;	// IMP=0x001000000055f6ed
- (id)requestIdentifier;	// IMP=0x001000000055f6d3
- (unsigned long long)requestType;	// IMP=0x001000000055f6cb
- (id)initWithFromPush:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000055f63e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

