//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, PDAppletSubcredentialManager, PDCarKeySharingManagementService, PDDatabaseManager, PDGeneralSharingManagementService, PDHomeShareManagementService, PDPaymentWebServiceCoordinator, PDPushNotificationManager, PDRemoteInterfacePresenter, PDSharingChannelManager, PDSharingStatefulProvisioningManager, PDSharingUserCommunicationManager, PDUserNotificationManager;
@protocol OS_dispatch_queue, PDSharingManagerDelegate, PKCloudStoreCoordinatorDelegate;

@interface PDSharingManager : NSObject
{
    PDSharingStatefulProvisioningManager *_statefulProvisioningManager;	// 8 = 0x8
    PDPaymentWebServiceCoordinator *_webServiceCoordinator;	// 16 = 0x10
    PDDatabaseManager *_databaseManager;	// 24 = 0x18
    PDUserNotificationManager *_userNotificationManager;	// 32 = 0x20
    PDSharingUserCommunicationManager *_userCommunicationManager;	// 40 = 0x28
    PDPushNotificationManager *_pushNotificationManager;	// 48 = 0x30
    PDAppletSubcredentialManager *_subcredentialManager;	// 56 = 0x38
    PDRemoteInterfacePresenter *_remoteInterfacePresenter;	// 64 = 0x40
    id <PKCloudStoreCoordinatorDelegate> _cloudStoreDelegate;	// 72 = 0x48
    id <PDSharingManagerDelegate> _delegate;	// 80 = 0x50
    NSObject<OS_dispatch_queue> *_queue;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_replyQueue;	// 96 = 0x60
    PDGeneralSharingManagementService *_sharingManagementService;	// 104 = 0x68
    PDHomeShareManagementService *_homeManagementService;	// 112 = 0x70
    PDCarKeySharingManagementService *_carKeyManagementService;	// 120 = 0x78
    NSMutableArray *_continuityManagers;	// 128 = 0x80
    PDSharingChannelManager *_channelManager;	// 136 = 0x88
}

- (void).cxx_destruct;	// IMP=0x002000000011ca4d
@property(readonly, nonatomic) PDSharingChannelManager *channelManager; // @synthesize channelManager=_channelManager;
- (void)processCLICommands:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000110ef0
- (void)channelWasRemotelyTerminatedWithTransportIdentifier:(id)arg1;	// IMP=0x0010000000110d7e
- (void)handleOutstandingShareMessage:(id)arg1 transportIdentifier:(id)arg2;	// IMP=0x001000000010d02f
- (void)insertPassMessage:(id)arg1 pass:(id)arg2;	// IMP=0x001000000010cfb1
- (void)userDidDismissPendingShareActivationForShareIdentifier:(id)arg1;	// IMP=0x001000000010ce9e
- (id)pendingShareActivationForShareIdentifier:(id)arg1;	// IMP=0x001000000010cd4f
- (id)pendingShareActivations;	// IMP=0x001000000010ca41
- (void)provisioningOperationsDidUpdate;	// IMP=0x001000000010ca2b
- (void)finishedStatefulProvisioningAttemptWithSuccess:(_Bool)arg1 operation:(id)arg2 share:(id)arg3;	// IMP=0x001000000010c76c
- (void)revokePendingCredentialsForReaderIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000010c22a
- (void)pendingCredentialsBeingProvisioned:(CDUnknownBlockType)arg1;	// IMP=0x001000000010bf1f
- (void)pendingShareActivationForShareIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000010b9e5
- (void)didReceiveActivationCodeFailureForCredentialIdentifier:(id)arg1 attemptsRemaining:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000010b722
- (void)acceptCarKeyShareForMessage:(id)arg1 activationCode:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000010a2f2
- (void)sendSharingMessageTo:(id)arg1 message:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000109fea
- (void)passWillBeRemoved:(id)arg1;	// IMP=0x0010000000109b4b
- (void)passUpdated:(id)arg1 oldPass:(id)arg2 oldShares:(id)arg3 oldEntitlements:(id)arg4;	// IMP=0x001000000010980d
- (void)passUpdated:(id)arg1 oldShares:(id)arg2;	// IMP=0x00100000001097f5
- (void)passAdded:(id)arg1;	// IMP=0x00100000001096b6
- (void)userNotificationActionPerformed:(unsigned long long)arg1 notificationIdentifier:(id)arg2;	// IMP=0x001000000010911d
- (void)displayableEntitlementsForPassIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000108e99
- (void)displayableSharesForPassIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000010896c
- (id)entitlementsForPassIdentifier:(id)arg1;	// IMP=0x0010000000108828
- (_Bool)hasShareableEntitlementsForPassIdentifier:(id)arg1;	// IMP=0x001000000010871e
- (_Bool)hasSharesForPassIdentifier:(id)arg1;	// IMP=0x0010000000108607
- (void)sharesForPassIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000108480
- (_Bool)hasActiveExternallySharedPasses;	// IMP=0x00100000001083c2
- (void)cacheSharingMessageFromMailboxAddress:(id)arg1 message:(id)arg2;	// IMP=0x00100000001082db
- (void)createSingleUseShareURLWithMessage:(id)arg1 timeToLive:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000107e41
- (void)revokeSharesForPassIdentifier:(id)arg1 shares:(id)arg2 shouldCascade:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000001073f9
- (void)revokeShareForPassIdentifier:(id)arg1 share:(id)arg2 shouldCascade:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000107316
- (void)updateShareForPassIdentifier:(id)arg1 share:(id)arg2 authorization:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000106c6d
- (void)createShareInvitationForPartialShareInvitation:(id)arg1 existingTransportIdentifier:(id)arg2 authorization:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000104cc6
- (void)createShareForPartialShareInvitation:(id)arg1 authorization:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001039e3
- (void)prewarmCreateShareForPassIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000010348c
- (void)rejectShareForMailboxAddress:(id)arg1;	// IMP=0x0010000000102f77
- (void)deleteSharingMessage:(id)arg1;	// IMP=0x0010000000102c2c
- (void)relinquishInvitation:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000010294f
- (void)retrieveShareInvitationForMailboxAddress:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000101c49
- (void)checkInvitationStatusForMailboxAddress:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000101a8e
- (void)start;	// IMP=0x0010000000101a75
- (id)initWithWebServiceCoordinator:(id)arg1 databaseManager:(id)arg2 notificationManager:(id)arg3 pushNotificationManager:(id)arg4 cardFileManager:(id)arg5 subcredentialManager:(id)arg6 applicationMessageManager:(id)arg7 remoteInterfacePresenter:(id)arg8 idsSharingService:(id)arg9 cloudStoreDelegate:(id)arg10 delegate:(id)arg11;	// IMP=0x001000000010171f
- (id)init;	// IMP=0x0010000000101711

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

