//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface PDShareActivationRequiredUserNotification
{
    NSString *_shareIdentifier;	// 160 = 0xa0
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00200000002dc35e
- (void).cxx_destruct;	// IMP=0x00200000002dc377
@property(readonly, nonatomic) NSString *shareIdentifier; // @synthesize shareIdentifier=_shareIdentifier;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000002dc2e1
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000002dc246
- (id)description;	// IMP=0x00100000002dc16a
- (unsigned long long)notificationType;	// IMP=0x00100000002dc15f
- (id)initWithTitle:(id)arg1 message:(id)arg2 shareIdentifier:(id)arg3;	// IMP=0x00100000002dc085

@end

