//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PendingPaymentRemoteCredential
{
}

+ (id)_propertySetters;	// IMP=0x0040000000401f3a
+ (id)_properties;	// IMP=0x0010000000401e5a
+ (id)databaseTable;	// IMP=0x0010000000401e4d
+ (id)_predicateForBasePendingProvisioningPID:(long long)arg1;	// IMP=0x0010000000401ddc
+ (void)deleteEntitiesForBasePendingProvisioningPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x0010000000401d3f
+ (void)inflatePendingProvisioning:(id)arg1 forBasePendingProvisioningPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x0010000000401b63
+ (id)insertPendingProvisioning:(id)arg1 forBasePendingProvisioning:(id)arg2 inDatabase:(id)arg3;	// IMP=0x0010000000401950
- (id)initWithPendingProvisioning:(id)arg1 forBasePendingProvisioning:(id)arg2 inDatabase:(id)arg3;	// IMP=0x0040000000401595

@end

