//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SharingIDSChannelEndpoint
{
}

+ (id)_properties;	// IMP=0x0040000000382107
+ (id)databaseTable;	// IMP=0x00100000003820fa
- (id)initWithIDSEndpoint:(id)arg1 inDatabase:(id)arg2;	// IMP=0x0040000000381fbd

@end

