//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface SharedAccountCloudStore
{
}

+ (id)_propertySettersForSharedAccountCloudStore;	// IMP=0x00400000004e975f
+ (id)_sharedAccountCloudStoreForQuery:(id)arg1;	// IMP=0x00100000004e9461
+ (MISSING_TYPE *)_predicateForAccountPID: /* Error: Ran out of types for this method. */;	// IMP=0x00100000004e9214
+ (void)deleteEntitiesForAccountPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000004e90ff
+ (id)sharedAccountCloudStoreByAccountIdentifierInDatabase:(id)arg1;	// IMP=0x00100000004e8dc2
+ (id)sharedAccountCloudStoreForAccount:(id)arg1 inDatabase:(id)arg2;	// IMP=0x00100000004e8d0b
+ (id)insertOrUpdateSharedAccountCloudStore:(id)arg1 forAccount:(id)arg2 inDatabase:(id)arg3;	// IMP=0x00100000004e89ae
+ (void)addJoinClausesForProperty:(id)arg1 toJoins:(id)arg2;	// IMP=0x00100000004e8910
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x00100000004e88e1
+ (id)databaseTable;	// IMP=0x00100000004e88d4
- (id)_commonDictionaryForSharedAccountCloudStore:(id)arg1 accountPID:(long long)arg2;	// IMP=0x00400000004e963c
- (id)sharedAccountCloudStore;	// IMP=0x00100000004e9285
- (_Bool)deleteFromDatabase;	// IMP=0x00100000004e9198
- (void)updateWithSharedAccountCloudStore:(id)arg1 forAccount:(id)arg2;	// IMP=0x00100000004e8bc7
- (id)initWithSharedAccountCloudStore:(id)arg1 forAccount:(id)arg2 inDatabase:(id)arg3;	// IMP=0x00100000004e8ab0

@end

