//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TileStateDefaultV2
{
}

+ (id)_predicateForBaseStatePID:(long long)arg1;	// IMP=0x00400000003e2be2
+ (id)_predicateForBaseState:(id)arg1;	// IMP=0x00100000003e2b74
+ (id)databaseTable;	// IMP=0x00100000003e2b67
+ (void)deleteEntitiesForBaseState:(id)arg1 inDatabase:(id)arg2;	// IMP=0x00100000003e2991
+ (void)inflateState:(id)arg1 forBaseStatePID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00100000003e230f
+ (id)insertState:(id)arg1 forBaseState:(id)arg2 inDatabase:(id)arg3;	// IMP=0x00100000003e1e14
- (id)secondaryAccessory;	// IMP=0x00400000003e2f37
- (id)accessory;	// IMP=0x00100000003e2ea3
- (id)footerValue;	// IMP=0x00100000003e2e0f
- (id)bodyImage;	// IMP=0x00100000003e2d7b
- (id)bodyValue;	// IMP=0x00100000003e2ce7
- (id)titleValue;	// IMP=0x00100000003e2c53
- (_Bool)deleteFromDatabase;	// IMP=0x00100000003e2a2e
- (id)initWithState:(id)arg1 forBaseState:(id)arg2 forTitleValue:(id)arg3 forBodyValue:(id)arg4 forBodyImage:(id)arg5 forFooterValue:(id)arg6 forAccessory:(id)arg7 forSecondaryAccessory:(id)arg8 inDatabase:(id)arg9;	// IMP=0x00100000003e1c04

@end

