//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@interface _CircleView : UIView
{
    _Bool _usesRoundedRectInsteadOfCircle;	// 8 = 0x8
}

@property(nonatomic) _Bool usesRoundedRectInsteadOfCircle; // @synthesize usesRoundedRectInsteadOfCircle=_usesRoundedRectInsteadOfCircle;
- (void)tintColorDidChange;	// IMP=0x001000000000a8c6
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x001000000000a758

@end

