//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class EKCalendarResourceChangeNotification, NSString;

@interface CalendarMessageResourceChangeCell
{
    NSString *_dateString;	// 8 = 0x8
    NSString *_changeString;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000f81f7
@property(retain, nonatomic) EKCalendarResourceChangeNotification *notification; // @dynamic notification;
- (unsigned long long)options;	// IMP=0x00100000000f816a
- (id)actions;	// IMP=0x00100000000f815d
- (long long)_changedPropertyCount;	// IMP=0x00100000000f80d1
- (id)bodyStringDict;	// IMP=0x00100000000f8077
- (id)titleStrings;	// IMP=0x00100000000f7eac

@end

