//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class EKCalendarDate;

@interface DayRangeCacheKey : NSObject
{
    EKCalendarDate *_occurrenceStart;	// 8 = 0x8
    EKCalendarDate *_occurrenceEnd;	// 16 = 0x10
    EKCalendarDate *_rangeBoundStart;	// 24 = 0x18
    EKCalendarDate *_rangeBoundEnd;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000005089a
@property(readonly, nonatomic) EKCalendarDate *rangeBoundEnd; // @synthesize rangeBoundEnd=_rangeBoundEnd;
@property(readonly, nonatomic) EKCalendarDate *rangeBoundStart; // @synthesize rangeBoundStart=_rangeBoundStart;
@property(readonly, nonatomic) EKCalendarDate *occurrenceEnd; // @synthesize occurrenceEnd=_occurrenceEnd;
@property(readonly, nonatomic) EKCalendarDate *occurrenceStart; // @synthesize occurrenceStart=_occurrenceStart;
- (unsigned long long)hash;	// IMP=0x0010000000050781
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000005058b
- (id)initWithOccurrenceStart:(id)arg1 occurrenceEnd:(id)arg2 rangeBoundStart:(id)arg3 rangeBoundEnd:(id)arg4;	// IMP=0x00100000000504a3

@end

