//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class CUIKCalendarModel, NSString, UITableView;

@interface IdentitySwitcherViewController : UIViewController
{
    CUIKCalendarModel *_model;	// 8 = 0x8
    UITableView *_tableView;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000010499f
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0010000000104763
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000104324
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000104252
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00100000001041ff
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00100000001041f4
- (struct CGSize)preferredContentSize;	// IMP=0x001000000010418c
- (void)loadView;	// IMP=0x0010000000104039
- (id)initWithModel:(id)arg1;	// IMP=0x0010000000103fcb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

