//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PhoneShowAddEventTest
{
}

+ (id)_animationSubTestName;	// IMP=0x004000000009ab97
+ (id)_delaySubTestName;	// IMP=0x001000000009ab8a
- (void)_viewControllerAppeared:(id)arg1;	// IMP=0x004000000009af9c
- (void)runTest;	// IMP=0x001000000009aba4

@end

