//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UINavigationController.h>

@class CUIKCalendarModel, NSString, SearchResultsViewController, UISearchBar;

@interface SearchResultsNavigationController : UINavigationController
{
    _Bool _initialPresentationHasCompleted;	// 8 = 0x8
    SearchResultsViewController *_searchResultsViewController;	// 16 = 0x10
    UISearchBar *_searchBar;	// 24 = 0x18
    CUIKCalendarModel *_model;	// 32 = 0x20
}

+ (id)_todayLocalizedString;	// IMP=0x002000000016b4dc
+ (_Bool)_shouldForwardViewWillTransitionToSize;	// IMP=0x0010000000169a9f
- (void).cxx_destruct;	// IMP=0x002000000016b5d2
@property(nonatomic) _Bool initialPresentationHasCompleted; // @synthesize initialPresentationHasCompleted=_initialPresentationHasCompleted;
@property(retain, nonatomic) CUIKCalendarModel *model; // @synthesize model=_model;
@property(nonatomic) __weak UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) SearchResultsViewController *searchResultsViewController; // @synthesize searchResultsViewController=_searchResultsViewController;
- (void)todayPressed;	// IMP=0x001000000016b3c8
- (void)_setSearchBarEnabledState:(_Bool)arg1;	// IMP=0x001000000016afd7
- (void)_updateTodayButtonPosition;	// IMP=0x001000000016ad7d
- (void)_showSearchBar;	// IMP=0x001000000016aad8
- (void)_hideSearchBar;	// IMP=0x001000000016a9c1
- (void)animateShowingSearchBarAnimated:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000016a841
- (void)hideSearchBarForNavigationTransitionAnimated:(_Bool)arg1;	// IMP=0x001000000016a675
- (void);	// IMP=0x001000000016a457
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;	// IMP=0x001000000016a38d
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x0010000000169aa7
- (void)viewDidLoad;	// IMP=0x0010000000169a07
- (void)dealloc;	// IMP=0x0010000000169992
- (id)initWithModel:(id)arg1 window:(id)arg2;	// IMP=0x001000000016958b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

