//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface APSPowerAssertion
{
}

- (id)initWithName:(id)arg1 category:(int)arg2 holdDuration:(double)arg3;	// IMP=0x00400000000719a5

@end

