//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface _TtC9storekitd14SQLiteFunction : NSObject
{
    MISSING_TYPE *name;	// 8 = 0x8
    MISSING_TYPE *argumentCount;	// 24 = 0x18
    MISSING_TYPE *flagStorage;	// 32 = 0x20
    MISSING_TYPE *implementation;	// 40 = 0x28
}

+ (id)unarchiveRenewalInfoAsJSON;	// IMP=0x0020000000173e81
+ (id)extractJWSPayload;	// IMP=0x0010000000173baa
- (void).cxx_destruct;	// IMP=0x00200000000a3027
- (id)init;	// IMP=0x00100000000a2fef
- (void)withUnsafePropertyPointers:(CDUnknownBlockType)arg1;	// IMP=0x00100000000a2f84
@property(nonatomic, readonly) int flags;
@property(nonatomic, readonly) _Bool canCallIndirectly;
@property(nonatomic, readonly) _Bool isPure;
@property(nonatomic, readonly) long long argumentCount; // @synthesize argumentCount;
@property(nonatomic, readonly) NSString *name;
- (void)applyTransformBinding:(id)arg1 atIndex:(int *)arg2;	// IMP=0x00100000000a317d
- (id)transformSQLWithRoot:(id)arg1;	// IMP=0x00100000000a310b

@end

