//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppleMediaServices/AMSDialogRequest.h>

@class NSDictionary, NSString;

@interface AMSDialogRequest (LibAppStoreDaemon)
- (void)_lib_setAnalyticsEventDictionary:(id)arg1;	// IMP=0x0020000000052472
- (id)_lib_analyticsEventDictionary;	// IMP=0x001000000005241b
- (void)lib_setAnalyticsDialogName:(id)arg1 eventInfo:(id)arg2;	// IMP=0x00100000000522fe
- (void)lib_setAnalyticsActionName:(id)arg1 forAction:(id)arg2;	// IMP=0x00100000000522e9
- (void)lib_postAnalyticsEventWithResult:(id)arg1 error:(id)arg2;	// IMP=0x00100000000522c0
@property(copy, nonatomic, setter=lib_setAnalyticsDialogName:) NSString *lib_analyticsDialogName;
@property(copy, nonatomic, setter=lib_setAnalyticsEventInfo:) NSDictionary *lib_analyticsEventInfo;
- (void)_lib_postAnalyticsEventWithResult:(id)arg1 error:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000052541
@end

