//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AKCASatoriReporter
{
}

- (void)didCompleteVerificationWithSuccess:(_Bool)arg1 duration:(unsigned long long)arg2;	// IMP=0x00400000000a08ab
- (void)didPerformVerificationWithSuccess:(_Bool)arg1 duration:(unsigned long long)arg2;	// IMP=0x00100000000a07f7
- (void)didCompleteWithSuccess:(_Bool)arg1 authorizationAlreadyComplete:(_Bool)arg2;	// IMP=0x00100000000a074e
- (id)initWithRequestID:(id)arg1;	// IMP=0x00100000000a06d5

@end

