//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AKClient;

@interface AKCustodianDaemonService : NSObject
{
    AKClient *_client;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000a8ba7
@property(readonly, nonatomic) AKClient *client; // @synthesize client=_client;
- (id)_trustedContactOperationsByIDFromArray:(id)arg1;	// IMP=0x00100000000a876c
- (void)performTrustedContactsDataSync:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a7cd3
- (_Bool)verifyRecoveryTransactionWithContext:(id)arg1 verifySessionID:(_Bool)arg2 error:(id *)arg3;	// IMP=0x00100000000a7936
- (void)sendEmbargoEndNotificationFeedbackWithContext:(id)arg1 urlKey:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000a73c8
- (void)fetchCustodianDataRecoveryKeyWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a6e58
- (void)fetchCustodianRecoveryTokenWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a669f
- (void)startCustodianRecoveryTransactionWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a62ff
- (void)fetchCustodianRecoveryCodeConfigurationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000a61f5
- (void)startCustodianRecoveryRequestWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a5cf7
- (void)updateCustodianRecoveryKeyWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a581c
- (void)revokeCustodianWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a534a
- (void)finalizeCustodianSetupWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a4e78
- (void)initiateCustodianSetupWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a48b8
- (void)dealloc;	// IMP=0x00100000000a484c
- (id)initWithClient:(id)arg1;	// IMP=0x00100000000a47e1
- (id)init;	// IMP=0x00100000000a47b6

@end

