//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AKDeviceListStoreMigrator
{
}

- (void).cxx_destruct;	// IMP=0x004000000015a3f0
- (id)init;	// IMP=0x001000000015a390
- (id)initWithExecutor:(id)arg1;	// IMP=0x001000000015a350
- (void)migrateSchemaFromVersion:(unsigned long long)arg1;	// IMP=0x001000000015a320
- (unsigned long long)currentSchemaVersion;	// IMP=0x0010000000159700
- (id)storeName;	// IMP=0x00100000001596d0

@end

