//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSError.h>

@interface NSError (ADTimerStore)
+ (id)_ad_timerStoreErrorWithCode:(long long)arg1;	// IMP=0x0020000000168b64
+ (id)_ad_alarmStoreErrorWithCode:(long long)arg1;	// IMP=0x00100000001aa146
+ (id)ad_calendarErrorWithCode:(long long)arg1;	// IMP=0x0010000000244246
+ (id)ad_siriTaskHandlerAceTranslationFailureError;	// IMP=0x001000000027f276
+ (id)ad_siriTaskHandlerErrorWithCode:(long long)arg1;	// IMP=0x001000000027f23d
- (_Bool)ad_isNetworkDownError;	// IMP=0x00200000001a8f29
- (_Bool)ad_requiresDampedRetry:(long long *)arg1;	// IMP=0x00100000001a8d2a
- (_Bool)ad_isPeerRemoteError;	// IMP=0x00100000001a8bcb
- (_Bool)ad_isPeerNotNearbyError;	// IMP=0x00100000001a8ab0
- (_Bool)ad_isPeerConnectionError;	// IMP=0x00100000001a894d
- (_Bool)ad_isRetryableSessionError;	// IMP=0x00100000001a878a
- (_Bool)ad_isUnrecoverablePeerError;	// IMP=0x00100000001a8716
- (_Bool)ad_isStricterRetryableConnectionError;	// IMP=0x00100000001a8571
- (_Bool)ad_isStricterUnreachableError;	// IMP=0x00100000001a848e
- (_Bool)ad_isRetryableConnectionError;	// IMP=0x00100000001a820a
- (_Bool)ad_isUnreachableError;	// IMP=0x00100000001a7f3f
- (_Bool)ad_isAssistantNotReadyError;	// IMP=0x00100000001a7f03
- (_Bool)ad_isInAssistantErrorDomain;	// IMP=0x00100000001a7eb5
@end

