//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SASyncGetCachedSyncAnchors.h>

@interface SASyncGetCachedSyncAnchors (ADResultObjectCache)
- (_Bool);	// IMP=0x0010000000243ba7
@end

