//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UISplitViewController.h>

@class MISSING_TYPE, NSUndoManager;

@interface _TtC9Reminders22TTRIRootViewController : UISplitViewController
{
    MISSING_TYPE *presenter;	// 8 = 0x8
    MISSING_TYPE *mainNavigationController;	// 24 = 0x18
    MISSING_TYPE *detailNavigationController;	// 32 = 0x20
    MISSING_TYPE *ttrMainViewController;	// 40 = 0x28
    MISSING_TYPE *pendingNavigateToRootPromise;	// 48 = 0x30
    MISSING_TYPE *activityItemsConfigurationProviding;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x002000000023d010
- (id)initWithStyle:(long long)arg1;	// IMP=0x001000000023cfd0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x001000000023cfa0
- (id)targetForAction:(SEL)arg1 withSender:(id)arg2;	// IMP=0x001000000023ce90
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x001000000023ccf0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x001000000023ccd0
@property(nonatomic, readonly) _Bool canBecomeFirstResponder;
@property(nonatomic, readonly) NSUndoManager *undoManager;
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000023cc10
- (void)splitViewControllerDidExpand:(id)arg1;	// IMP=0x001000000023daa0
- (void)splitViewControllerDidCollapse:(id)arg1;	// IMP=0x001000000023d8b0
- (long long)splitViewController:(id)arg1 topColumnForCollapsingToProposedTopColumn:(long long)arg2;	// IMP=0x001000000023d4b0
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;	// IMP=0x001000000023db50

@end

