//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;
@protocol UIActivityItemsConfigurationReading;

@interface _TtC9Reminders43TTRIRootActivityItemsConfigurationProviding : NSObject
{
    MISSING_TYPE *visibleList;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x004000000023d470
- (id)init;	// IMP=0x001000000023d440
@property(nonatomic, readonly) id <UIActivityItemsConfigurationReading> activityItemsConfiguration;

@end

