//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppSupportUI/NUIContainerStackView.h>

@class MISSING_TYPE, NSString;

@interface _TtC9Reminders30TTRIRemindersListMessagingView : NUIContainerStackView
{
    MISSING_TYPE *listLayout;	// 8 = 0x8
    MISSING_TYPE *emptyListMessaging;	// 9 = 0x9
    MISSING_TYPE *messagingViewDelegate;	// 16 = 0x10
    MISSING_TYPE *titleLabel;	// 32 = 0x20
    MISSING_TYPE *subtitleTextView;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000001da950
- (id)initWithArrangedSubviews:(id)arg1;	// IMP=0x00100000001da8f0
@property(nonatomic, copy) NSString *accessibilityLabel;
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000001da5b0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000001da580
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3;	// IMP=0x00100000001da9c0

@end

