//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APIDAccount, APIDAccountsSettings;

@interface APIDAccountProvider : NSObject
{
    APIDAccountsSettings *_accountSettings;	// 8 = 0x8
    id _accountChangedNotificationObject;	// 16 = 0x10
    APIDAccount *_idAccount;	// 24 = 0x18
}

+ (void)fetchGenderAndAgeData:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0040000000043cb5
+ (id)segmentData;	// IMP=0x0010000000043c0d
+ (id)privateUserAccount;	// IMP=0x0010000000043489
+ (id)userAccount;	// IMP=0x0010000000043439
+ (id)sharedInstance;	// IMP=0x00100000000433e4
- (void).cxx_destruct;	// IMP=0x002000000004445f
@property(retain) APIDAccount *idAccount; // @synthesize idAccount=_idAccount;
@property(retain) id accountChangedNotificationObject; // @synthesize accountChangedNotificationObject=_accountChangedNotificationObject;
@property(retain) APIDAccountsSettings *accountSettings; // @synthesize accountSettings=_accountSettings;
- (_Bool)_loadIDAccounts;	// IMP=0x0010000000043767
- (void)dealloc;	// IMP=0x00100000000436f1
- (id)init;	// IMP=0x00100000000434d9

@end

