//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <APFoundation/APSettings.h>

@class NSNumber;

@interface APInternalCacheSettings : APSettings
{
}

+ (id)storageWithDefaultValues:(id)arg1;	// IMP=0x0040000000141b4b
@property(readonly, nonatomic) double diagnosticsIntervalValue;

// Remaining properties
@property(retain, nonatomic) NSNumber *diagnosticsInterval; // @dynamic diagnosticsInterval;

@end

