//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface Synchronize : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
}

+ (void)async:(CDUnknownBlockType)arg1;	// IMP=0x0020000000005280
+ (void)sync:(CDUnknownBlockType)arg1;	// IMP=0x00100000000050ed
+ (id)queue;	// IMP=0x0010000000005096
- (void).cxx_destruct;	// IMP=0x0020000000005400
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)async:(CDUnknownBlockType)arg1;	// IMP=0x0010000000005336
- (void)sync:(CDUnknownBlockType)arg1;	// IMP=0x00100000000051ca
- (id)initWithQueueName:(id)arg1;	// IMP=0x0010000000005011

@end

