//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;
@protocol OS_dispatch_queue, TUNotifyObserver;

@interface CSDDeviceLockStateObserver : NSObject
{
    _Bool _hasBeenUnlockedSinceBoot;	// 8 = 0x8
    int _mobileKeyLockState;	// 12 = 0xc
    CDUnknownBlockType _hasBeenUnlockedSinceBootBlock;	// 16 = 0x10
    CDUnknownBlockType _mobileKeyLockStateBlock;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_queue;	// 32 = 0x20
    NSMutableArray *_firstUnlockCallbacks;	// 40 = 0x28
    NSMutableArray *_whenUnlockedCallbacks;	// 48 = 0x30
    id <TUNotifyObserver> _firstUnlockObserver;	// 56 = 0x38
    id <TUNotifyObserver> _whenUnlockedObserver;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00200000001aaed7
@property(retain, nonatomic) id <TUNotifyObserver> whenUnlockedObserver; // @synthesize whenUnlockedObserver=_whenUnlockedObserver;
@property(retain, nonatomic) id <TUNotifyObserver> firstUnlockObserver; // @synthesize firstUnlockObserver=_firstUnlockObserver;
@property(nonatomic) int mobileKeyLockState; // @synthesize mobileKeyLockState=_mobileKeyLockState;
@property(nonatomic) _Bool hasBeenUnlockedSinceBoot; // @synthesize hasBeenUnlockedSinceBoot=_hasBeenUnlockedSinceBoot;
- (_Bool);	// IMP=0x00100000001aae7d
@property(retain, nonatomic) NSMutableArray *whenUnlockedCallbacks; // @synthesize whenUnlockedCallbacks=_whenUnlockedCallbacks;
@property(retain, nonatomic) NSMutableArray *firstUnlockCallbacks; // @synthesize firstUnlockCallbacks=_firstUnlockCallbacks;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) CDUnknownBlockType mobileKeyLockStateBlock; // @synthesize mobileKeyLockStateBlock=_mobileKeyLockStateBlock;
@property(copy, nonatomic) CDUnknownBlockType hasBeenUnlockedSinceBootBlock; // @synthesize hasBeenUnlockedSinceBootBlock=_hasBeenUnlockedSinceBootBlock;
- (void)performBlockWhenUnlocked:(CDUnknownBlockType)arg1;	// IMP=0x00100000001aab21
- (void)performBlockAfterFirstUnlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001aa8be
- (void)_handleDeviceLockStatusNotification;	// IMP=0x00100000001aa5d0
- (void)_handleDeviceFirstUnlockNotification;	// IMP=0x00100000001aa405
- (void)_refreshHasBeenUnlockedSinceBoot;	// IMP=0x00100000001aa2b9
- (id)initWithQueue:(id)arg1;	// IMP=0x00100000001aa2a0
- (id)initWithFirstUnlockObserver:(id)arg1 whenUnlockedObserver:(id)arg2 queue:(id)arg3;	// IMP=0x00100000001a9fdd

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

