//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface CSDMessagingConversationActivitySessionLocallyPersistedMetadata : PBCodable
{
    _Bool _locallyInitiated;	// 8 = 0x8
    struct {
        unsigned int locallyInitiated:1;
    } _has;	// 12 = 0xc
}

@property(nonatomic) _Bool locallyInitiated; // @synthesize locallyInitiated=_locallyInitiated;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000081e07
- (unsigned long long)hash;	// IMP=0x0010000000081ddc
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000081d3a
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000081cd6
- (void)copyTo:(id)arg1;	// IMP=0x0010000000081cb0
- (void)writeTo:(id)arg1;	// IMP=0x0010000000081c84
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000081c77
- (id)dictionaryRepresentation;	// IMP=0x0010000000081a24
- (id)description;	// IMP=0x0010000000081975
@property(nonatomic) _Bool hasLocallyInitiated;

@end

