//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray;

@interface CSDMessagingLinkSyncUpdateMessage : PBCodable
{
    NSMutableArray *_links;	// 8 = 0x8
    unsigned int _version;	// 16 = 0x10
    CDStruct_f20694ce _has;	// 20 = 0x14
}

+ (Class)linkType;	// IMP=0x00200000000ef5ac
- (void).cxx_destruct;	// IMP=0x00200000000f021e
@property(retain, nonatomic) NSMutableArray *links; // @synthesize links=_links;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000f0078
- (unsigned long long)hash;	// IMP=0x00100000000f002c
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000eff71
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000efd83
- (void)copyTo:(id)arg1;	// IMP=0x00100000000efca0
- (void)writeTo:(id)arg1;	// IMP=0x00100000000efb45
- (_Bool);	// IMP=0x00100000000efb38
- (id)dictionaryRepresentation;	// IMP=0x00100000000ef66c
- (id)description;	// IMP=0x00100000000ef5bd
- (id)linkAtIndex:(unsigned long long)arg1;	// IMP=0x00100000000ef58f
- (unsigned long long)linksCount;	// IMP=0x00100000000ef572
- (void)addLink:(id)arg1;	// IMP=0x00100000000ef508
- (void)clearLinks;	// IMP=0x00100000000ef4eb
@property(nonatomic) _Bool hasVersion;

@end

