//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSDictionary;

@interface CSDSharedConversationServerBag : NSObject
{
    MISSING_TYPE *fitnessPlusAppBundleID;	// 8 = 0x8
    MISSING_TYPE *fitnessPlusDaemonBundleID;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00400000002a8eb3
- (id)init;	// IMP=0x00100000002a8e72
@property(nonatomic, readonly) _Bool faceTimeSpamReportingCheckPrefix;
@property(nonatomic, readonly) double liveLookupTimeoutSeconds;
@property(nonatomic, readonly) unsigned long long voIPDOSMinJailTimeSeconds;
@property(nonatomic, readonly) unsigned long long voIPDOSMaxJailTimeSeconds;
@property(nonatomic, readonly) unsigned long long voIPDOSTimeSeconds;
@property(nonatomic, readonly) long long voIPDOSCount;
@property(nonatomic, readonly) unsigned long long clearMuteCacheDelay;
@property(nonatomic, readonly) long long maxVoicemailLengthFudgeSeconds;
@property(nonatomic, readonly) long long maxVoicemailLengthSeconds;
@property(nonatomic, readonly) long long answeringMachineDidStopTimeout;
@property(nonatomic, readonly) unsigned long long answeringMachineAudioPowerLevelCount;
@property(nonatomic, readonly) float answeringMachineAudioPowerLevelThreshold;
@property(nonatomic, readonly) unsigned long long watchLPMDialDelay;
@property(nonatomic, readonly) unsigned long long watchInviteNotificationDelay;
@property(nonatomic, readonly) unsigned long long handoffUPlusOneLeaveDelay;
@property(nonatomic, readonly) unsigned long long handoffUPlusOneLeaveTimeout;
- (_Bool)gftaasPseudonymsEnabled:(id)arg1;	// IMP=0x00100000002a88b9
- (_Bool)isGuestModeSupported;	// IMP=0x00100000002a883f
- (_Bool)isUPlusNDowngradeAvailable;	// IMP=0x00100000002a87f3
@property(nonatomic, readonly) unsigned long long maxRemoteSpatialPersonaParticipants;
- (_Bool)isGFTDowngradeToOneToOneAvailable;	// IMP=0x00100000002a875f
@property(nonatomic, readonly) unsigned long long messageRetryIntervalMillis;
@property(nonatomic, readonly) unsigned long long messageRetryMaxAttempts;
- (id)stableBundleIdentifierForLocalBundleIdentifier:(id)arg1;	// IMP=0x00100000002a8655
@property(nonatomic, readonly) unsigned long long handoffAudioDeviceTimeout;
- (id)localBundleIDForActivityIdentifier:(id)arg1;	// IMP=0x00100000002a8472
@property(nonatomic, readonly) NSDictionary *activityIdentifierBundleIDMapping;
@property(nonatomic, readonly) unsigned long long letMeInRequestUINotificationGracePeriod;
@property(nonatomic, readonly) unsigned long long letMeInRequestRecoveryTimeout;
- (_Bool)isMSNPillDataSourceEnabled;	// IMP=0x00100000002a80d6
@property(nonatomic, readonly) unsigned long long letMeInRequestNotificationTimeout;
@property(nonatomic, readonly) unsigned long long linkSyncRecoverTimeLimit;
@property(nonatomic, readonly) unsigned long long linkSyncRecoverFailureLimit;
@property(nonatomic, readonly) unsigned long long webNicknameLengthLimit;
@property(nonatomic, readonly) unsigned long long inactiveLinkCacheLimit;
@property(nonatomic, readonly) unsigned long long inactiveLinkPseudonymExpiry;
@property(nonatomic, readonly) unsigned long long linkRemainingTimeBeforeAutoRenewal;
@property(nonatomic, readonly) unsigned long long linkRenewalExtensionTime;
@property(nonatomic, readonly) unsigned long long addParticipantFromQRTime;
@property(nonatomic, readonly) unsigned long long linkPseudonymExpiry;
@property(nonatomic, readonly) unsigned long long maxKickMemberRetries;
@property(nonatomic, readonly) unsigned long long maxActiveParticipantFetchRetries;
- (_Bool)isFaceTimeMyselfEnabled;	// IMP=0x00100000002a7d2a
- (_Bool)shouldRingForIncomingCallEnabled;	// IMP=0x00100000002a7cde
- (_Bool)isControlMessageOverQREnabled;	// IMP=0x00100000002a7c92
- (_Bool)isUPlusOneSessionCapabilitiesEnabled;	// IMP=0x00100000002a7c46
- (_Bool)isNoConversationParticipantEndCallEnabled;	// IMP=0x00100000002a7bfa
- (_Bool);	// IMP=0x00100000002a7bae
- (_Bool)isSharePlayVersionCheckEnabled;	// IMP=0x00100000002a7b62
- (_Bool)isModernGFTEnabled;	// IMP=0x00100000002a7b16
- (_Bool)isParticipantIDToURIIncludedInPush;	// IMP=0x00100000002a7aca
- (_Bool)isShortMKIEnabled;	// IMP=0x00100000002a7a7e
@property(nonatomic, readonly) unsigned long long groupFaceTimeTLESampleRate;
@property(nonatomic, readonly) unsigned long long uPlusOneAuthTagSampleRate;
- (_Bool)isAutomaticUpgradingEnabled;	// IMP=0x00100000002a79a2
@property(nonatomic, readonly) unsigned long long activeParticipantRefreshDelay;
@property(nonatomic, readonly) unsigned long long rebroadcastTimeThreshold;
@property(nonatomic, readonly) unsigned long long noConversationParticipantTimeout;
@property(nonatomic, readonly) unsigned long long AVCBlobRecoveryTimeout;
@property(nonatomic, readonly) unsigned long long AVCBlobRecoveryGracePeriod;
@property(nonatomic, readonly) unsigned long long greenTeaHandoffTimeout;
@property(nonatomic, readonly) unsigned long long sessionCleanupTimeout;
@property(nonatomic, readonly) unsigned long long activeParticipantPruningTimeout;

// Remaining properties
@property(nonatomic, readonly) _Bool FaceTimeMyselfEnabled;
@property(nonatomic, readonly) _Bool automaticUpgradingEnabled;
@property(nonatomic, readonly) _Bool controlMessageOverQREnabled;
@property(nonatomic, readonly) _Bool gftDowngradeToOneToOneAvailable;
@property(nonatomic, readonly) _Bool guestModeSupported;
@property(nonatomic, readonly) _Bool letMeInRequestUIForUnknownParticipantEnabled;
@property(nonatomic, readonly) _Bool modernGFTEnabled;
@property(nonatomic, readonly) _Bool msnPillDataSourceEnabled;
@property(nonatomic, readonly) _Bool noConversationParticipantEndCallEnabled;
@property(nonatomic, readonly) _Bool participantIDToURIIncludedInPush;
@property(nonatomic, readonly) _Bool ringForIncomingCallEnabled;
@property(nonatomic, readonly) _Bool sharePlayVersionCheckEnabled;
@property(nonatomic, readonly) _Bool shortMKIEnabled;
@property(nonatomic, readonly) _Bool uPlusNDowngradeAvailable;
@property(nonatomic, readonly) _Bool uPlusOneSessionCapabilitiesEnabled;

@end

