//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface CSDSpeechAssetManager : NSObject
{
    MISSING_TYPE *hasSpeechAssets;	// 8 = 0x8
    MISSING_TYPE *fetchingSpeechAssets;	// 9 = 0x9
    MISSING_TYPE *queue;	// 16 = 0x10
    MISSING_TYPE *languageManager;	// 0 = 0x0
    MISSING_TYPE *delegates;	// 0 = 0x0
    MISSING_TYPE *assetSetObserver;	// 0 = 0x0
    MISSING_TYPE *$__lazy_storage_$_downloadSpeechAssetPath;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x00400000002c55d3
- (id)init;	// IMP=0x00100000002c559e
- (void)handleCurrentLocaleDidChange;	// IMP=0x00100000002c446c
- (id)initWithQueue:(id)arg1;	// IMP=0x00100000002c2e87

@end

