//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <EventKit/EKEventStore.h>

@interface EKEventStore (EventKitSync)
+ (long long)eks_storeCount;	// IMP=0x0010000000079a4e
+ (id)eks_eventStoreFor:(id)arg1;	// IMP=0x0010000000079960
+ (id)eks_eventOnlyStoreFor:(id)arg1;	// IMP=0x0010000000079906
+ (id)eks_eventOnlyStoreIgnoringExternalChangesFor:(id)arg1 withClientId:(id)arg2;	// IMP=0x001000000007950c
- (id)eks_sourcesAlwaysIncludingLocal;	// IMP=0x0020000000079c85
@end

