//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSString;

@interface NDTSQKeyValueStore
{
    NSString *_insert;	// 8 = 0x8
    NSString *_exchange;	// 16 = 0x10
    NSString *_select;	// 24 = 0x18
    NSString *_delete;	// 32 = 0x20
    MISSING_TYPE *_baseName;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0020000000016ee0
- (void)deleteValueForKey:(id)arg1;	// IMP=0x0010000000016de8
- (void)setData:(id)arg1 forKey:(id)arg2;	// IMP=0x0010000000016caa
- (id)getDataForKey:(id)arg1 default:(id)arg2;	// IMP=0x0010000000016ae1
- (void)setString:(id)arg1 forKey:(id)arg2;	// IMP=0x00100000000169a7
- (id)getStringForKey:(id)arg1 default:(id)arg2;	// IMP=0x00100000000167b9
- (void)setDouble:(double)arg1 forKey:(id)arg2;	// IMP=0x0010000000016693
- (double)getDoubleForKey:(id)arg1 default:(double)arg2;	// IMP=0x0010000000016509
- (_Bool)compareAndSwapIntegerValue:(long long)arg1 expectedExistingValue:(long long)arg2 forKey:(id)arg3;	// IMP=0x00100000000163bc
- (void)setInteger:(long long)arg1 forKey:(id)arg2;	// IMP=0x0010000000016299
- (long long)getIntegerForKey:(id)arg1 default:(long long)arg2;	// IMP=0x001000000001611f
- (id)instanceName;	// IMP=0x00100000000160ef
- (void)migrateFrom:(long long)arg1;	// IMP=0x00100000000160e9
- (long long)currentVersion;	// IMP=0x00100000000160de
- (void)createTables;	// IMP=0x0010000000016077
- (id)initWithName:(id)arg1;	// IMP=0x0010000000015f1b

@end

