//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSXPCConnection;

@interface TIKBDClientProxy : NSObject
{
    NSXPCConnection *_connection;	// 8 = 0x8
}

+ (id)KBDClientProxyWithConnection:(id)arg1;	// IMP=0x002000000000bc21
- (void).cxx_destruct;	// IMP=0x002000000000beca
@property(readonly, nonatomic) __weak NSXPCConnection *connection; // @synthesize connection=_connection;
- (void)closeRequestToken:(id)arg1;	// IMP=0x001000000000beae
- (void)pushCandidateResultSet:(id)arg1 requestToken:(id)arg2;	// IMP=0x001000000000bdd0
- (void)pushCandidates:(id)arg1 requestToken:(id)arg2;	// IMP=0x001000000000bcf2
- (void)invalidate;	// IMP=0x001000000000bce2
- (id)initWithConnection:(id)arg1;	// IMP=0x001000000000bc7e
- (id)init;	// IMP=0x001000000000bc6a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

