//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC19appstorecomponentsd6Daemon : NSObject
{
    MISSING_TYPE *dialogHandler;	// 8 = 0x8
    MISSING_TYPE *listener;	// 16 = 0x10
    MISSING_TYPE *connections;	// 24 = 0x18
    MISSING_TYPE *session;	// 32 = 0x20
    MISSING_TYPE *shutdownTimer;	// 40 = 0x28
    MISSING_TYPE *keepAlive;	// 48 = 0x30
    MISSING_TYPE *widgetEventListener;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00400000000a9250
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00100000000a91b0
- (id)init;	// IMP=0x00100000000a8c30

@end

