//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC19appstorecomponentsd19AppOfferStateClient : NSObject
{
    MISSING_TYPE *objectGraph;	// 8 = 0x8
    MISSING_TYPE *appStateController;	// 16 = 0x10
    MISSING_TYPE *arcadeSubscription;	// 56 = 0x38
    MISSING_TYPE *restrictions;	// 96 = 0x60
    MISSING_TYPE *contingentOffers;	// 136 = 0x88
    MISSING_TYPE *appStoreInstallStateMonitor;	// 176 = 0xb0
    MISSING_TYPE *jsStackManager;	// 216 = 0xd8
    MISSING_TYPE *localizer;	// 256 = 0x100
    MISSING_TYPE *delegate;	// 296 = 0x128
    MISSING_TYPE *stateLock;	// 304 = 0x130
    MISSING_TYPE *observations;	// 312 = 0x138
    MISSING_TYPE *isUpdatingArcadeSubscription;	// 320 = 0x140
    MISSING_TYPE *isUpdatingContingentOfferSubscription;	// 321 = 0x141
    MISSING_TYPE *appDistribution;	// 328 = 0x148
}

- (void).cxx_destruct;	// IMP=0x0040000000053bf0
- (id)init;	// IMP=0x001000000005e510
- (void)decorateBuyParamsForOffer:(id)arg1 withActivity:(id)arg2 withReplyHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000005e3f0
- (void)viewAppForAppDistributionOffer:(id)arg1;	// IMP=0x001000000005d710
- (void)reinstallWatchSystemAppWithBundleID:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000005d540
- (void)reinstallWatchAppWithID:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000005cbb0
- (void)performActionOfOffer:(id)arg1 withActivity:(id)arg2 inContext:(id)arg3 withReplyHandler:(CDUnknownBlockType)arg4;	// IMP=0x001000000005c1f0
- (void)stopObservingStateOfOffers:(id)arg1;	// IMP=0x0010000000059960
- (void)startObservingStateOfOffers:(id)arg1;	// IMP=0x0010000000058f60
- (void)didChangeAppCapabilities:(id)arg1;	// IMP=0x00100000000567d0
- (void)dealloc;	// IMP=0x0010000000053bd0

@end

