//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSSet, NSString;

@interface ASCLockupBatchRequest : NSObject
{
    _Bool _enableAppDistribution;	// 8 = 0x8
    NSSet *_ids;	// 16 = 0x10
    NSString *_kind;	// 24 = 0x18
    NSString *_context;	// 32 = 0x20
    NSString *_clientID;	// 40 = 0x28
    NSDictionary *_mediaQueryParams;	// 48 = 0x30
    NSString *_platformOverride;	// 56 = 0x38
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000019a0f
+ (id)lockupBatchRequestsFromRequests:(id)arg1;	// IMP=0x0010000000018f1d
- (void).cxx_destruct;	// IMP=0x002000000001acd3
@property(readonly, copy, nonatomic) NSString *platformOverride; // @synthesize platformOverride=_platformOverride;
@property(readonly, copy, nonatomic) NSDictionary *mediaQueryParams; // @synthesize mediaQueryParams=_mediaQueryParams;
@property(readonly, nonatomic) _Bool enableAppDistribution; // @synthesize enableAppDistribution=_enableAppDistribution;
@property(readonly, copy, nonatomic) NSString *clientID; // @synthesize clientID=_clientID;
@property(readonly, copy, nonatomic) NSString *context; // @synthesize context=_context;
@property(readonly, copy, nonatomic) NSString *kind; // @synthesize kind=_kind;
@property(readonly, copy, nonatomic) NSSet *ids; // @synthesize ids=_ids;
- (id)lockupBatchRequestWithIDs:(id)arg1;	// IMP=0x001000000001ab4c
@property(readonly, copy, nonatomic) NSArray *requests;
- (id)description;	// IMP=0x001000000001a4e1
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000001a05e
- (unsigned long long)hash;	// IMP=0x0010000000019ed4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000019ec9
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000019d25
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000019a17
- (id)_initWithIDs:(id)arg1 kind:(id)arg2 context:(id)arg3 clientID:(id)arg4 enableAppDistribution:(_Bool)arg5 mediaQueryParams:(id)arg6 platformOverride:(id)arg7;	// IMP=0x0010000000019942
- (id)initWithIDs:(id)arg1 kind:(id)arg2 context:(id)arg3;	// IMP=0x0010000000019856

@end

