//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, NSURL;

@protocol SiriSharedUIInteractionDelegate <NSObject>
- (void)userDidReportConcern;
- (void)siriViewControllerSetStatusViewHidden:(_Bool)arg1;
- (void)siriViewControllerShouldOpenUrl:(NSURL *)arg1;
- (void)siriViewControllerHeightDidChange;
- (void)siriSnippetViewControllerPerformAceCommands:(NSArray *)arg1;
- (void)siriSnippetViewControllerShouldPushSirilandSnippets:(NSArray *)arg1;

@optional
- (void)siriViewControllerShouldRequestTextInputWithUtterance:(NSString *)arg1;
@end

