//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSArray, SFCard, SiriSharedUISmartDialogView;

@protocol SiriSharedUISAEViewStateDelegate <NSObject>
- (_Bool)alwaysShowRecognizedSpeech;
- (void)setSmartDialogPluginBlock:(void (^)(void))arg1;
- (void)setSmartDialogCardBlock:(void (^)(void))arg1;
- (SFCard *)filterTranscriptItemsForSAEDialogBoxContent:(NSArray *)arg1;
- (SiriSharedUISmartDialogView *)createNewSmartDialog;
- (void)performPillCollapseAnimation;
- (void)presentResultAnimation:(_Bool)arg1;
- (void)performSinglePillExpandAnimation;
- (void)performPillMergeAndCrossfadeAnimation;
- (void)presentLatencyPillAnimation;
- (_Bool)hasPendingUpdates;
- (void)willPresentResult;
- (void)didPresentContent;
- (void)didSetTranscriptItems;
- (void)smartDialogContentDidChange;
- (void)didSetServerUtterance:(NSArray *)arg1;
- (void)didSetInputType:(long long)arg1;

@optional
- (void)didSetInputTypeFromTextToVisualIntelligenceCamera;
- (void)speechRecognitionHypothesisUpdated;
- (void)startTextFieldLatency;
- (void)didSetInputTypeFromTextToVoice;
@end

