//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC4Maps18DirectionsETAModel : _TtCs12_SwiftObject
{
    MISSING_TYPE *_ETAString;	// 0 = 0x0
    MISSING_TYPE *_isDriveable;	// 0 = 0x0
    MISSING_TYPE *showETA;	// 0 = 0x0
    MISSING_TYPE *mapItem;	// 15967280 = 0xf3a430
    MISSING_TYPE *searchAlongRoute;	// 510116 = 0x7c8a4
    MISSING_TYPE *id;	// 15967280 = 0xf3a430
}

@end

