//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC4Maps32AirQualityConditionsDataProvider : NSObject
{
    MISSING_TYPE *observers;	// 8 = 0x8
    MISSING_TYPE *airQualityConditions;	// 16 = 0x10
    MISSING_TYPE *updatingTimer;	// 24 = 0x18
    MISSING_TYPE *lastSavedLocation;	// 32 = 0x20
    MISSING_TYPE *weatherService;	// 40 = 0x28
    MISSING_TYPE *enabled;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x002000000000c6b0
- (id)init;	// IMP=0x001000000000e710
- (void)removeObserver:(id)arg1;	// IMP=0x001000000000c9b0
- (void)addObserver:(id)arg1;	// IMP=0x001000000000c990
@property(nonatomic) _Bool enabled; // @synthesize enabled;
- (void)dealloc;	// IMP=0x001000000000c690
- (void)weatherLocationDataProvider:(id)arg1 didChangeLocation:(id)arg2;	// IMP=0x001000000000e7b0

@end

