//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC4Maps16EVChargerUtility : NSObject
{
}

+ (id)realTimeEVChargerDisplayStringWithEvCharger:(id)arg1 mapDisplay:(_Bool)arg2;	// IMP=0x0020000000203a60
+ (id)chargerStringForNonRealDataWithChargerNumber:(long long)arg1;	// IMP=0x0010000000203a20
+ (int)chargerStatusForNonRealData;	// IMP=0x0010000000203a10
+ (int)realTimeEVChargerStatusWithEvCharger:(id)arg1;	// IMP=0x0010000000203910
- (id)init;	// IMP=0x0040000000203ac0

@end

