//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray;

@interface _TtC4Maps20MapsFavoritesManager : NSObject
{
    MISSING_TYPE *etaTimer;	// 8 = 0x8
    MISSING_TYPE *isETATimerRunning;	// 16 = 0x10
    MISSING_TYPE *$__lazy_storage_$_msgRoutine;	// 24 = 0x18
    MISSING_TYPE *observers;	// 32 = 0x20
    MISSING_TYPE *storeSubscriptionTypes;	// 40 = 0x28
    MISSING_TYPE *_shortcuts;	// 48 = 0x30
    MISSING_TYPE *_sortedShortcuts;	// 56 = 0x38
    MISSING_TYPE *_setupButtons;	// 64 = 0x40
    MISSING_TYPE *_suggestions;	// 72 = 0x48
    MISSING_TYPE *_hasInitialData;	// 80 = 0x50
    MISSING_TYPE *_needsSuggestions;	// 88 = 0x58
    MISSING_TYPE *active;	// 96 = 0x60
    MISSING_TYPE *mapViewMode;	// 104 = 0x68
}

+ (id)sharedManager;	// IMP=0x0040000000102240
- (void).cxx_destruct;	// IMP=0x002000000010a8e0
- (void)storeDidChangeWithTypes:(id)arg1;	// IMP=0x001000000010a870
- (void)valueChangedForGEOConfigKey:(CDStruct_065526f1)arg1;	// IMP=0x001000000010a4a0
- (void)unregisterObserver:(id)arg1;	// IMP=0x00100000001076b0
- (void)registerObserver:(id)arg1;	// IMP=0x0010000000107600
- (void)loadAllShortcutsWithCompletionHandler:(void (^)(NSError *))arg1;	// IMP=0x00100000001065a0
- (void)getShortcutsCountWithIncludeNearbyTransit:(_Bool)arg1 completionHandler:(void (^)(long long, NSError *))arg2;	// IMP=0x0010000000105680
- (id)shortcutForMapItem:(id)arg1;	// IMP=0x0010000000105620
- (void)proposePlacesForTypeWithType:(long long)arg1 completionHandler:(void (^)(NSArray *, NSError *))arg2;	// IMP=0x0010000000104dc0
- (id)init;	// IMP=0x0010000000103480
@property(nonatomic) long long mapViewMode; // @synthesize mapViewMode;
@property(nonatomic) _Bool active; // @synthesize active;
@property(nonatomic, readonly) NSArray *shortcutsForCarplay;
@property(nonatomic, readonly) NSArray *shortcutsForLibrary;
@property(nonatomic, readonly) NSArray *shortcutsForMapsHome;
@property(nonatomic) _Bool hasInitialData;
@property(nonatomic, copy) NSArray *suggestions;
@property(nonatomic, copy) NSArray *sortedShortcuts;
@property(nonatomic, copy) NSArray *shortcuts;
@property(nonatomic, copy) NSArray *storeSubscriptionTypes;
@property(nonatomic, readonly) id observers; // @synthesize observers;
- (void)migrateFavoritesIfNeededWithCompletionHandler:(void (^)(NSError *))arg1;	// IMP=0x001000000010d2b0

@end

