//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ASAuthorizationController, NSString;
@protocol AppleConnectSSOAuthenticatorDelegate;

@interface AppleConnectSSOAuthenticator : NSObject
{
    id <AppleConnectSSOAuthenticatorDelegate> _delegate;	// 8 = 0x8
    NSString *_appIdentifier;	// 16 = 0x10
    NSString *_envIdentifier;	// 24 = 0x18
    ASAuthorizationController *_authenticationController;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000b271dd
@property(retain, nonatomic) ASAuthorizationController *authenticationController; // @synthesize authenticationController=_authenticationController;
@property(retain, nonatomic) NSString *envIdentifier; // @synthesize envIdentifier=_envIdentifier;
@property(retain, nonatomic) NSString *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
@property(nonatomic) __weak id <AppleConnectSSOAuthenticatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)authorizationController:(id)arg1 didCompleteWithError:(id)arg2;	// IMP=0x0010000000b27068
- (void)authorizationController:(id)arg1 didCompleteWithAuthorization:(id)arg2;	// IMP=0x0010000000b26e40
- (void)authenticate;	// IMP=0x0010000000b26a17
- (id)queryItemsWithParameters:(id)arg1;	// IMP=0x0010000000b26863

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

