//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSString, UIStackView;

@interface ButtonsContainerViewController
{
    NSArray *_groupVCs;	// 8 = 0x8
    UIStackView *_stackView;	// 16 = 0x10
    _Bool _visualEffectDisabled;	// 24 = 0x18
    NSArray *_floatingButtonItems;	// 32 = 0x20
    NSString *_blurGroupName;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000032feb0
@property(copy, nonatomic) NSString *blurGroupName; // @synthesize blurGroupName=_blurGroupName;
@property(readonly, copy, nonatomic) NSArray *floatingButtonItems; // @synthesize floatingButtonItems=_floatingButtonItems;
- (void)refreshControls;	// IMP=0x001000000032fbb1
- (void)showVisibleControls:(long long)arg1;	// IMP=0x001000000032f9de
- (void)setVisibleControls:(long long)arg1;	// IMP=0x001000000032f802
- (void)hideNonVisibleControls:(long long)arg1;	// IMP=0x001000000032f62f
- (void)viewDidLoad;	// IMP=0x001000000032f404
- (void)loadView;	// IMP=0x001000000032f040
- (id)initWithFloatingButtonItems:(id)arg1 visualEffectDisabled:(_Bool)arg2;	// IMP=0x001000000032ef65
- (id)initWithFloatingButtonItems:(id)arg1;	// IMP=0x001000000032ef51
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x001000000032ef3d
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000032ef29
- (_Bool)_canShowWhileLocked;	// IMP=0x001000000032ef21

@end

