//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIImage;

@interface Car3DButton
{
    UIImage *_image2D;	// 8 = 0x8
    UIImage *_image3D;	// 16 = 0x10
    unsigned long long _buttonState;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000c86865
@property(nonatomic) unsigned long long buttonState; // @synthesize buttonState=_buttonState;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000c8653f

@end

