//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UITableViewCell.h>

@class UIImageView, UILabel;

@interface CarAddStopCell : UITableViewCell
{
    UIImageView *_iconImageView;	// 8 = 0x8
    UILabel *_addStopLabel;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000305f29
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0010000000305ee0
- (void)_updateAppearanceWithFocus:(_Bool)arg1;	// IMP=0x0010000000305e2e
- (void)_setupConstraints;	// IMP=0x00100000003058f5
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0010000000305541

@end

