//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class CarCardsUpdate, NSArray;

@protocol CarCardsUpdateDelegate <NSObject>
- (void)cardsUpdateWantsLayout:(CarCardsUpdate *)arg1;
- (void)cardsUpdate:(CarCardsUpdate *)arg1 applyConfigurations:(NSArray *)arg2;
- (void)cardsUpdate:(CarCardsUpdate *)arg1 finalizeUpdate:(unsigned long long)arg2 withCardConfigurations:(NSArray *)arg3;
- (void)cardsUpdate:(CarCardsUpdate *)arg1 prepareForUpdate:(unsigned long long)arg2 withCardConfigurations:(NSArray *)arg3;
@end

