//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class CardCustomBorderView, NSLayoutConstraint, NSString, UIVisualEffectView;
@protocol CardViewDelegate;

@interface CardView : UIView
{
    CardCustomBorderView *_customBorderView;	// 8 = 0x8
    unsigned long long _style;	// 16 = 0x10
    UIView *_shadowView;	// 24 = 0x18
    UIView *_contentView;	// 32 = 0x20
    UIVisualEffectView *_blurView;	// 40 = 0x28
    _Bool _canAddSubviews;	// 48 = 0x30
    _Bool _buttonCard;	// 49 = 0x31
    NSLayoutConstraint *_topConstraint;	// 56 = 0x38
    NSLayoutConstraint *_bottomConstraint;	// 64 = 0x40
    struct CGRect _savedBounds;	// 72 = 0x48
    _Bool _hideGrabber;	// 104 = 0x68
    _Bool _showFooterGrabber;	// 105 = 0x69
    id <CardViewDelegate> _delegate;	// 112 = 0x70
    NSString *_blurGroupName;	// 120 = 0x78
    double _height;	// 128 = 0x80
    double _overriddenIntrinsicHeight;	// 136 = 0x88
    NSLayoutConstraint *_heightConstraint;	// 144 = 0x90
}

- (void).cxx_destruct;	// IMP=0x0020000000cb9145
@property(retain, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
@property(nonatomic) double overriddenIntrinsicHeight; // @synthesize overriddenIntrinsicHeight=_overriddenIntrinsicHeight;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) _Bool showFooterGrabber; // @synthesize showFooterGrabber=_showFooterGrabber;
@property(nonatomic) _Bool hideGrabber; // @synthesize hideGrabber=_hideGrabber;
@property(copy, nonatomic) NSString *blurGroupName; // @synthesize blurGroupName=_blurGroupName;
@property(nonatomic) __weak id <CardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGSize)intrinsicContentSize;	// IMP=0x0010000000cb8f6d
- (void)showShadow:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0010000000cb8e1b
- (void)setLayoutStyle:(unsigned long long)arg1;	// IMP=0x0010000000cb8cdb
- (void)_setCornerRadiusWithMaskedCorners:(unsigned long long)arg1 cornerRadius:(double)arg2;	// IMP=0x0010000000cb8b3d
- (void)updateTheme;	// IMP=0x0010000000cb8b20
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0010000000cb89fd
- (void)setCaptureView:(id)arg1;	// IMP=0x0010000000cb8951
- (void)layoutSubviews;	// IMP=0x0010000000cb878e
- (void)insertSubview:(id)arg1 atIndex:(long long)arg2;	// IMP=0x0010000000cb8788
- (void)didAddSubview:(id)arg1;	// IMP=0x0010000000cb8724
- (void)_commonInitWithBlurType:(long long)arg1;	// IMP=0x0010000000cb7dae
- (id)initWithThickBlur;	// IMP=0x0010000000cb7c50
- (id)initAllowingBlurredForButton:(_Bool)arg1;	// IMP=0x0010000000cb7b8d
- (id)initAllowingBlurred:(_Bool)arg1;	// IMP=0x0010000000cb79cf
@property(readonly, nonatomic) UIView *contentView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

