//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOComposedRoute, NSArray, NSMutableArray, NSString, NavManeuverSignView, SteppingSignSizeAttributesCache;
@protocol CellVendor;

@interface DrivingWalkingSteppingSignGenerator : NSObject
{
    SteppingSignSizeAttributesCache *_sizeCache;	// 8 = 0x8
    GEOComposedRoute *_route;	// 16 = 0x10
    NSArray *_stepsWithCorrespondingSigns;	// 24 = 0x18
    id <CellVendor> _cellVendor;	// 32 = 0x20
    unsigned long long _signLayoutType;	// 40 = 0x28
    long long _options;	// 48 = 0x30
    NSMutableArray *_signs;	// 56 = 0x38
    NavManeuverSignView *_steppingSizingView;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0020000000eac9a7
@property(retain, nonatomic) NavManeuverSignView *steppingSizingView; // @synthesize steppingSizingView=_steppingSizingView;
@property(retain, nonatomic) NSMutableArray *signs; // @synthesize signs=_signs;
@property(readonly, nonatomic) long long options; // @synthesize options=_options;
@property(nonatomic) unsigned long long signLayoutType; // @synthesize signLayoutType=_signLayoutType;
@property(nonatomic) __weak id <CellVendor> cellVendor; // @synthesize cellVendor=_cellVendor;
@property(readonly, nonatomic) NSArray *stepsWithCorrespondingSigns; // @synthesize stepsWithCorrespondingSigns=_stepsWithCorrespondingSigns;
@property(readonly, nonatomic) GEOComposedRoute *route; // @synthesize route=_route;
@property(readonly) long long numberOfSigns;
- (void)rectForSignAtIndex:(long long)arg1 currentStepIndex:(unsigned long long)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000eac886
- (double)distanceFromPageControlBaselineToTopOfAuxView;	// IMP=0x0010000000eac85d
- (id)_signSizeAttributesForSign:(id)arg1 fittingSize:(struct CGSize)arg2;	// IMP=0x0010000000eac65e
- (double)distanceFromPageControlBaselineToBottomOfSignAtIndex:(long long)arg1 fittingSize:(struct CGSize)arg2;	// IMP=0x0010000000eac539
- (struct CGSize)sizeForSignAtIndex:(long long)arg1 fittingSize:(struct CGSize)arg2;	// IMP=0x0010000000eac3fc
- (long long)signIndexForStepIndex:(long long)arg1;	// IMP=0x0010000000eac329
- (long long)signIndexForStep:(id)arg1;	// IMP=0x0010000000eac2f5
- (id)stepAtSignIndex:(long long)arg1;	// IMP=0x0010000000eac266
- (id)auxViewAtIndex:(long long)arg1;	// IMP=0x0010000000eac25e
- (id)signAtIndex:(long long)arg1;	// IMP=0x0010000000eac15d
- (void)invalidateSizeCaches;	// IMP=0x0010000000eac147
- (id)currentViewStateForSignAtIndex:(long long)arg1;	// IMP=0x0010000000eac10b
- (void)updateInstruction:(id)arg1 forSignAtIndex:(long long)arg2;	// IMP=0x0010000000eabfb2
- (void)updateDistance:(double)arg1 forStepAtIndex:(long long)arg2;	// IMP=0x0010000000eabe9b
- (void)updateSignForStepAtIndex:(long long)arg1 maneuverInfo:(id)arg2;	// IMP=0x0010000000eabddc
- (void)resetDistanceForSignAtIndex:(long long)arg1;	// IMP=0x0010000000eabcdf
- (id)_distanceTextForStep:(id)arg1 distance:(double)arg2;	// IMP=0x0010000000eabc1c
- (id)_distanceTextForStep:(id)arg1;	// IMP=0x0010000000eabbb7
- (void)configureNavSignView:(id)arg1 withSign:(id)arg2;	// IMP=0x0010000000eaba91
- (void)_configureSign:(id)arg1 forSteppingWithStep:(id)arg2;	// IMP=0x0010000000eab3c2
- (void)_configureSign:(id)arg1 withStep:(id)arg2;	// IMP=0x0010000000eaad3e
- (void)_configureWithRoute:(id)arg1;	// IMP=0x0010000000eaa962
- (_Bool)_showDistanceInMinorText;	// IMP=0x0010000000eaa949
- (_Bool)_forWalkingNavigation;	// IMP=0x0010000000eaa931
- (id)initWithRoute:(id)arg1 options:(long long)arg2;	// IMP=0x0010000000eaa8be
- (id)initWithRoute:(id)arg1;	// IMP=0x0010000000eaa8aa

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

