//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionViewCompositionalLayout.h>

@protocol GuideHomeDataProvider;

@interface GuideHomeCompositionalLayout : UICollectionViewCompositionalLayout
{
    id <GuideHomeDataProvider> _dataProvider;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000073ba87
@property(nonatomic) __weak id <GuideHomeDataProvider> dataProvider; // @synthesize dataProvider=_dataProvider;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;	// IMP=0x001000000073ba52
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x001000000073b627
- (id)initWithSectionProvider:(CDUnknownBlockType)arg1 dataProvider:(id)arg2;	// IMP=0x001000000073b515

@end

