//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CollectionHandler, CollectionImageView, NSString, UIButton, UITextField;
@protocol MacCollectionEditViewControllerDelegate;

@interface MacCollectionEditViewController
{
    UITextField *_textField;	// 8 = 0x8
    CollectionImageView *_imageView;	// 16 = 0x10
    UIButton *_changePhotoButton;	// 24 = 0x18
    UIButton *_deleteButton;	// 32 = 0x20
    CollectionHandler *_collection;	// 40 = 0x28
    id <MacCollectionEditViewControllerDelegate> _delegate;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000bd618d
@property(readonly, nonatomic) __weak id <MacCollectionEditViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) CollectionHandler *collection; // @synthesize collection=_collection;
- (_Bool)textFieldShouldReturn:(id)arg1;	// IMP=0x0010000000bd6124
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;	// IMP=0x0010000000bd5ffb
- (void)_delete;	// IMP=0x0010000000bd5fbf
- (void)_changePhoto;	// IMP=0x0010000000bd5f83
@property(readonly, nonatomic) NSString *newTitle;
- (id)_spacerImage;	// IMP=0x0010000000bd5ee9
- (id)_buttonWithTitle:(id)arg1 imageNamed:(id)arg2;	// IMP=0x0010000000bd5ab1
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0010000000bd5a68
- (void)viewDidLoad;	// IMP=0x0010000000bd5198
- (id)initWithCollection:(id)arg1 delegate:(id)arg2;	// IMP=0x0010000000bd50f2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

