//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UITableViewHeaderFooterView.h>

@class NSLayoutConstraint, UILabel;

@interface MapsGroupedTableHeaderView : UITableViewHeaderFooterView
{
    NSLayoutConstraint *_topToFirstBaselineConstraint;	// 8 = 0x8
    NSLayoutConstraint *_lastBaselineToBottomConstraint;	// 16 = 0x10
    UILabel *_titleLabel;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000cc4c9d
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)updateAXIdentifiersWithPrefix:(id)arg1;	// IMP=0x0010000000cc4baa
- (void)_contentSizeChanged:(id)arg1;	// IMP=0x0010000000cc4a95
- (void)setupConstraints;	// IMP=0x0010000000cc4630
- (id)initWithReuseIdentifier:(id)arg1;	// IMP=0x0010000000cc4299

@end

