//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MapsPieProgressView, NSProgress, _UICellAccessoryConfigurationCustomView;

@interface MapsDebugActionTableRow
{
    NSProgress *_internalProgress;	// 8 = 0x8
    MapsPieProgressView *_progressView;	// 16 = 0x10
    _UICellAccessoryConfigurationCustomView *_progressViewAccessory;	// 24 = 0x18
    _Bool _isDestructive;	// 32 = 0x20
    NSProgress *_observingProgress;	// 40 = 0x28
}

+ (id)reuseIdentifier;	// IMP=0x00400000008b1fc9
- (void).cxx_destruct;	// IMP=0x00200000008b2d24
@property(nonatomic) _Bool isDestructive; // @synthesize isDestructive=_isDestructive;
@property(retain, nonatomic) NSProgress *observingProgress; // @synthesize observingProgress=_observingProgress;
- (void)setSelectionAction:(CDUnknownBlockType)arg1;	// IMP=0x00100000008b2af7
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00100000008b29a8
- (id)_progressView;	// IMP=0x00100000008b286c
- (_Bool)_showingProgressView;	// IMP=0x00100000008b2782
- (void)_createProgressViewIfNeeded;	// IMP=0x00100000008b2708
- (void)_setProgressViewHidden:(_Bool)arg1;	// IMP=0x00100000008b245c
- (id)_findTableView;	// IMP=0x00100000008b23d4
- (void)configureCollectionViewCell:(id)arg1;	// IMP=0x00100000008b2157
- (void)configureCell:(id)arg1;	// IMP=0x00100000008b2013
- (void)dealloc;	// IMP=0x00100000008b1fd3

@end

