//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface MapsLegacyDataMigrator : NSObject
{
    NSObject<OS_dispatch_queue> *_migrationQueue;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000bcaa46
- (_Bool)_removeOrphanedRAPWebBundles;	// IMP=0x0010000000bca8a8
- (void)_migratePreCrystalFavorites;	// IMP=0x0010000000bca459
- (_Bool)_removeLegacyFiles;	// IMP=0x0010000000bc9eef
- (_Bool)_migrateOrphanedWatchResources;	// IMP=0x0010000000bc9719
- (_Bool)_migrateFiles;	// IMP=0x0010000000bc96dd
- (_Bool)_migrateDefaults;	// IMP=0x0010000000bc93d2
- (_Bool)_removeItemAtPathIfExists:(id)arg1;	// IMP=0x0010000000bc91f3
- (_Bool)_moveItemAtPathIfExists:(id)arg1 toPathCreatingIntermediateDirectories:(id)arg2;	// IMP=0x0010000000bc8e63
- (_Bool)_maps_isFileNotFoundError:(id)arg1;	// IMP=0x0010000000bc8d5f
- (_Bool)_migratePathsIntoContainer;	// IMP=0x0010000000bc89bf
- (void)performMigration;	// IMP=0x0010000000bc84ed
- (id)init;	// IMP=0x0010000000bc848a

@end

