//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, ScrollViewDelegateForwarder, SearchInfo, UIViewController;

@interface MapsAppTestPlacecard
{
    _Bool _thruSearchResultsList;	// 8 = 0x8
    _Bool _isScrollTest;	// 9 = 0x9
    _Bool _canResizePlacecard;	// 10 = 0xa
    unsigned long long _waitingTests;	// 16 = 0x10
    UIViewController *_placeViewController;	// 24 = 0x18
    ScrollViewDelegateForwarder *_scrollViewDelegate;	// 32 = 0x20
    unsigned long long _scrollTestState;	// 40 = 0x28
    SearchInfo *_searchInfo;	// 48 = 0x30
    id _notifcationToken;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000007eb90e
- (void)finishedSubTest:(id)arg1 checkAllFinished:(_Bool)arg2;	// IMP=0x00100000007eb8aa
- (void)startedSubTest:(id)arg1;	// IMP=0x00100000007eb870
- (void)_scrollTest:(id)arg1;	// IMP=0x00100000007eb4e4
- (void)_runScrollTest;	// IMP=0x00100000007eb3c5
- (void)_repositionTestDidFinish;	// IMP=0x00100000007eb380
- (void)_placeCardDidUpdatePosition:(id)arg1;	// IMP=0x00100000007eb2fe
- (void)_mediumizePlaceCardFromBig;	// IMP=0x00100000007eb1fe
- (void)_maxiumizePlaceCard;	// IMP=0x00100000007eafd4
- (void)_mediumizePlaceCard;	// IMP=0x00100000007eadaa
- (void)_minimizePlaceCard;	// IMP=0x00100000007ead51
- (void)_repositionTestWillStart;	// IMP=0x00100000007eab81
- (void)_performNextTestAfterShowingPlacecard;	// IMP=0x00100000007eab0c
- (void)_showPlaceCard:(id)arg1;	// IMP=0x00100000007eaa30
- (void)_showCallout:(id)arg1;	// IMP=0x00100000007ea9ad
- (void)_searchResultDidShow:(id)arg1;	// IMP=0x00100000007ea857
- (void)searchSessionDidFail:(id)arg1;	// IMP=0x00100000007ea851
- (void)searchSessionDidInvalidate:(id)arg1 reason:(unsigned long long)arg2;	// IMP=0x00100000007ea84b
- (void)searchSessionWillPerformSearch:(id)arg1;	// IMP=0x00100000007ea845
- (void)searchSessionDidChangeSearchFieldItem:(id)arg1;	// IMP=0x00100000007ea83f
- (void)searchSessionDidChangeSearchResults:(id)arg1;	// IMP=0x00100000007ea695
- (void)startPlacecardTest;	// IMP=0x00100000007ea476
- (void)cleanup:(_Bool)arg1;	// IMP=0x00100000007ea429
- (_Bool)runTest;	// IMP=0x00100000007ea120

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

