//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOComposedRoute, GEOMapFeatureAccess, NSArray, VKNavContext;

@interface NavCameraCaches : NSObject
{
    NSArray *_stepsWithRampCache;	// 8 = 0x8
    NSArray *_stepsWithCloseDistanceCache;	// 16 = 0x10
    NSArray *_stepsWithNearDistanceCache;	// 24 = 0x18
    NSArray *_stepsWithRoundaboutCache;	// 32 = 0x20
    NSArray *_groupedManeuverCounts;	// 40 = 0x28
    GEOComposedRoute *_currentRoute;	// 48 = 0x30
    GEOMapFeatureAccess *_mapFeatureAccess;	// 56 = 0x38
    VKNavContext *_navContex;	// 64 = 0x40
}

+ (id)cachesWithRoute:(id)arg1 context:(id)arg2;	// IMP=0x00400000007e2b05
- (void).cxx_destruct;	// IMP=0x00200000007e4322
// Error: Property attributes should begin with the type ('T') attribute, property name: navContex
// Property attributes: (null)

@property(retain, nonatomic) GEOMapFeatureAccess *mapFeatureAccess; // @synthesize mapFeatureAccess=_mapFeatureAccess;
@property(retain, nonatomic) GEOComposedRoute *currentRoute; // @synthesize currentRoute=_currentRoute;
@property(retain, nonatomic) NSArray *groupedManeuverCounts; // @synthesize groupedManeuverCounts=_groupedManeuverCounts;
@property(retain, nonatomic) NSArray *stepsWithRoundaboutCache; // @synthesize stepsWithRoundaboutCache=_stepsWithRoundaboutCache;
@property(retain, nonatomic) NSArray *stepsWithNearDistanceCache; // @synthesize stepsWithNearDistanceCache=_stepsWithNearDistanceCache;
@property(retain, nonatomic) NSArray *stepsWithCloseDistanceCache; // @synthesize stepsWithCloseDistanceCache=_stepsWithCloseDistanceCache;
@property(retain, nonatomic) NSArray *stepsWithRampCache; // @synthesize stepsWithRampCache=_stepsWithRampCache;
- (void)_roadForCoordinate:(CDStruct_c3b9c2ee)arg1 course:(double)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000007e3f6a
- (void)_calculateRoadTileGroupedManeuversWithUpdateHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000007e3956
- (void)_calculateRouteGroupedManeuvers;	// IMP=0x00100000007e325e
- (void)_updateGroupedManeuverCounts;	// IMP=0x00100000007e2d50
- (void)recalculateGroupedManeuversCaches;	// IMP=0x00100000007e2cc7
- (id)init;	// IMP=0x00100000007e2a6b

@end

