//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ChromeViewController, GEOComposedRoute, GEOComposedWaypoint, MKMapView, MNLocation, MapViewResponder, MapsSuggestionsRouteGeniusEntry, NSString, NavCameraController, NavCameraDriveProvider, NavigationDebugAnnotationsProvider, UserLocationView;
@protocol NavigationDisplayDelegate;

@interface NavigationDisplay : NSObject
{
    NavigationDebugAnnotationsProvider *_debugAnnotationsProvider;	// 8 = 0x8
    MapViewResponder *_mapViewResponder;	// 16 = 0x10
    MNLocation *_matchedLocation;	// 24 = 0x18
    unsigned long long _navigationCameraMode;	// 32 = 0x20
    _Bool _observingChrome;	// 40 = 0x28
    GEOComposedRoute *_route;	// 48 = 0x30
    NavCameraDriveProvider *_driveCameraProvider;	// 56 = 0x38
    struct {
        _Bool canSelectPOIs;
        _Bool compassEnabled;
        _Bool locationPropagationEnabled;
        _Bool panWithMomentum;
        _Bool rotateEnabled;
        _Bool scaleEnabled;
        _Bool shouldAnimatePositionWithRouteMatch;
        _Bool showsUserLocation;
        long long userTrackingMode;
        _Bool zoomEnabled;
    } _mapViewFlagsToRestore;	// 64 = 0x40
    _Bool _tracking;	// 88 = 0x58
    _Bool _showsRoadLabel;	// 89 = 0x59
    int _transportType;	// 92 = 0x5c
    id <NavigationDisplayDelegate> _delegate;	// 96 = 0x60
    MKMapView *_mapView;	// 104 = 0x68
    ChromeViewController *_chromeViewController;	// 112 = 0x70
    UserLocationView *_userLocationAnnotationView;	// 120 = 0x78
    long long _sky;	// 128 = 0x80
    NavCameraController *_cameraController;	// 136 = 0x88
    GEOComposedWaypoint *_destinationWaypoint;	// 144 = 0x90
    MapsSuggestionsRouteGeniusEntry *_routeGeniusEntry;	// 152 = 0x98
}

- (void).cxx_destruct;	// IMP=0x002000000059a1da
@property(nonatomic) _Bool showsRoadLabel; // @synthesize showsRoadLabel=_showsRoadLabel;
@property(readonly, nonatomic, getter=isTracking) _Bool tracking; // @synthesize tracking=_tracking;
@property(nonatomic) int transportType; // @synthesize transportType=_transportType;
@property(retain, nonatomic) MapsSuggestionsRouteGeniusEntry *routeGeniusEntry; // @synthesize routeGeniusEntry=_routeGeniusEntry;
@property(retain, nonatomic) GEOComposedWaypoint *destinationWaypoint; // @synthesize destinationWaypoint=_destinationWaypoint;
@property(readonly, nonatomic) NavCameraController *cameraController; // @synthesize cameraController=_cameraController;
@property(nonatomic) long long sky; // @synthesize sky=_sky;
@property(retain, nonatomic) UserLocationView *userLocationAnnotationView; // @synthesize userLocationAnnotationView=_userLocationAnnotationView;
@property(nonatomic) __weak ChromeViewController *chromeViewController; // @synthesize chromeViewController=_chromeViewController;
@property(retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
@property(nonatomic) __weak id <NavigationDisplayDelegate> delegate; // @synthesize delegate=_delegate;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;	// IMP=0x001000000059a095
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;	// IMP=0x0010000000599fe9
- (void)mapViewNavigationCameraDidReturnToDefaultZoom:(id)arg1;	// IMP=0x0010000000599f64
- (void)mapViewNavigationCameraDidLeaveDefaultZoom:(id)arg1;	// IMP=0x0010000000599edf
- (void)mapViewNavigationCameraHasStoppedPanning:(id)arg1;	// IMP=0x0010000000599e5a
- (void)mapViewNavigationCameraHasStartedPanning:(id)arg1;	// IMP=0x0010000000599dd5
- (void)mapView:(id)arg1 didDeselectLabelMarker:(id)arg2;	// IMP=0x0010000000599d2c
- (void)mapView:(id)arg1 didSelectLabelMarker:(id)arg2;	// IMP=0x0010000000599c83
- (_Bool)mapView:(id)arg1 shouldSelectLabelMarker:(id)arg2;	// IMP=0x0010000000599bd0
- (void)mapView:(id)arg1 didStopRespondingToGesture:(long long)arg2 zoomDirection:(long long)arg3 zoomGestureType:(long long)arg4 didDecelerate:(_Bool)arg5 tiltDirection:(long long)arg6;	// IMP=0x0010000000599990
- (id)mapViewCurrentRouteMatch:(id)arg1;	// IMP=0x0010000000599945
- (void)didTapMapView:(id)arg1 atPoint:(struct CGPoint)arg2;	// IMP=0x00100000005998d4
- (void)mapView:(id)arg1 didUpdateYaw:(double)arg2;	// IMP=0x0010000000599840
- (void)mapView:(id)arg1 didChangeUserTrackingMode:(long long)arg2 animated:(_Bool)arg3 fromTrackingButton:(_Bool)arg4;	// IMP=0x00100000005997b6
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;	// IMP=0x00100000005997a0
- (id)mapView:(id)arg1 rendererForOverlay:(id)arg2;	// IMP=0x001000000059978a
- (void)_shouldUseModernMapDidUpdate:(id)arg1;	// IMP=0x0010000000599778
- (void)_stopObservingChromeIfNeeded;	// IMP=0x00100000005996d3
- (void)_startObservingChromeIfNeeded;	// IMP=0x00100000005995e0
- (void)pauseCameraMotion;	// IMP=0x00100000005995ac
- (void)stopCameraMotion;	// IMP=0x0010000000599578
- (void)startMotion:(_Bool)arg1;	// IMP=0x0010000000599278
- (void)setNavigationDestinationState:(unsigned long long)arg1;	// IMP=0x001000000059924e
- (void)_updateDestinationBuildingId;	// IMP=0x00100000005990ea
- (void)_updateMapViewAndCameraController;	// IMP=0x0010000000598f07
- (void)setNavigationCameraMode:(unsigned long long)arg1;	// IMP=0x0010000000598ef1
- (void)_setTracking:(_Bool)arg1;	// IMP=0x0010000000598e09
- (void)_updateRoadDescription:(id)arg1;	// IMP=0x0010000000598d6f
- (void)clearCache;	// IMP=0x0010000000598ccb
- (void)_updateUserAnnotationViewForCurrentTransportTypeAnimated:(_Bool)arg1;	// IMP=0x0010000000598c98
- (void)setTransportType:(int)arg1 animated:(_Bool)arg2;	// IMP=0x0010000000598ae1
- (void)_updateCartographicConfiguration;	// IMP=0x001000000059897c
- (CDStruct_f97336e6)cartographicConfigurationForTransportType:(int)arg1;	// IMP=0x0010000000598807
- (void)clearAllAnnotations;	// IMP=0x00100000005987f1
- (void)updateWithRoute:(id)arg1;	// IMP=0x0010000000598735
- (void)updateWithLocation:(id)arg1;	// IMP=0x00100000005986a6
- (void)_updateSky;	// IMP=0x0010000000597ef5
- (void)dealloc;	// IMP=0x0010000000597eb7
- (id)init;	// IMP=0x0010000000597e50

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

