//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionViewCell.h>

@class UIActivityIndicatorView, UIView;

@interface NavManeuverReroutingCell : UICollectionViewCell
{
    UIView *_mapsBackgroundView;	// 8 = 0x8
    UIActivityIndicatorView *_spinnerView;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000e8c96e
- (void)setSelectedWithLayoutProgress:(double)arg1;	// IMP=0x0010000000e8c8e3
- (void)startAnimating;	// IMP=0x0010000000e8c89e
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000e8bc25

@end

