//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MapsSuggestionsEngine, NSString;
@protocol OS_dispatch_queue;

@interface OfflineMapsSuggestionsDataProvider : NSObject
{
    MapsSuggestionsEngine *_engine;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_msgEngineQueue;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_insightsQueue;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_callbackQueue;	// 32 = 0x20
    _Bool _tripTipDismissedThisSession;	// 40 = 0x28
    _Bool _homeAreaTipDismissedThisSession;	// 41 = 0x29
    int _clientType;	// 44 = 0x2c
}

- (void).cxx_destruct;	// IMP=0x0020000000aa5116
- (void)invalidateForMapsSuggestionsManager:(id)arg1;	// IMP=0x0010000000aa5110
@property(readonly, nonatomic) NSString *uniqueName;
- (void)_buildMapRegionForLatitude:(double)arg1 longitude:(double)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000aa4d99
- (_Bool)_tripTipWasDismissed;	// IMP=0x0010000000aa4876
- (_Bool)_homeAreaTipWasDismissed;	// IMP=0x0010000000aa44a4
- (void)_offlineSuggestionsUsingLocation:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000aa3b1f
- (id)_filterEntriesWithOverLappingRects:(id)arg1;	// IMP=0x0010000000aa36aa
- (void)_fetchHomeAreaModelDataFromEntry:(id)arg1 onQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000aa2949
- (void)_fetchAirportArrivalModelDataFromFlightEntry:(id)arg1 usingCurrentLocation:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000aa1f15
- (void)_firstUpcomingTripOfflineSuggestion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000aa1262
- (_Bool)isTrip:(id)arg1 nearAtLeastOneShortcut:(id)arg2;	// IMP=0x0010000000aa0fdd
- (id)fetchHomeLocationsAsShortCuts;	// IMP=0x0010000000aa0b5a
- (void)showHomeAreaTipInFuture;	// IMP=0x0010000000aa0a43
- (void)displayedTipWithType:(int)arg1;	// IMP=0x0010000000aa07e8
- (void)dismissedTipWithType:(int)arg1;	// IMP=0x0010000000aa05e8
- (void)offlineSuggestionsForLocation:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000a9fc47
- (void)offlineSuggestions:(CDUnknownBlockType)arg1;	// IMP=0x0000000000a9fc30
- (id)initWithClientType:(int)arg1 callbackQueue:(id)arg2;	// IMP=0x0010000000a9f9db

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

