//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class ACAccount, NSString, RAPCommentPartHeaderView, RAPDisplayUserContentTableViewCell, RAPLookAroundQuestion, RAPMultilineAddressLabelTableViewCell, RAPReport, RAPReportComposerCommentTableViewCell, TableViewSelectableFooterView, UIBarButtonItem, UITableView;

@interface RAPLookAroundDetailsEditorViewController : UIViewController
{
    RAPReport *_report;	// 8 = 0x8
    RAPLookAroundQuestion *_question;	// 16 = 0x10
    CDUnknownBlockType _completion;	// 24 = 0x18
    UIBarButtonItem *_sendButtonItem;	// 32 = 0x20
    RAPReportComposerCommentTableViewCell *_commentCell;	// 40 = 0x28
    RAPMultilineAddressLabelTableViewCell *_addressCell;	// 48 = 0x30
    RAPCommentPartHeaderView *_commentHeaderView;	// 56 = 0x38
    RAPDisplayUserContentTableViewCell *_userInfoCell;	// 64 = 0x40
    TableViewSelectableFooterView *_userContentFooterView;	// 72 = 0x48
    ACAccount *_account;	// 80 = 0x50
    UITableView *_tableView;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x002000000071d1f0
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)macFooterViewRightButtonTapped:(id)arg1;	// IMP=0x001000000071d1b9
@property(readonly, nonatomic) int analyticTarget;
- (void)_presentPrivacyView;	// IMP=0x001000000071d135
- (id)_userInfoCell;	// IMP=0x001000000071d08f
- (id)tableView:(id)arg1 resolveSimpleFeedbackCellForIndexPath:(id)arg2;	// IMP=0x001000000071cc29
- (id)tableView:(id)arg1 resolveHomeImageryCellWithNoAccountForIndexPath:(id)arg2;	// IMP=0x001000000071c969
- (id)tableView:(id)arg1 resolveHomeImageryCellForIndexPath:(id)arg2;	// IMP=0x001000000071c641
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x001000000071c59c
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;	// IMP=0x001000000071c52c
- (double)tableView:(id)arg1 heightforFooterInSection:(long long)arg2;	// IMP=0x001000000071c4e8
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;	// IMP=0x001000000071c426
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;	// IMP=0x001000000071c372
- (_Bool)_shouldShowPrivacyFooterForSection:(long long)arg1;	// IMP=0x001000000071c2c4
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;	// IMP=0x001000000071c240
- (id)commentHeaderView;	// IMP=0x001000000071c135
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;	// IMP=0x001000000071bf0b
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x001000000071bf00
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x001000000071be7c
- (void)userTappedOnAddressTableViewCell:(id)arg1;	// IMP=0x001000000071bbb6
- (void)addressTableViewCell:(id)arg1 updatedAddress:(id)arg2;	// IMP=0x001000000071bb1f
- (void)rapSearchAutocompleteViewController:(id)arg1 finishedPickingAutocompleteResult:(id)arg2 isAutocompleteResult:(_Bool)arg3;	// IMP=0x001000000071b901
- (void)valueForCorrectableItemKind:(long long)arg1 changedTo:(id)arg2;	// IMP=0x001000000071b890
- (void)_sendRAP;	// IMP=0x001000000071b6ee
- (id)_sendButtonItem;	// IMP=0x001000000071b54e
- (_Bool)_requiresPrivacyElements;	// IMP=0x001000000071b529
- (void)keyboardWillHide:(id)arg1;	// IMP=0x001000000071b477
- (void)keyboardWillShow:(id)arg1;	// IMP=0x001000000071b2a8
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x001000000071b25a
- (void)_setupTableView;	// IMP=0x001000000071afcc
- (void)viewDidLoad;	// IMP=0x001000000071a9d3
- (id)initWithReport:(id)arg1 question:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000071a850

// Remaining properties
@property(readonly, nonatomic) int backAction;
// Preceding property had unknown attributes: ?
// Original attribute string: Ti,?,R,N

@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSString *eventValue;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,N

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

