//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, RAPEditLocationViewController, RAPIncidentsQuestion, RAPReportComposerCommentPart, RAPReportComposerMapFeaturePickerPart;

@interface RAPReportComposerIncidentsEditorViewController
{
    RAPIncidentsQuestion *_question;	// 8 = 0x8
    RAPEditLocationViewController *_mapPicker;	// 16 = 0x10
    RAPReportComposerMapFeaturePickerPart *_labelMarkerPickerPart;	// 24 = 0x18
    RAPReportComposerCommentPart *_commentPart;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000009162f1
- (void)_presentMapPicker;	// IMP=0x0010000000915f77
- (void)inlineMapViewModelRequestsDisplayPowerActions:(id)arg1;	// IMP=0x0010000000915f65
- (id)tableParts;	// IMP=0x0010000000915d2f
@property(readonly, nonatomic) int analyticTarget;
- (id)initWithReport:(id)arg1 question:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000915c45

// Remaining properties
@property(readonly, nonatomic) int backAction;
// Preceding property had unknown attributes: ?
// Original attribute string: Ti,?,R,N

@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSString *eventValue;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,N

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

