//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UITableViewController.h>

@class NSDate, NSDateFormatter, NSString, NSTimeZone, ReservationAnalyticsCaptor, RestaurantReservationAnalyticsBookingSession;
@protocol ReservationRequestRefinementViewControllerDelegate;

@interface ReservationRequestRefinementViewController : UITableViewController
{
    id <ReservationRequestRefinementViewControllerDelegate> _refinementDelegate;	// 8 = 0x8
    NSDateFormatter *_dateFormatter;	// 16 = 0x10
    unsigned long long _defaultPartySize;	// 24 = 0x18
    NSDate *_defaultDate;	// 32 = 0x20
    unsigned long long _minimumPartySize;	// 40 = 0x28
    unsigned long long _maximumPartySize;	// 48 = 0x30
    unsigned long long _previousPartySize;	// 56 = 0x38
    ReservationAnalyticsCaptor *_analyticsCaptor;	// 64 = 0x40
    NSTimeZone *_timeZone;	// 72 = 0x48
    RestaurantReservationAnalyticsBookingSession *_analyticsBookingSession;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x0020000000a61b79
@property(retain, nonatomic) RestaurantReservationAnalyticsBookingSession *analyticsBookingSession; // @synthesize analyticsBookingSession=_analyticsBookingSession;
@property(retain, nonatomic) NSTimeZone *timeZone; // @synthesize timeZone=_timeZone;
@property(retain, nonatomic) ReservationAnalyticsCaptor *analyticsCaptor; // @synthesize analyticsCaptor=_analyticsCaptor;
@property(nonatomic) unsigned long long previousPartySize; // @synthesize previousPartySize=_previousPartySize;
@property(nonatomic) unsigned long long maximumPartySize; // @synthesize maximumPartySize=_maximumPartySize;
@property(nonatomic) unsigned long long minimumPartySize; // @synthesize minimumPartySize=_minimumPartySize;
@property(retain, nonatomic) NSDate *defaultDate; // @synthesize defaultDate=_defaultDate;
@property(nonatomic) unsigned long long defaultPartySize; // @synthesize defaultPartySize=_defaultPartySize;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(nonatomic) __weak id <ReservationRequestRefinementViewControllerDelegate> refinementDelegate; // @synthesize refinementDelegate=_refinementDelegate;
@property(readonly, nonatomic) NSDate *date;
@property(readonly, nonatomic) unsigned long long partySize;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;	// IMP=0x0010000000a617f8
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x0010000000a61728
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000a61334
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0010000000a61329
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0010000000a6131e
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000a612ac
- (void)datePickerChanged;	// IMP=0x0010000000a6122e
- (void)stepperChanged:(id)arg1;	// IMP=0x0010000000a610fd
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0010000000a60f98
- (void)configureNavBar;	// IMP=0x0010000000a60f12
- (void)configureTableView;	// IMP=0x0010000000a60d39
- (void)viewDidLoad;	// IMP=0x0010000000a60ce3
- (id)initWithDate:(id)arg1 partySize:(unsigned long long)arg2 minimumPartySize:(unsigned long long)arg3 maximumPartySize:(unsigned long long)arg4 analyticsCaptor:(id)arg5 timeZone:(id)arg6 analyticsBookingSession:(id)arg7;	// IMP=0x0010000000a60b98

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

