//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSLayoutConstraint, NSString, UILabel;

@interface RidesharingAppSelectionSectionHeaderView
{
    UILabel *_majorLabel;	// 8 = 0x8
    NSLayoutConstraint *_heightConstraint;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000073c139
@property(retain, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
@property(retain, nonatomic) UILabel *majorLabel; // @synthesize majorLabel=_majorLabel;
@property(copy, nonatomic) NSString *majorString;
- (void)_updateContentSizeCategoryDependentFontsAndConstraints;	// IMP=0x001000000073bff4
- (void)_setupConstraints;	// IMP=0x001000000073bccf
- (void)_setupViews;	// IMP=0x001000000073bbdc
- (void)dealloc;	// IMP=0x001000000073bb67
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000073ba98

@end

