//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ContainerHeaderView, NSString, UIViewController;
@protocol RoutePlanningDataCoordination;

@interface RoutePlanningWrapperViewController
{
    id <RoutePlanningDataCoordination> _dataCoordinator;	// 8 = 0x8
    ContainerHeaderView *_titleHeaderView;	// 16 = 0x10
    UIViewController *_wrappedViewController;	// 24 = 0x18
}

+ (_Bool)wantsDefaultHeaderContentViews;	// IMP=0x00200000008731cd
- (void).cxx_destruct;	// IMP=0x0020000000873fbf
@property(retain, nonatomic) UIViewController *wrappedViewController; // @synthesize wrappedViewController=_wrappedViewController;
@property(retain, nonatomic) ContainerHeaderView *titleHeaderView; // @synthesize titleHeaderView=_titleHeaderView;
@property(readonly, nonatomic) __weak id <RoutePlanningDataCoordination> dataCoordinator; // @synthesize dataCoordinator=_dataCoordinator;
- (void)headerViewTapped:(id)arg1;	// IMP=0x0010000000873f1f
- (void)headerViewButtonTapped:(id)arg1 buttonType:(unsigned long long)arg2;	// IMP=0x0010000000873ed0
- (void)_setupChildViewControllerIfNeeded:(id)arg1;	// IMP=0x0010000000873a42
- (void)updateHeaderTitle;	// IMP=0x0010000000873959
- (void)viewDidLoad;	// IMP=0x00100000008731d5
- (id)initWithDataCoordination:(id)arg1;	// IMP=0x00100000008730e1

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

