//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSSet, NSString, WaypointSet;
@protocol RouteLoadingControllerDelegate, RouteLoadingTaskFactory, RouteUpdatingTask;

@interface RouteLoadingController : NSObject
{
    id <RouteLoadingControllerDelegate> _delegate;	// 8 = 0x8
    id <RouteLoadingTaskFactory> _routeLoadingTaskFactory;	// 16 = 0x10
    WaypointSet *_waypointSet;	// 24 = 0x18
    long long _transportTypeForRealtimeUpdates;	// 32 = 0x20
    NSMutableDictionary *_activeTasks;	// 40 = 0x28
    NSMutableDictionary *_mutableRoutesResults;	// 48 = 0x30
    id <RouteUpdatingTask> _routeUpdatingTask;	// 56 = 0x38
    NSString *_activeTasksSync;	// 64 = 0x40
    NSString *_routesResultsSync;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0020000000780504
@property(readonly, copy, nonatomic) NSString *routesResultsSync; // @synthesize routesResultsSync=_routesResultsSync;
@property(readonly, copy, nonatomic) NSString *activeTasksSync; // @synthesize activeTasksSync=_activeTasksSync;
@property(retain, nonatomic) id <RouteUpdatingTask> routeUpdatingTask; // @synthesize routeUpdatingTask=_routeUpdatingTask;
@property(retain, nonatomic) NSMutableDictionary *mutableRoutesResults; // @synthesize mutableRoutesResults=_mutableRoutesResults;
@property(retain, nonatomic) NSMutableDictionary *activeTasks; // @synthesize activeTasks=_activeTasks;
@property(nonatomic) long long transportTypeForRealtimeUpdates; // @synthesize transportTypeForRealtimeUpdates=_transportTypeForRealtimeUpdates;
@property(retain, nonatomic) WaypointSet *waypointSet; // @synthesize waypointSet=_waypointSet;
@property(readonly, nonatomic) id <RouteLoadingTaskFactory> routeLoadingTaskFactory; // @synthesize routeLoadingTaskFactory=_routeLoadingTaskFactory;
@property(nonatomic) __weak id <RouteLoadingControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_handleResults:(id)arg1;	// IMP=0x001000000077fd6b
- (void)_updateTaskForRealtimeUpdates;	// IMP=0x001000000077fa4a
- (id)_routeLoadingTaskForTransportType:(long long)arg1;	// IMP=0x001000000077f879
- (void)refreshRoutesForTransportType:(long long)arg1;	// IMP=0x001000000077ef5c
- (id)routesForTransportType:(long long)arg1;	// IMP=0x001000000077ee82
@property(readonly, nonatomic) NSDictionary *routesResults;
- (_Bool)isActiveForTransportType:(long long)arg1;	// IMP=0x001000000077ed47
@property(readonly, nonatomic) _Bool isActive;
- (void)cancelLoadingForTransportType:(long long)arg1;	// IMP=0x001000000077eb56
- (void)cancelLoading;	// IMP=0x001000000077ea75
@property(readonly, nonatomic) NSSet *supportedTransportTypes;
- (id)initWithWaypointSet:(id)arg1 taskFactory:(id)arg2;	// IMP=0x001000000077e858

@end

