//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class HistoryEntryRecentsItem, NSString, RoutePlanningSession;

@interface RoutePlanningSessionRouteLoadedNotifier : NSObject
{
    HistoryEntryRecentsItem *_currentRouteHistoryEntry;	// 8 = 0x8
    RoutePlanningSession *_observedRoutePlanningSession;	// 16 = 0x10
    CDUnknownBlockType _handler;	// 24 = 0x18
}

+ (id)_createAndSaveHistoryEntryFromSession:(id)arg1 selectedRoute:(id)arg2;	// IMP=0x0020000000a3fb0d
+ (long long)creationPreference;	// IMP=0x0010000000a3f271
- (void).cxx_destruct;	// IMP=0x0020000000a40939
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(retain, nonatomic) RoutePlanningSession *observedRoutePlanningSession; // @synthesize observedRoutePlanningSession=_observedRoutePlanningSession;
@property(readonly, nonatomic) HistoryEntryRecentsItem *currentRouteHistoryEntry; // @synthesize currentRouteHistoryEntry=_currentRouteHistoryEntry;
- (void)_createAndSaveHistoryEntryFromOutgoingSession:(id)arg1;	// IMP=0x0010000000a4073f
- (void)_createAndSaveHistoryEntryFromUpdatedSession:(id)arg1;	// IMP=0x0010000000a40574
- (void)_updateCurrentRouteHistoryEntryFromSession:(id)arg1;	// IMP=0x0010000000a404f8
- (void)routePlanningSession:(id)arg1 didReceiveUpdates:(id)arg2 forRoutesResult:(id)arg3;	// IMP=0x0010000000a3fb07
- (void)routePlanningSession:(id)arg1 didUpdateRouteCollectionResult:(id)arg2 forTransportType:(long long)arg3;	// IMP=0x0010000000a3f820
- (void)routePlanningSession:(id)arg1 didChangeCurrentTransportType:(long long)arg2 userInitiated:(_Bool)arg3;	// IMP=0x0010000000a3f731
- (void)routePlanningSession:(id)arg1 didFinishResolvingWaypointSet:(id)arg2;	// IMP=0x0010000000a3f72b
- (void)mapsSession:(id)arg1 didChangeState:(unsigned long long)arg2;	// IMP=0x0010000000a3f725
- (void)setCurrentRouteHistoryEntry:(id)arg1;	// IMP=0x0010000000a3f4b0
- (void)platformController:(id)arg1 didChangeCurrentSessionFromSession:(id)arg2 toSession:(id)arg3;	// IMP=0x0010000000a3f282
- (void)platformController:(id)arg1 willChangeCurrentSessionFromSession:(id)arg2 toSession:(id)arg3;	// IMP=0x0010000000a3f27c
- (id)initWithPlatformController:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000a3eefd

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

