//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface SearchHomePublishersLayoutProvider : NSObject
{
}

- (id)layoutSectionWithLayoutEnvironment:(id)arg1 estimatedHeaderHeight:(double)arg2 estimatedFooterHeight:(double)arg3 deletionBlock:(CDUnknownBlockType)arg4 objectsCount:(unsigned long long)arg5 mapsTheme:(id)arg6;	// IMP=0x00200000002a6d8a
- (id)cellReuseIdentifier;	// IMP=0x00100000002a6d71
- (id)cellForRowAtIndexPath:(id)arg1 collectionView:(id)arg2 item:(id)arg3;	// IMP=0x00100000002a6c71
- (long long)type;	// IMP=0x00100000002a6c66
- (id)cellClasses;	// IMP=0x00100000002a6bfa

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

