//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ContainerHeaderView, NSArray, NSMutableArray, NSString, UITableView;
@protocol SharedTripAutosharingContaineeViewControllerDelegate;

@interface SharedTripAutosharingContaineeViewController
{
    ContainerHeaderView *_headerView;	// 8 = 0x8
    UITableView *_tableView;	// 16 = 0x10
    NSMutableArray *_contacts;	// 24 = 0x18
    id <SharedTripAutosharingContaineeViewControllerDelegate> _delegate;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000b5ae26
@property(nonatomic) __weak id <SharedTripAutosharingContaineeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_deleteContact:(id)arg1;	// IMP=0x0010000000b5acf7
- (void)_addContact:(id)arg1;	// IMP=0x0010000000b5ac09
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0010000000b5aa41
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;	// IMP=0x0010000000b5a9f7
- (void)_updateImage:(id)arg1 forContact:(id)arg2;	// IMP=0x0010000000b5a8f5
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000b59f76
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0010000000b59f55
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0010000000b59f4a
- (void)headerViewButtonTapped:(id)arg1 buttonType:(unsigned long long)arg2;	// IMP=0x0010000000b59ed9
- (id)contentView;	// IMP=0x0010000000b59ec4
- (id)headerView;	// IMP=0x0010000000b59eaf
- (void)viewDidLoad;	// IMP=0x0010000000b59687
@property(copy, nonatomic) NSArray *contacts;
- (id)initWithContacts:(id)arg1;	// IMP=0x0010000000b59596

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

