//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOObserverHashTable, NSArray, NSMutableArray, NSString;

@interface SharedCollectionsDataProvider : NSObject
{
    NSMutableArray *_mutableCollections;	// 8 = 0x8
    GEOObserverHashTable *_observers;	// 16 = 0x10
    _Bool _active;	// 24 = 0x18
    NSArray *_sharedCollections;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000b38d07
@property(readonly, nonatomic) NSArray *sharedCollections; // @synthesize sharedCollections=_sharedCollections;
@property(nonatomic) _Bool active; // @synthesize active=_active;
- (void)collectionHandlerContentUpdated:(id)arg1;	// IMP=0x0010000000b38cdd
- (void)collectionHandlerInfoUpdated:(id)arg1;	// IMP=0x0010000000b38cc6
- (void)removeSharedCollection:(id)arg1;	// IMP=0x0010000000b38c48
- (void)addSharedCollection:(id)arg1;	// IMP=0x0010000000b38bca
- (void)_updateAndNotifyObservers:(_Bool)arg1;	// IMP=0x0010000000b38957
@property(readonly, nonatomic) GEOObserverHashTable *observers;
@property(readonly, nonatomic) _Bool hasInitialData;
- (id)init;	// IMP=0x0010000000b3885d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

