//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol UIPopoverPresentationControllerSourceItem;

@protocol ToolbarControllerActionHandling

@optional
- (void)tapUserProfileButton:(id)arg1;
- (void)tapNewTabButton:(id)arg1;
- (void)tapShareButton:(id)arg1;
- (void)tapDirectionButton:(id)arg1;
- (void)selectLookAroundMode;
- (void)didSelectMapModeToolbarItem:(id <UIPopoverPresentationControllerSourceItem>)arg1;
- (void)select3dMode;
- (void)tapLocateMe:(id)arg1;
- (void)tapToggleSidebar:(id)arg1;
@end

