//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol TransitSchedulesHeadsignPickerCollectionViewCellDelegate;

@interface TransitSchedulesHeadsignPickerProvider : NSObject
{
    id <TransitSchedulesHeadsignPickerCollectionViewCellDelegate> _delegate;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000e571f5
@property(nonatomic) __weak id <TransitSchedulesHeadsignPickerCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (id)identifiersForDepartureSequences:(id)arg1;	// IMP=0x0010000000e57120
- (id)collectionView:(id)arg1 headsignCellWithIdentifier:(id)arg2 indexPath:(id)arg3 dataProvider:(id)arg4;	// IMP=0x0010000000e56fdc
- (void)collectionView:(id)arg1 selectedHeadsignForDepartureSequence:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0010000000e56efc
- (void)registerCellsForCollectionView:(id)arg1;	// IMP=0x0010000000e56e81

@end

