//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class BNBannerSource, BannerItem, EmptyApertureView, NSLayoutConstraint, NSString, TransitApertureElementWrapperView, UIImageView, UILabel, UIView;
@protocol SBUISystemApertureAccessoryView;

@interface TransitDestinationBannerView
{
    TransitApertureElementWrapperView *_leadingView;	// 8 = 0x8
    UIImageView *_leadingImageView;	// 16 = 0x10
    TransitApertureElementWrapperView *_minimalView;	// 24 = 0x18
    UIImageView *_minimalImageView;	// 32 = 0x20
    TransitApertureElementWrapperView *_detachedMinimalView;	// 40 = 0x28
    UIImageView *_detachedMinimalImageView;	// 48 = 0x30
    EmptyApertureView *_trailingView;	// 56 = 0x38
    NSLayoutConstraint *_topConstraint;	// 64 = 0x40
    double _cachedHeight;	// 72 = 0x48
    double _calculatedWidth;	// 80 = 0x50
    _Bool _showsControls;	// 88 = 0x58
    _Bool _expanded;	// 89 = 0x59
    UILabel *_primaryLabel;	// 96 = 0x60
    UIImageView *_primaryImageView;	// 104 = 0x68
    UIView *_controlsView;	// 112 = 0x70
}

- (void).cxx_destruct;	// IMP=0x0020000000e27ed1
@property(retain, nonatomic) UIView *controlsView; // @synthesize controlsView=_controlsView;
@property(retain, nonatomic) UIImageView *primaryImageView; // @synthesize primaryImageView=_primaryImageView;
@property(retain, nonatomic) UILabel *primaryLabel; // @synthesize primaryLabel=_primaryLabel;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
// Preceding property had unknown attributes: ?
// Original attribute string: TB,?,N,V_expanded

@property(nonatomic) _Bool showsControls; // @synthesize showsControls=_showsControls;
// Preceding property had unknown attributes: ?
// Original attribute string: TB,?,N,V_showsControls

- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0010000000e27bc9
@property(readonly, nonatomic) UIView<SBUISystemApertureAccessoryView> *detachedMinimalView;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIView<SBUISystemApertureAccessoryView>",?,R,N

@property(readonly, nonatomic) UIView<SBUISystemApertureAccessoryView> *minimalView;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIView<SBUISystemApertureAccessoryView>",?,R,N

@property(readonly, nonatomic) UIView<SBUISystemApertureAccessoryView> *trailingView;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIView<SBUISystemApertureAccessoryView>",?,R,N

@property(readonly, nonatomic) UIView<SBUISystemApertureAccessoryView> *leadingView;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIView<SBUISystemApertureAccessoryView>",?,R,N

@property(readonly, nonatomic) unsigned long long bannerType;
- (void)updateFromBannerItem;	// IMP=0x0010000000e2783e
- (id)initWithTarget:(id)arg1 item:(id)arg2 aperturePresentation:(_Bool)arg3;	// IMP=0x0010000000e26719

// Remaining properties
@property(readonly, nonatomic) _Bool aperturePresentation;
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) BannerItem *item;
@property(readonly) Class superclass;
@property(readonly, nonatomic) __weak BNBannerSource *target;

@end

