//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface TransitPayFeatureDiscoveryMetadataStore : NSObject
{
    NSMutableDictionary *_defaultsDictionary;	// 8 = 0x8
    NSMutableDictionary *_tipInfoDictionary;	// 16 = 0x10
    _Bool _isTourist;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000009feee8
- (void)_persistData;	// IMP=0x00100000009fee37
- (_Bool)_userHasBecomeLocalAndTipShouldDisplayInMarket:(unsigned long long)arg1 tipType:(int)arg2 currentTip:(id)arg3;	// IMP=0x00100000009fea7b
- (id)_tipInfoForMarket:(unsigned long long)arg1 tipType:(int)arg2;	// IMP=0x00100000009fe822
- (void)handleTipDisplayForMarket:(unsigned long long)arg1 tipType:(int)arg2 sinkType:(int)arg3;	// IMP=0x00100000009fe2f9
- (void)handleManualTipDismissForMarket:(unsigned long long)arg1 tipType:(int)arg2 sinkType:(int)arg3;	// IMP=0x00100000009fe04b
- (_Bool)shouldDisplayTipInMarket:(unsigned long long)arg1 tipType:(int)arg2 sinkType:(int)arg3;	// IMP=0x00100000009fda33
- (id)initWithTouristStatus:(_Bool)arg1;	// IMP=0x00100000009fd8ed

@end

