//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class DirectionItem, MapCameraController, NSArray, NSDictionary, NSURL, TransitSchedulesViewController, UIView;
@protocol GEOTransitLineItem;

@protocol TransitSchedulesViewControllerDelegate <NSObject>
- (void)transitSchedulesViewController:(TransitSchedulesViewController *)arg1 wantsToOpenURL:(NSURL *)arg2;
- (void)transitSchedulesViewController:(TransitSchedulesViewController *)arg1 wantsToDoDirectionItem:(DirectionItem *)arg2 withUserInfo:(NSDictionary *)arg3;
- (void)transitSchedulesViewController:(TransitSchedulesViewController *)arg1 wantsToDisplayIncidents:(NSArray *)arg2 fromView:(UIView *)arg3;
- (void)transitSchedulesViewController:(TransitSchedulesViewController *)arg1 wantsToShowInfoForLine:(id <GEOTransitLineItem>)arg2;
- (void)transitSchedulesViewControllerWantsToUpdateRouteAnnotations:(TransitSchedulesViewController *)arg1;
- (MapCameraController *)mapCameraControllerForTransitSchedulesViewController:(TransitSchedulesViewController *)arg1;
@end

