//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GEOComposedString, GEOPBTransitArtwork, NSString;

@interface TransitAlightMessage
{
    NSString *_identifier;	// 8 = 0x8
    unsigned long long _stopIndex;	// 16 = 0x10
    unsigned long long _stepIndex;	// 24 = 0x18
    GEOPBTransitArtwork *_artwork;	// 32 = 0x20
    GEOComposedString *_title;	// 40 = 0x28
    GEOComposedString *_detail;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000e0365a
@property(retain, nonatomic) GEOComposedString *detail; // @synthesize detail=_detail;
@property(retain, nonatomic) GEOComposedString *title; // @synthesize title=_title;
@property(copy, nonatomic) GEOPBTransitArtwork *artwork; // @synthesize artwork=_artwork;
@property(nonatomic) unsigned long long stepIndex; // @synthesize stepIndex=_stepIndex;
@property(nonatomic) unsigned long long stopIndex; // @synthesize stopIndex=_stopIndex;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)description;	// IMP=0x0010000000e03500
- (id)dictionaryValue;	// IMP=0x0010000000e03247
- (id)initWithDictionary:(id)arg1;	// IMP=0x0010000000e02fdd

@end

