//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSURL, PHAsset, PHCachingImageManager, UGCPhotoWithMetadata;

@interface UGCARPPhotoCarouselViewModel : NSObject
{
    PHCachingImageManager *_imageManager;	// 8 = 0x8
    _Bool _checked;	// 16 = 0x10
    _Bool _isSuggestedPhoto;	// 17 = 0x11
    _Bool _enabled;	// 18 = 0x12
    _Bool _isLoading;	// 19 = 0x13
    UGCPhotoWithMetadata *_photoWithMetadata;	// 24 = 0x18
    PHAsset *_asset;	// 32 = 0x20
    NSString *_identifier;	// 40 = 0x28
    NSURL *_imageURL;	// 48 = 0x30
}

+ (double)preferredCellHeight;	// IMP=0x002000000025d1a6
- (void).cxx_destruct;	// IMP=0x002000000025e05e
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool isSuggestedPhoto; // @synthesize isSuggestedPhoto=_isSuggestedPhoto;
@property(nonatomic) _Bool checked; // @synthesize checked=_checked;
@property(copy, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) PHAsset *asset; // @synthesize asset=_asset;
@property(retain, nonatomic) UGCPhotoWithMetadata *photoWithMetadata; // @synthesize photoWithMetadata=_photoWithMetadata;
- (void)_prepareImageThumbnailWithOriginalImage:(id)arg1 targetSize:(struct CGSize)arg2 scale:(double)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000025deb4
- (int)_loadPhotoFromAsset:(id)arg1 shouldDegrade:(_Bool)arg2 scale:(double)arg3 progressHandler:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000025da39
- (void)loadThumbnailImageWithDisplayScale:(double)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000025d79c
- (void)cancelLoadImageWithRequestID:(int)arg1;	// IMP=0x001000000025d786
- (void)loadOriginalImageWithDisplayScale:(double)arg1 progressHandler:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000025d3d3
@property(readonly, nonatomic) struct CGSize imageSizeForCell;
@property(readonly, nonatomic) double timeoutInterval;
@property(readonly, nonatomic) NSURL *url;
@property(readonly, nonatomic) NSString *downloadIdentifier;
@property(readonly, nonatomic) NSString *_maps_diffableDataSourceIdentifier;
- (id)initWithImageManager:(id)arg1;	// IMP=0x001000000025d09b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

