//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol GEOVenueIdentifier, GEOVenueLabel;

@interface VenueAllBuildings : NSObject
{
    _Bool _describesParentVenue;	// 8 = 0x8
    id <GEOVenueIdentifier> _filterID;	// 16 = 0x10
    id <GEOVenueLabel> _label;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000c834b9
@property(readonly, nonatomic) _Bool describesParentVenue; // @synthesize describesParentVenue=_describesParentVenue;
@property(readonly, nonatomic) id <GEOVenueLabel> label; // @synthesize label=_label;
@property(readonly, nonatomic) id <GEOVenueIdentifier> filterID; // @synthesize filterID=_filterID;
- (id)initWithVenueIdentifier:(id)arg1;	// IMP=0x0010000000c83412
- (id)init;	// IMP=0x0010000000c83404

@end

