//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableArray, NSString;

@interface ViewportFrameBookmarksController
{
    NSMutableArray *_items;	// 8 = 0x8
    NSString *_filePath;	// 16 = 0x10
}

+ (id)navigationDestinationTitle;	// IMP=0x00400000002da66f
- (void).cxx_destruct;	// IMP=0x00200000002dbd31
- (void)saveFileAndReload;	// IMP=0x00100000002dbc1e
- (void)prepareContent;	// IMP=0x00100000002da67c

@end

