//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MediaRemote/MRAVEndpoint.h>

@class MRDSystemEndpointControllerHelperEndpointInfo;

@interface MRAVEndpoint (MRDHostedRoutingControllerAdditions)
@property(readonly, nonatomic) _Bool hasASmartDevice;
@property(readonly, nonatomic) MRDSystemEndpointControllerHelperEndpointInfo *endpointInfo;
@property(readonly, nonatomic, getter=isRemoteEndpoint) _Bool remoteEndpoint;
@property(readonly, nonatomic) _Bool shouldDonate;
@end

