//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MRDExternalDeviceHomeServerRecentlyPlayedEntry, NSMutableArray, NSString, NSUserDefaults;

@interface MRDExternalDeviceHomeServer : NSObject
{
    _Bool _sendingPlaybackStateToCompanion;	// 8 = 0x8
    MRDExternalDeviceHomeServerRecentlyPlayedEntry *_lastSentEntry;	// 16 = 0x10
    NSMutableArray *_entries;	// 24 = 0x18
    NSUserDefaults *_userDefaults;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000000819fb
@property(nonatomic) _Bool sendingPlaybackStateToCompanion; // @synthesize sendingPlaybackStateToCompanion=_sendingPlaybackStateToCompanion;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(retain, nonatomic) NSMutableArray *entries; // @synthesize entries=_entries;
@property(retain, nonatomic) MRDExternalDeviceHomeServerRecentlyPlayedEntry *lastSentEntry; // @synthesize lastSentEntry=_lastSentEntry;
- (id)decodeEntries;	// IMP=0x0010000000081729
- (id)encodeEntries;	// IMP=0x001000000008152a
- (void)_addEntry:(id)arg1;	// IMP=0x00100000000810c4
- (_Bool)_shouldSendCompanionLinkMessage;	// IMP=0x00100000000810bc
- (void)_maybeSendPlaybackStateMessageToCompanion;	// IMP=0x00100000000808d6
- (void)_handleSetNearbyDevicesToRemoteControlMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000807b7
- (void)_maybeMostRecentlyPlayedDeviceChanged:(id)arg1;	// IMP=0x0010000000080620
- (void)_handleLocalPlaybackBeganNotification:(id)arg1;	// IMP=0x0010000000080419
- (void)_registerNotifications;	// IMP=0x0010000000080252
- (void)_registerCompanionLinkHandlers;	// IMP=0x001000000007f84b
- (void)handleXPCMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x001000000007f7d0
@property(readonly, nonatomic) NSString *mostRecentDeviceUID;
- (id)init;	// IMP=0x001000000007f65e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

