//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MRDMediaControlIPCServer : NSObject
{
}

- (id)init;	// IMP=0x004000000029c0e0
- (void)collectDiagnostic:(id)arg1;	// IMP=0x001000000029c030
- (void)start;	// IMP=0x001000000029bf40

@end

