//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class NRTermsEvent, UIToolbar, UIWebView;
@protocol BuddyTCSubControllerDelegate;

@interface BuddySimpleTCController : UIViewController
{
    UIToolbar *_toolbar;	// 8 = 0x8
    UIWebView *_webView;	// 16 = 0x10
    id <BuddyTCSubControllerDelegate> _delegate;	// 24 = 0x18
    NRTermsEvent *_content;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000125070
@property(retain, nonatomic) NRTermsEvent *content; // @synthesize content=_content;
@property(nonatomic) __weak id <BuddyTCSubControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)disagree:(id)arg1;	// IMP=0x0010000000124fe0
- (void)agree:(id)arg1;	// IMP=0x0010000000124f9f
- (void)updateLayout;	// IMP=0x0010000000124dab
- (void)viewDidLoad;	// IMP=0x0010000000124ce4
- (void)loadView;	// IMP=0x001000000012452b
- (id)initWithTitle:(id)arg1 content:(id)arg2;	// IMP=0x0010000000124459

@end

