//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class COSFeatureHighlightDataSource, NSMutableArray;

@interface COSFeatureHighlightView : UIView
{
    _Bool _flattenImages;	// 8 = 0x8
    COSFeatureHighlightDataSource *_dataSource;	// 16 = 0x10
    NSMutableArray *_features;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000003bb13
@property(retain, nonatomic) NSMutableArray *features; // @synthesize features=_features;
@property(nonatomic) __weak COSFeatureHighlightDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) _Bool flattenImages; // @synthesize flattenImages=_flattenImages;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x001000000003ba8d
- (struct CGSize)_sizeThatFits:(struct CGSize)arg1 doLayout:(_Bool)arg2;	// IMP=0x001000000003b820
- (void)layoutSubviews;	// IMP=0x001000000003b7c6
- (void)showFeaturesForDataSource:(id)arg1;	// IMP=0x001000000003b282
- (double)rowHeight;	// IMP=0x001000000003b274
- (id)localizedStringForString:(id)arg1;	// IMP=0x001000000003b26c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000003b1ec

@end

