//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Preferences/PSTableCell.h>

@class UIView;

@interface COSSOSTriggerAnimationCell : PSTableCell
{
    UIView *_triggerImageView;	// 120 = 0x78
}

+ (double)preferredCellHeight;	// IMP=0x002000000000517c
- (void).cxx_destruct;	// IMP=0x00200000000057e5
@property(retain, nonatomic) UIView *triggerImageView; // @synthesize triggerImageView=_triggerImageView;
- (void)setupConstraints;	// IMP=0x001000000000544c
- (void)loadTriggerImageView;	// IMP=0x00100000000052c1
- (_Bool)isLayoutLeftToRight;	// IMP=0x0010000000005272
- (_Bool)isCrownOrientationOnRightSide;	// IMP=0x001000000000518a
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;	// IMP=0x0010000000005130

@end

