//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface COSTinkerLocationOptinViewController
{
}

+ (_Bool)controllerNeedsToRun;	// IMP=0x00400000000de969
- (id)privacyBundles;	// IMP=0x00400000000dee01
- (id)alternateButtonTitle;	// IMP=0x00100000000ded95
- (id)suggestedButtonTitle;	// IMP=0x00100000000ded29
- (void)applyConfirmedOptin:(_Bool)arg1;	// IMP=0x00100000000dec24
- (void)alternateButtonPressed:(id)arg1;	// IMP=0x00100000000dec10
- (void)suggestedButtonPressed:(id)arg1;	// IMP=0x00100000000debf9
- (id)imageResource;	// IMP=0x00100000000deba8
- (id)detailString;	// IMP=0x00000000000deab9
- (id)titleString;	// IMP=0x00100000000de9ca
- (_Bool)wantsLightenBlendedScreen;	// IMP=0x00100000000de9c2
- (id)init;	// IMP=0x00100000000de971

@end

