//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ToneKit/TKTonePickerViewController.h>

@interface TKTonePickerViewController (CompanionSetup)
- (id)initWithAlertType:(long long)arg1 tableViewStyle:(long long)arg2;	// IMP=0x00100000000f61bd
@end

