//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC11SettingsApp21SettingsAppLSObserver : NSObject
{
    MISSING_TYPE *callback;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0040000000049250
- (id)init;	// IMP=0x00100000000491d0
- (void)observerDidObserveDatabaseChange:(id)arg1;	// IMP=0x0010000000049140

@end

