//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AXAssetController, AXCharacterSoundMap, AXMDisplayManager, AXSSPunctuationGroup, AXUISoftwareKeyboardManager, AXVoiceOverActivity, BRLTTable, NSArray, NSLock, NSMutableArray, NSMutableDictionary, NSNumber, NSString, TUCallCenter, UITextChecker, VOSCommandManager, VOTElement, VOTEventFactory, VOTKeyboardManager, VOTOutputRequest, VOTVisionEngine, _TtC3vot11VOTSettings;
@protocol OS_dispatch_queue, OS_os_transaction, VOTDirectTouchManagementProtocol, VOTElementManagementProtocol, VOTRotorManagementProtocol, VOTWorkspaceUnitTestDelegate;

@interface VOTWorkspace : NSObject
{
    VOTEventFactory *_eventFactory;	// 8 = 0x8
    id <VOTElementManagementProtocol> _elementManager;	// 16 = 0x10
    id <VOTRotorManagementProtocol> _rotorManager;	// 24 = 0x18
    id <VOTDirectTouchManagementProtocol> _directTouchManager;	// 32 = 0x20
    VOTKeyboardManager *_keyboardManager;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_callCenterQueue;	// 48 = 0x30
    TUCallCenter *_callCenter;	// 56 = 0x38
    NSObject<OS_dispatch_queue> *_avAccessQueue;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_keyPostingQueue;	// 72 = 0x48
    struct __CFRunLoop *_runLoop;	// 80 = 0x50
    struct {
        unsigned int count;
        double delay;
        double lastTime;
        _Bool connected;
        double lastRecordedTimeOfDeath;
    } _retryState;	// 88 = 0x58
    _Bool _soundMuted;	// 128 = 0x80
    _Bool _speechMuted;	// 129 = 0x81
    _Bool _voiceOverMuted;	// 130 = 0x82
    _Bool _screenCurtainEnabled;	// 131 = 0x83
    _Bool _isSystemBatteryLow;	// 132 = 0x84
    _Bool _hintsEnabled;	// 133 = 0x85
    _Bool _typingPitchChangeEnabled;	// 134 = 0x86
    _Bool _isPostingKeyboardEvents;	// 135 = 0x87
    _Bool _speakingRateInRotor;	// 136 = 0x88
    _Bool _outputDisabled;	// 137 = 0x89
    _Bool _screenOn;	// 138 = 0x8a
    _Bool _playKeyboardClicksOnHWInput;	// 139 = 0x8b
    _Bool _largeCursorEnabled;	// 140 = 0x8c
    long long _typingMode;	// 144 = 0x90
    long long _tvInteractionMode;	// 152 = 0x98
    VOTOutputRequest *_completionRequest;	// 160 = 0xa0
    long long _orientation;	// 168 = 0xa8
    long long _realOrientation;	// 176 = 0xb0
    double _lastLockButtonPress;	// 184 = 0xb8
    double _lastHomeButtonPress;	// 192 = 0xc0
    double _lastKeyboardKeyPress;	// 200 = 0xc8
    double _lastDeviceInteractionEvent;	// 208 = 0xd0
    double _lastUnmuteEvent;	// 216 = 0xd8
    double _screenOnTime;	// 224 = 0xe0
    double _screenOffTime;	// 232 = 0xe8
    double _lastPowerCheck;	// 240 = 0xf0
    double _lastDeviceLock;	// 248 = 0xf8
    _Bool _deviceIsCharging;	// 256 = 0x100
    NSArray *_enabledLanguageRotorItems;	// 264 = 0x108
    NSString *_selectedLanguage;	// 272 = 0x110
    NSString *_audioAccessoryInstalledAssetLanguage;	// 280 = 0x118
    NSString *_systemSpokenLanguage;	// 288 = 0x120
    NSArray *_enabledBrailleLanguageRotorItems;	// 296 = 0x128
    BRLTTable *_selectedBrailleTable;	// 304 = 0x130
    BRLTTable *_selectedBrailleInputTable;	// 312 = 0x138
    BRLTTable *_selectedBrailleGesturesInputTable;	// 320 = 0x140
    long long _cachedRotorType;	// 328 = 0x148
    NSMutableDictionary *_appCache;	// 336 = 0x150
    NSMutableDictionary *_appCacheWithExactPID;	// 344 = 0x158
    struct os_unfair_lock_s _appCacheLock;	// 352 = 0x160
    NSString *_postKeyThreadKey;	// 360 = 0x168
    struct {
        _Bool isRunLoopEnabled;
        _Bool speakAutocorrectionsEnabled;
        _Bool ringerSwitchSilent;
        _Bool audioIsRoutedToSpeaker;
        _Bool speechLogging;
        _Bool isInternalInstall;
    } _vtwFlags;	// 368 = 0x170
    NSLock *_systemLangaugeLock;	// 376 = 0x178
    _Bool _originalKBAttachedState;	// 384 = 0x180
    _Bool _originalKBAttachedStateIsValid;	// 385 = 0x181
    long long _triggeredKBAttachState;	// 392 = 0x188
    long long _forcedOrientation;	// 400 = 0x190
    long long _applicationOrientation;	// 408 = 0x198
    NSMutableArray *_punctuationGroups;	// 416 = 0x1a0
    AXSSPunctuationGroup *_defaultPunctuationGroup;	// 424 = 0x1a8
    UITextChecker *_textChecker;	// 432 = 0x1b0
    AXAssetController *_assetController;	// 440 = 0x1b8
    _Bool _didSendShutdownSignal;	// 448 = 0x1c0
    _Bool useRingerSwitchForNotificationOutput;	// 449 = 0x1c1
    _Bool _voiceOverIsIdle;	// 450 = 0x1c2
    _Bool _screenCurtainSuspended;	// 451 = 0x1c3
    _Bool _wasEnabledThroughAccessory;	// 452 = 0x1c4
    _Bool _supportsHomeGestures;	// 453 = 0x1c5
    _Bool _accessoryShutdownInProgress;	// 454 = 0x1c6
    _Bool _inUnitTestMode;	// 455 = 0x1c7
    _Bool _inPerformanceTestMode;	// 456 = 0x1c8
    _Bool _isSiriTalking;	// 457 = 0x1c9
    _Bool _isSiriListening;	// 458 = 0x1ca
    _Bool _isOnenessActive;	// 459 = 0x1cb
    _Bool _duckingTemporarilyDisabled;	// 460 = 0x1cc
    _Bool _pauseSpeechAndHaptics;	// 461 = 0x1cd
    _Bool _brailleFormattingEnabled;	// 462 = 0x1ce
    _Bool _imageCaptionsEnabled;	// 463 = 0x1cf
    _Bool _textDetectionEnabled;	// 464 = 0x1d0
    _Bool _buttonIconDetectionEnabled;	// 465 = 0x1d1
    _Bool _soundEffectsEnabled;	// 466 = 0x1d2
    _Bool _captionPanelEnabled;	// 467 = 0x1d3
    _Bool _automaticAccessibilityEnabled;	// 468 = 0x1d4
    _Bool _updateRotorWithElement;	// 469 = 0x1d5
    _Bool _reachabilityActive;	// 470 = 0x1d6
    _Bool _audioDestinationRequestExternal;	// 471 = 0x1d7
    _Bool _systemVolumeControlsAvailablity;	// 472 = 0x1d8
    _Bool _brailleAlertsEnabled;	// 473 = 0x1d9
    _Bool _speakUnderPointer;	// 474 = 0x1da
    _Bool _useDigitalCrownNavigation;	// 475 = 0x1db
    _Bool _telephonyIsActive;	// 476 = 0x1dc
    _Bool;	// 477 = 0x1dd
    _Bool _userRecentlyUnlockedDeviceForUnitTesting;	// 478 = 0x1de
    _Bool _userUnlockedDeviceForUnitTesting;	// 479 = 0x1df
    _Bool _isRingerSwitchSilentForUnitTesting;	// 480 = 0x1e0
    _Bool _disableVoiceOverSettingOnStop;	// 481 = 0x1e1
    int _pointerVoiceOverCursorOption;	// 484 = 0x1e4
    int _currentCallStateForUnitTests;	// 488 = 0x1e8
    long long _navigateImagesOption;	// 496 = 0x1f0
    NSString *additionalLanguageRotorItem;	// 504 = 0x1f8
    CDUnknownBlockType testingEventListener;	// 512 = 0x200
    AXVoiceOverActivity *_selectedActivity;	// 520 = 0x208
    NSString *_previousRotorVoiceIdentifier;	// 528 = 0x210
    long long notificationsWhenLockedOutput;	// 536 = 0x218
    long long bannerNotificationsOutput;	// 544 = 0x220
    double _lastSpeechMuteToggleTime;	// 552 = 0x228
    double _lastSoundMuteToggleTime;	// 560 = 0x230
    unsigned long long _customContentImportance;	// 568 = 0x238
    NSArray *_imageCaptioningDisabledApps;	// 576 = 0x240
    long long _containerOutputFeedback;	// 584 = 0x248
    long long _moreContentOutputFeedback;	// 592 = 0x250
    long long _numberFeedback;	// 600 = 0x258
    long long _emojiFeedback;	// 608 = 0x260
    long long _navigationStyle;	// 616 = 0x268
    long long _navigationDirection;	// 624 = 0x270
    double _lastTelephonyCallActive;	// 632 = 0x278
    NSMutableDictionary *_websiteLanguageMappingOverrides;	// 640 = 0x280
    CDUnknownBlockType _punctuationGroupsUpdatedHandler;	// 648 = 0x288
    double _reachabilityOffset;	// 656 = 0x290
    NSArray *_activities;	// 664 = 0x298
    long long _suppressValueChangeNotificationCount;	// 672 = 0x2a0
    long long _suppressSelectionChangeNotificationCount;	// 680 = 0x2a8
    long long _suppressSelectionChangeNotificationSpeechOutputCount;	// 688 = 0x2b0
    long long _systemVisualizationState;	// 696 = 0x2b8
    AXUISoftwareKeyboardManager *_softwareKeyboardManager;	// 704 = 0x2c0
    _TtC3vot11VOTSettings *_votSettings;	// 712 = 0x2c8
    double _speakUnderPointerDelay;	// 720 = 0x2d0
    VOTVisionEngine *_visionEngine;	// 728 = 0x2d8
    AXMDisplayManager *_displayManager;	// 736 = 0x2e0
    VOSCommandManager *_userCommandManager;	// 744 = 0x2e8
    NSObject<VOTWorkspaceUnitTestDelegate> *_unitTestDelegate;	// 752 = 0x2f0
    NSNumber *_unitTestSpeechRate;	// 760 = 0x2f8
    NSString *_unitTestSystemSpokenLanguage;	// 768 = 0x300
    NSString *_reachabilityIdentifier;	// 776 = 0x308
    AXCharacterSoundMap *_characterSoundMap;	// 784 = 0x310
    NSObject<OS_dispatch_queue> *_managedConfigurationQueue;	// 792 = 0x318
    NSObject<OS_os_transaction> *_votTransaction;	// 800 = 0x320
    double _automaticAccessibilityVisualizationsEnabled;	// 808 = 0x328
}

+ (id)sharedWorkspace;	// IMP=0x00200000000500e4
- (void).cxx_destruct;	// IMP=0x002000000005ff0a
@property(nonatomic) double automaticAccessibilityVisualizationsEnabled; // @synthesize automaticAccessibilityVisualizationsEnabled=_automaticAccessibilityVisualizationsEnabled;
@property(retain, nonatomic) NSObject<OS_os_transaction> *votTransaction; // @synthesize votTransaction=_votTransaction;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *managedConfigurationQueue; // @synthesize managedConfigurationQueue=_managedConfigurationQueue;
@property(retain, nonatomic) AXCharacterSoundMap *characterSoundMap; // @synthesize characterSoundMap=_characterSoundMap;
@property(nonatomic) _Bool disableVoiceOverSettingOnStop; // @synthesize disableVoiceOverSettingOnStop=_disableVoiceOverSettingOnStop;
@property(retain, nonatomic) NSString *reachabilityIdentifier; // @synthesize reachabilityIdentifier=_reachabilityIdentifier;
@property(retain, nonatomic) NSString *unitTestSystemSpokenLanguage; // @synthesize unitTestSystemSpokenLanguage=_unitTestSystemSpokenLanguage;
@property(retain, nonatomic) NSNumber *unitTestSpeechRate; // @synthesize unitTestSpeechRate=_unitTestSpeechRate;
@property(nonatomic) int currentCallStateForUnitTests; // @synthesize currentCallStateForUnitTests=_currentCallStateForUnitTests;
@property(nonatomic) _Bool isRingerSwitchSilentForUnitTesting; // @synthesize isRingerSwitchSilentForUnitTesting=_isRingerSwitchSilentForUnitTesting;
@property(nonatomic) _Bool userUnlockedDeviceForUnitTesting; // @synthesize userUnlockedDeviceForUnitTesting=_userUnlockedDeviceForUnitTesting;
@property(nonatomic) _Bool userRecentlyUnlockedDeviceForUnitTesting; // @synthesize userRecentlyUnlockedDeviceForUnitTesting=_userRecentlyUnlockedDeviceForUnitTesting;
@property(nonatomic) _Bool overridePropertiesForTesting; // @synthesize overridePropertiesForTesting=_overridePropertiesForTesting;
@property(nonatomic) __weak NSObject<VOTWorkspaceUnitTestDelegate> *unitTestDelegate; // @synthesize unitTestDelegate=_unitTestDelegate;
@property(nonatomic) _Bool telephonyIsActive; // @synthesize telephonyIsActive=_telephonyIsActive;
@property(readonly, nonatomic) _Bool useDigitalCrownNavigation; // @synthesize useDigitalCrownNavigation=_useDigitalCrownNavigation;
@property(retain, nonatomic) VOSCommandManager *userCommandManager; // @synthesize userCommandManager=_userCommandManager;
@property(retain, nonatomic) AXMDisplayManager *displayManager; // @synthesize displayManager=_displayManager;
@property(retain, nonatomic) VOTVisionEngine *visionEngine; // @synthesize visionEngine=_visionEngine;
@property(nonatomic) double speakUnderPointerDelay; // @synthesize speakUnderPointerDelay=_speakUnderPointerDelay;
@property(nonatomic) _Bool speakUnderPointer; // @synthesize speakUnderPointer=_speakUnderPointer;
@property(nonatomic) int pointerVoiceOverCursorOption; // @synthesize pointerVoiceOverCursorOption=_pointerVoiceOverCursorOption;
@property(nonatomic) _Bool brailleAlertsEnabled; // @synthesize brailleAlertsEnabled=_brailleAlertsEnabled;
@property(retain, nonatomic) _TtC3vot11VOTSettings *votSettings; // @synthesize votSettings=_votSettings;
@property(readonly, nonatomic) AXUISoftwareKeyboardManager *softwareKeyboardManager; // @synthesize softwareKeyboardManager=_softwareKeyboardManager;
@property(nonatomic) _Bool systemVolumeControlsAvailablity; // @synthesize systemVolumeControlsAvailablity=_systemVolumeControlsAvailablity;
@property(nonatomic) long long systemVisualizationState; // @synthesize systemVisualizationState=_systemVisualizationState;
@property(nonatomic) long long suppressSelectionChangeNotificationSpeechOutputCount; // @synthesize suppressSelectionChangeNotificationSpeechOutputCount=_suppressSelectionChangeNotificationSpeechOutputCount;
@property(nonatomic) long long suppressSelectionChangeNotificationCount; // @synthesize suppressSelectionChangeNotificationCount=_suppressSelectionChangeNotificationCount;
@property(nonatomic) long long suppressValueChangeNotificationCount; // @synthesize suppressValueChangeNotificationCount=_suppressValueChangeNotificationCount;
@property(retain, nonatomic) NSArray *activities; // @synthesize activities=_activities;
@property(nonatomic) _Bool audioDestinationRequestExternal; // @synthesize audioDestinationRequestExternal=_audioDestinationRequestExternal;
@property(nonatomic) double reachabilityOffset; // @synthesize reachabilityOffset=_reachabilityOffset;
@property(nonatomic) _Bool reachabilityActive; // @synthesize reachabilityActive=_reachabilityActive;
@property(copy, nonatomic) CDUnknownBlockType punctuationGroupsUpdatedHandler; // @synthesize punctuationGroupsUpdatedHandler=_punctuationGroupsUpdatedHandler;
@property(retain, nonatomic) NSMutableDictionary *websiteLanguageMappingOverrides; // @synthesize websiteLanguageMappingOverrides=_websiteLanguageMappingOverrides;
@property(nonatomic) _Bool largeCursorEnabled; // @synthesize largeCursorEnabled=_largeCursorEnabled;
@property(nonatomic) _Bool updateRotorWithElement; // @synthesize updateRotorWithElement=_updateRotorWithElement;
@property(retain, nonatomic) BRLTTable *selectedBrailleGesturesInputTable; // @synthesize selectedBrailleGesturesInputTable=_selectedBrailleGesturesInputTable;
@property(nonatomic) _Bool automaticAccessibilityEnabled; // @synthesize automaticAccessibilityEnabled=_automaticAccessibilityEnabled;
@property(nonatomic) double lastTelephonyCallActive; // @synthesize lastTelephonyCallActive=_lastTelephonyCallActive;
@property(nonatomic) _Bool captionPanelEnabled; // @synthesize captionPanelEnabled=_captionPanelEnabled;
@property(nonatomic) long long navigationDirection; // @synthesize navigationDirection=_navigationDirection;
@property(nonatomic) long long navigationStyle; // @synthesize navigationStyle=_navigationStyle;
@property(nonatomic) long long emojiFeedback; // @synthesize emojiFeedback=_emojiFeedback;
@property(nonatomic) long long numberFeedback; // @synthesize numberFeedback=_numberFeedback;
@property(nonatomic) _Bool soundEffectsEnabled; // @synthesize soundEffectsEnabled=_soundEffectsEnabled;
@property(nonatomic) _Bool buttonIconDetectionEnabled; // @synthesize buttonIconDetectionEnabled=_buttonIconDetectionEnabled;
@property(nonatomic) _Bool textDetectionEnabled; // @synthesize textDetectionEnabled=_textDetectionEnabled;
@property(nonatomic) _Bool imageCaptionsEnabled; // @synthesize imageCaptionsEnabled=_imageCaptionsEnabled;
@property(nonatomic) long long moreContentOutputFeedback; // @synthesize moreContentOutputFeedback=_moreContentOutputFeedback;
@property(nonatomic) _Bool brailleFormattingEnabled; // @synthesize brailleFormattingEnabled=_brailleFormattingEnabled;
@property(nonatomic) long long containerOutputFeedback; // @synthesize containerOutputFeedback=_containerOutputFeedback;
@property(retain, nonatomic) NSArray *imageCaptioningDisabledApps; // @synthesize imageCaptioningDisabledApps=_imageCaptioningDisabledApps;
@property(nonatomic) unsigned long long customContentImportance; // @synthesize customContentImportance=_customContentImportance;
@property(nonatomic) _Bool pauseSpeechAndHaptics; // @synthesize pauseSpeechAndHaptics=_pauseSpeechAndHaptics;
@property(nonatomic) _Bool duckingTemporarilyDisabled; // @synthesize duckingTemporarilyDisabled=_duckingTemporarilyDisabled;
@property(nonatomic) _Bool isOnenessActive; // @synthesize isOnenessActive=_isOnenessActive;
@property(nonatomic) _Bool isSiriListening; // @synthesize isSiriListening=_isSiriListening;
@property(nonatomic) _Bool isSiriTalking; // @synthesize isSiriTalking=_isSiriTalking;
@property(nonatomic) _Bool inPerformanceTestMode; // @synthesize inPerformanceTestMode=_inPerformanceTestMode;
@property(nonatomic) _Bool inUnitTestMode; // @synthesize inUnitTestMode=_inUnitTestMode;
@property(nonatomic) _Bool accessoryShutdownInProgress; // @synthesize accessoryShutdownInProgress=_accessoryShutdownInProgress;
@property(nonatomic) _Bool supportsHomeGestures; // @synthesize supportsHomeGestures=_supportsHomeGestures;
@property(nonatomic) _Bool wasEnabledThroughAccessory; // @synthesize wasEnabledThroughAccessory=_wasEnabledThroughAccessory;
@property(nonatomic) _Bool screenCurtainSuspended; // @synthesize screenCurtainSuspended=_screenCurtainSuspended;
@property(nonatomic) _Bool voiceOverIsIdle; // @synthesize voiceOverIsIdle=_voiceOverIsIdle;
@property(nonatomic) double lastSoundMuteToggleTime; // @synthesize lastSoundMuteToggleTime=_lastSoundMuteToggleTime;
@property(nonatomic) double lastSpeechMuteToggleTime; // @synthesize lastSpeechMuteToggleTime=_lastSpeechMuteToggleTime;
@property(nonatomic) _Bool useRingerSwitchForNotificationOutput; // @synthesize useRingerSwitchForNotificationOutput;
@property(nonatomic) long long bannerNotificationsOutput; // @synthesize bannerNotificationsOutput;
@property(nonatomic) long long notificationsWhenLockedOutput; // @synthesize notificationsWhenLockedOutput;
@property(retain, nonatomic) NSString *previousRotorVoiceIdentifier; // @synthesize previousRotorVoiceIdentifier=_previousRotorVoiceIdentifier;
@property(nonatomic) double screenOnTime; // @synthesize screenOnTime=_screenOnTime;
@property(copy, nonatomic) CDUnknownBlockType testingEventListener; // @synthesize testingEventListener;
@property(nonatomic) _Bool playKeyboardClicksOnHWInput; // @synthesize playKeyboardClicksOnHWInput=_playKeyboardClicksOnHWInput;
@property(nonatomic) _Bool outputDisabled; // @synthesize outputDisabled=_outputDisabled;
@property(nonatomic) _Bool speakingRateInRotor; // @synthesize speakingRateInRotor=_speakingRateInRotor;
@property(nonatomic) long long rotorType; // @synthesize rotorType=_cachedRotorType;
@property(nonatomic) _Bool isSystemBatteryLow; // @synthesize isSystemBatteryLow=_isSystemBatteryLow;
@property(nonatomic) _Bool screenCurtainEnabled; // @synthesize screenCurtainEnabled=_screenCurtainEnabled;
@property(nonatomic) double lastKeyboardKeyPress; // @synthesize lastKeyboardKeyPress=_lastKeyboardKeyPress;
@property(nonatomic) double lastLockButtonPress; // @synthesize lastLockButtonPress=_lastLockButtonPress;
@property(nonatomic) double lastHomeButtonPress; // @synthesize lastHomeButtonPress=_lastHomeButtonPress;
@property(retain, nonatomic) NSString *additionalLanguageRotorItem; // @synthesize additionalLanguageRotorItem;
@property(nonatomic) _Bool typingPitchChangeEnabled; // @synthesize typingPitchChangeEnabled=_typingPitchChangeEnabled;
@property(nonatomic) long long navigateImagesOption; // @synthesize navigateImagesOption=_navigateImagesOption;
@property(nonatomic) _Bool voiceOverMuted; // @synthesize voiceOverMuted=_voiceOverMuted;
@property(nonatomic) _Bool soundMuted; // @synthesize soundMuted=_soundMuted;
@property(readonly, nonatomic) NSString *systemSpokenLanguage; // @dynamic systemSpokenLanguage;
- (struct CGPoint)convertDevicePointToZoomedPoint:(struct CGPoint)arg1;	// IMP=0x001000000005f588
- (void)handleUSBMFiBrailleDisplayConnected;	// IMP=0x001000000005f2f6
- (void)assetController:(id)arg1 didUpdateCatalogForPolicy:(id)arg2 wasSuccessful:(_Bool)arg3 error:(id)arg4;	// IMP=0x001000000005f1ec
- (void)assetController:(id)arg1 didFinishDownloadingAsset:(id)arg2 wasSuccessful:(_Bool)arg3 error:(id)arg4 hasRemainingDownloads:(_Bool)arg5;	// IMP=0x001000000005f11c
- (void)assetController:(id)arg1 didFinishRefreshingAssets:(id)arg2 wasSuccessful:(_Bool)arg3 error:(id)arg4;	// IMP=0x001000000005eee1
- (id)_validateAssetFromResults:(id)arg1;	// IMP=0x001000000005ee35
- (void)handleBluetoothBrailleDisplayConnected;	// IMP=0x001000000005ecd0
- (void)_setUSBRMPreferenceDisabled;	// IMP=0x001000000005ec71
- (_Bool)_userHasDisabledUSBRM;	// IMP=0x001000000005ec18
@property(readonly, nonatomic) _Bool navigationStyleHonorsGroups;
@property(retain, nonatomic) NSObject<VOTRotorManagementProtocol> *rotorManager; // @dynamic rotorManager;
@property(retain, nonatomic) NSObject<VOTElementManagementProtocol> *elementManager; // @dynamic elementManager;
- (id)applicationForPID:(int)arg1;	// IMP=0x001000000005e8b4
- (id)applicationForElement:(id)arg1;	// IMP=0x001000000005e486
- (id)applicationForCurrentElement;	// IMP=0x001000000005e423
- (_Bool)isBaseSystemSpokenEqualToLocalization;	// IMP=0x001000000005e2ed
- (void)_selectedBrailleGesturesInputTableChanged;	// IMP=0x001000000005e24c
- (id)selectedBrailleGesturesInputTable:(id)arg1;	// IMP=0x001000000005e23b
- (void)_selectedBrailleInputTableChanged;	// IMP=0x001000000005e098
@property(retain, nonatomic) BRLTTable *selectedBrailleInputTable;
- (void)_selectedBrailleTableChanged;	// IMP=0x001000000005dc96
@property(retain, nonatomic) BRLTTable *selectedBrailleTable;
- (void)updateSelectedLanguage;	// IMP=0x001000000005d8fc
@property(retain) NSString *selectedLanguage; // @synthesize selectedLanguage=_selectedLanguage;
- (void)unitTestSetBrailleRotorItems:(id)arg1;	// IMP=0x001000000005d7e8
@property(readonly, nonatomic) NSArray *brailleLanguageRotorItems;
@property(readonly, nonatomic) NSArray *languageRotorItems; // @dynamic languageRotorItems;
- (double)lastLockButtonPressTime;	// IMP=0x001000000005d55d
- (_Bool)isRingerSwitchSilent;	// IMP=0x001000000005d4f2
- (_Bool)userRecentlyUnlockedDevice;	// IMP=0x001000000005d47f
- (_Bool)userUnlockedDevice;	// IMP=0x001000000005d429
- (_Bool)isAudioRoutedToSpeaker;	// IMP=0x001000000005d41d
@property(nonatomic) _Bool tapAndHoldMode; // @dynamic tapAndHoldMode;
- (void)_localeChanged:(id)arg1;	// IMP=0x001000000005d3d9
- (void)_activeAudioRouteChanged:(id)arg1;	// IMP=0x001000000005d301
- (int)currentCallState;	// IMP=0x001000000005d1f5
- (int)_callCenterQueue_currentCallState;	// IMP=0x001000000005d0c2
@property(readonly, nonatomic) double speechRateFromSettings;
- (_Bool)screenOn;	// IMP=0x001000000005d01e
- (void)setScreenOn:(_Bool)arg1 silently:(_Bool)arg2;	// IMP=0x001000000005cfc0
- (void)screenLockOccurred;	// IMP=0x001000000005cf93
- (void)unmuteEligibleEventOccured;	// IMP=0x001000000005cf2e
- (void)userInteractedWithDevice;	// IMP=0x001000000005cec9
@property(nonatomic) _Bool speechMuted; // @synthesize speechMuted=_speechMuted;
@property(nonatomic) _Bool speechLogging; // @dynamic speechLogging;
- (void)refreshBraille:(_Bool)arg1 rotorSelection:(id)arg2;	// IMP=0x001000000005cd8e
- (void)_postNextLanguageEvent;	// IMP=0x001000000005cd31
- (void)performNextLanguageButtonPress;	// IMP=0x001000000005ccd0
- (void)performEjectButtonPress;	// IMP=0x001000000005cbd7
- (void)performVolumeDownButtonPress;	// IMP=0x001000000005cb07
- (void)performVolumeUpButtonPress;	// IMP=0x001000000005ca37
- (void)performHomeButtonPress;	// IMP=0x001000000005c932
- (void)resetSystemBatteryLowState;	// IMP=0x001000000005c8ac
- (void)rotateDeviceOrientation:(_Bool)arg1;	// IMP=0x001000000005c7cb
- (void)_resetOrientationAndAnnounce:(_Bool)arg1 updateApplication:(_Bool)arg2;	// IMP=0x001000000005c706
- (void)resetOrientation;	// IMP=0x001000000005c6ea
- (long long)applicationOrientation;	// IMP=0x001000000005c6dd
- (long long)deviceOrientation;	// IMP=0x001000000005c6d0
- (void)_setDeviceOrientation:(long long)arg1 shouldAnnounce:(_Bool)arg2 updateApplication:(_Bool)arg3;	// IMP=0x001000000005c1d1
- (_Bool)announceOrientationChanges;	// IMP=0x001000000005c1c9
- (_Bool)speakAutocorrectionsEnabled;	// IMP=0x001000000005c1bd
- (void)_speakCorrectionsChanged;	// IMP=0x001000000005c167
- (void)_preferencesCaptionPanelChanged;	// IMP=0x001000000005c107
- (void)_languageChangedInBuddy;	// IMP=0x001000000005c0f5
- (void)_languageChanged;	// IMP=0x001000000005c07b
- (unsigned long long)fingerCount;	// IMP=0x001000000005c065
- (struct CGPoint)fingerPosition;	// IMP=0x001000000005c04f
- (void)handleReturnToSpringBoard;	// IMP=0x001000000005c00c
- (void)cancelTapAndHoldMode;	// IMP=0x001000000005bfe6
- (void)startTapAndHoldMode:(_Bool)arg1;	// IMP=0x001000000005bfd0
@property(readonly, nonatomic) _Bool directTouchElementsPresent;
- (void);	// IMP=0x001000000005bf8c
- (void)handleSetForcedOrientation:(long long)arg1 shouldAnnounce:(_Bool)arg2;	// IMP=0x001000000005bf3a
- (void)handleOrientationChanged;	// IMP=0x001000000005bf17
- (void)handleRingerSwitchSwitched:(id)arg1;	// IMP=0x001000000005bec1
- (void)handleProximityEvent:(id)arg1;	// IMP=0x001000000005be61
- (void)handleLockButtonPress:(id)arg1;	// IMP=0x001000000005bde8
- (void)handlePlayPauseKeyPress:(id)arg1;	// IMP=0x001000000005bdd2
- (void)_wst_handleMediaKeyPress:(id)arg1;	// IMP=0x001000000005bdc0
- (void)handleMediaKeyPress:(id)arg1;	// IMP=0x001000000005bdba
- (void)_handleSystemMuteKey:(id)arg1;	// IMP=0x001000000005ba04
- (void)temporarilyChangeQuickNavState:(_Bool)arg1;	// IMP=0x001000000005b95b
- (void)_temporarilyChangeQuickNav:(id)arg1;	// IMP=0x001000000005b926
- (id)keyboardPressInfo;	// IMP=0x001000000005b910
- (void)handleTurnOffSoundAndCurtainEvent:(id)arg1;	// IMP=0x001000000005b8fa
- (void)handleKeyboardKeyEvent:(id)arg1 eventOrigin:(long long)arg2;	// IMP=0x001000000005b8e4
- (void)handleAppleTVRemoteEvent:(id)arg1 eventOrigin:(long long)arg2 isRTL:(_Bool)arg3;	// IMP=0x001000000005b694
- (void)_wst_handleMenuButtonPress:(id)arg1;	// IMP=0x001000000005b682
- (void)handleMenuButtonPress:(id)arg1;	// IMP=0x001000000005b502
- (void)_wst_handleVolumeButtonPress:(id)arg1;	// IMP=0x001000000005b4f0
- (void)handleVolumeButtonPress:(id)arg1;	// IMP=0x001000000005b2a8
- (void)_selfDestruct;	// IMP=0x001000000005b11e
@property(readonly, nonatomic) _Bool isInternalInstall; // @dynamic isInternalInstall;
- (void)stop:(int)arg1;	// IMP=0x001000000005adb0
- (void)outputRequestFinished:(id)arg1;	// IMP=0x001000000005ad43
- (void)_stopRunLoop;	// IMP=0x001000000005ad27
- (void)setVoiceOverMuted:(_Bool)arg1 sendRequest:(_Bool)arg2;	// IMP=0x001000000005a7e7
- (void)punctuationGroupsChanged:(id)arg1;	// IMP=0x001000000005a503
- (id)defaultPunctuationGroup;	// IMP=0x001000000005a3e0
@property(readonly, nonatomic) NSArray *punctuationGroups;
- (id)punctuationGroupForUUID:(id)arg1;	// IMP=0x001000000005a174
- (void)systemSpokenLanguageChanged:(id)arg1;	// IMP=0x001000000005a101
@property(retain, nonatomic) AXVoiceOverActivity *selectedActivity; // @synthesize selectedActivity=_selectedActivity;
- (id)phoneticStringForCharacter:(id)arg1 andVoiceIdentifier:(id)arg2;	// IMP=0x0010000000059f77
- (void)_preferencesScreenCurtainChanged:(id)arg1;	// IMP=0x0010000000059f63
- (void)_preferencesTypingModeChanged:(id)arg1;	// IMP=0x0010000000059f47
- (void)preferencesBrailleLanguageRotorItemsChanged:(id)arg1;	// IMP=0x0010000000059c88
- (void)preferencesLanguageRotorItemsChanged:(id)arg1;	// IMP=0x00100000000599cf
- (void)preferencesKeyboardClickStatusChange:(id)arg1;	// IMP=0x00100000000599bb
- (void)_preferencesSpeakNotifications;	// IMP=0x00100000000598d4
- (void)_preferencesSpeakingRateInRotorChanged;	// IMP=0x0010000000059874
- (void)_preferencesSpeechRateChange;	// IMP=0x001000000005984a
- (void)_preferencesNavigateImagesOptionChange;	// IMP=0x00100000000597ea
- (void)_preferencesSpeakHintsChange;	// IMP=0x0010000000059785
- (void)_preferencesTypingPitchChange;	// IMP=0x0010000000059725
- (void)setUseDigitalCrownNavigationEnabled:(_Bool)arg1;	// IMP=0x00100000000596ce
- (void)_preferenceUseDigitalCrownNavigationChanged;	// IMP=0x0010000000059678
- (void)_preferencesAlwaysUseNemethForMathChange;	// IMP=0x0010000000059634
@property(readonly, nonatomic) _Bool brailleInputShouldBeDeactivatedByEscape;
@property(readonly, nonatomic) _Bool brailleInputWantsToStayActive;
@property(readonly, nonatomic) _Bool brailleInputAllowsElementMovement;
@property(readonly, nonatomic) long long brailleInputTypingMode;
@property(readonly, nonatomic) _Bool brailleInputActive;
@property(readonly, nonatomic) NSArray *focusedApplications;
@property(readonly, nonatomic) VOTElement *currentElement;
- (void)postKeyboardEventWithCharacters:(id)arg1 originalCharacters:(id)arg2 modifiers:(unsigned int)arg3 keyCode:(unsigned short)arg4;	// IMP=0x001000000005935c
- (void)postKeyboardEvent:(_Bool)arg1 modifiers:(unsigned int)arg2 keyCode:(unsigned short)arg3;	// IMP=0x0010000000059248
- (void)_postKeyboardEvent:(id)arg1 modifiers:(id)arg2 keyCode:(id)arg3;	// IMP=0x00100000000590ab
- (void)_postKeyboardEventWithKeyCode:(unsigned short)arg1 characters:(id)arg2 originalCharacters:(id)arg3 modifierState:(unsigned int)arg4 eventType:(unsigned int)arg5;	// IMP=0x0010000000058f6e
- (void)_postKeyboardEventWithKeyCode:(unsigned short)arg1 characters:(id)arg2 originalCharacters:(id)arg3 modifierState:(unsigned int)arg4 isKeyDown:(_Bool)arg5;	// IMP=0x0010000000058f49
- (void)_postKeyboardEventWithKeyCode:(unsigned short)arg1 modifierState:(unsigned int)arg2 isKeyDown:(_Bool)arg3;	// IMP=0x0010000000058f1d
- (void)_postKeyboardEventsForModifiers:(unsigned int)arg1 isKeyDown:(_Bool)arg2;	// IMP=0x0010000000058e3a
- (void)_postKeyboardEventWithCharacters:(id)arg1 originalCharacters:(id)arg2 modifiers:(id)arg3 keyCode:(id)arg4;	// IMP=0x0010000000058cb4
- (void)dispatchCommand:(id)arg1 bypassGesturedInput:(_Bool)arg2;	// IMP=0x0010000000058c9e
- (void)dispatchCommand:(id)arg1;	// IMP=0x0010000000058c8a
@property(nonatomic) long long typingMode;
- (void)_voiceOverTouchEnabledChange:(struct __CFString *)arg1;	// IMP=0x001000000005846e
- (void)_voiceOverUsageConfirmed;	// IMP=0x0010000000058427
- (void)_checkVoiceOverWasConfirmed;	// IMP=0x00100000000583b4
- (void)_showVOTNoHomeButtonGestureAlert;	// IMP=0x0010000000058366
- (void)_showConfirmPanel;	// IMP=0x001000000005831d
- (_Bool)voiceOverIsConfirmed;	// IMP=0x00100000000582f4
- (void)loadUIKit;	// IMP=0x0010000000058285
- (void)run;	// IMP=0x0010000000057fde
- (void)_sendGreetingMessage;	// IMP=0x0010000000057cbb
- (id)_systemBootTime;	// IMP=0x0010000000057c09
- (void)_registerWithSystem;	// IMP=0x0010000000057b03
- (void)_updateScreenCurtainEnabled:(_Bool)arg1;	// IMP=0x001000000005791f
- (void)_registerWithSpringBoard;	// IMP=0x001000000005749c
- (_Bool)isVoiceOverTouchPreferenceEnabled;	// IMP=0x001000000005748c
- (_Bool)isAccessibilityEnabled;	// IMP=0x001000000005747c
- (void)handleSystemWideServerDied;	// IMP=0x0010000000057152
- (_Bool)isSystemWideServerAlive;	// IMP=0x0010000000057149
- (void)_registerForExternalDevices;	// IMP=0x0010000000057143
- (void)_preferencesActivitiesChanged;	// IMP=0x0010000000056dbe
- (void)_updateActivityListeners;	// IMP=0x0010000000056c92
- (void)addMisspellingsForString:(id)arg1;	// IMP=0x00100000000569e3
- (void)currentElementDidUpdate:(id)arg1;	// IMP=0x0010000000056902
- (void)_preferencesSelectedLanguageChanged;	// IMP=0x001000000005684d
- (void)_preferencesSelectedActivityChanged;	// IMP=0x001000000005678b
- (void)dealloc;	// IMP=0x00100000000566c7
- (void)_registerForPreferenceChanges;	// IMP=0x0010000000055300
- (void)_handleReachabilityChanges;	// IMP=0x0010000000054fcc
- (void)willSwitchUser;	// IMP=0x0010000000054fc6
- (void)_registerForUserSwitches;	// IMP=0x0010000000054fc0
- (void)_migratePreferencesIfNeeded;	// IMP=0x0010000000054f63
- (void)_updatePointerVoiceOverOptions;	// IMP=0x0010000000054f09
- (void)_updateMainScreenSize:(struct CGSize)arg1 scale:(double)arg2;	// IMP=0x0010000000054eff
- (void)_handleBluetoothEnablement;	// IMP=0x0010000000054dcb
- (void)_handleOnenessCheck;	// IMP=0x0010000000054bae
- (id)imageCaptionModelAssetPolicy;	// IMP=0x0010000000054b95
- (void)_initializeCaptionModel;	// IMP=0x0010000000054a7d
- (void)_initialize;	// IMP=0x00100000000530de
- (void)_replaceHighMemoryVoiceIDWithDefaultVoiceIDForLanguage:(id)arg1 preferredFallbackLanguage:(id)arg2;	// IMP=0x0010000000052d14
- (void)_attemptRecoveryFromCrashloopDueToVoiceMemoryPressure;	// IMP=0x0010000000052b70
@property(readonly) _Bool usesDisplayManager;
- (void)mlElementDetectorReceivedFrames:(id)arg1 labels:(id)arg2 uiClasses:(id)arg3;	// IMP=0x0010000000052966
- (void)mlElementDetectorUpdatedElements;	// IMP=0x00100000000528c3
- (void)mlElementDetectorScrollToVisibleOccurred:(struct CGPoint)arg1;	// IMP=0x001000000005286a
- (_Bool)softwareKeyboardManagerShouldSetHardwareKeyboardAttached:(id)arg1 hardwareKeyboardIsCurrentlyAttached:(_Bool)arg2 newHardwareKeyboardAttachedValue:(_Bool *)arg3;	// IMP=0x0010000000052852
- (void)softwareKeyboardManagerDidChangeHardwareKeyboardAttached:(id)arg1;	// IMP=0x0010000000052845
- (void)softwareKeyboardManager:(id)arg1 didSetHardwareKeyboardAttached:(_Bool)arg2;	// IMP=0x0010000000052839
@property(readonly, nonatomic) _Bool hasActive2DBrailleDisplay;
- (void)softwareKeyboardManagerWillUpdateKeyboardState:(id)arg1;	// IMP=0x001000000005253d
@property(nonatomic) _Bool perkinsChordKeyboardInputEnabled;
@property(nonatomic) _Bool perkinsKeyboardInputEnabled;
@property long long tvInteractionMode;
- (void)setTvInteractionModeWithoutSaving:(long long)arg1;	// IMP=0x0010000000052391
@property(nonatomic) _Bool allowSingleLetterSearching; // @dynamic allowSingleLetterSearching;
- (id)_assetUpdaterClient;	// IMP=0x0010000000052282
- (void)_archerNotifyUserOfNavigationChanges;	// IMP=0x001000000005227c
- (void)_hunterMigrateDigitalCrownNavigation;	// IMP=0x0010000000052276
- (void)_hunterMigrateDefaultRotors;	// IMP=0x0010000000052270
- (void)_yukonMigrateLanguageRotors;	// IMP=0x0010000000051f98
- (void)_tigrisMigrateLanguageRotors;	// IMP=0x0010000000051af8
- (void)_screenChange:(id)arg1;	// IMP=0x0010000000051a59
- (double)activeBrailleAutoAdvanceDuration;	// IMP=0x0010000000051896
- (_Bool)activeBrailleGeneralStatusCellPreference;	// IMP=0x00100000000516d9
- (_Bool)activeBrailleAlertsPreference;	// IMP=0x0010000000051531
- (_Bool)activeBrailleTextStatusCellPreference;	// IMP=0x0010000000051362
- (long long)activeBrailleOutputPreference;	// IMP=0x00100000000511a5
- (long long)activeBrailleInputPreference;	// IMP=0x0010000000050fe8
@property(nonatomic) _Bool hintsEnabled;
- (void)_crystalBMigrateDuckingVolumePreferences;	// IMP=0x0010000000050b85
- (void)_applyVoiceOverMigrations;	// IMP=0x0010000000050ae3
@property(readonly, nonatomic) VOTEventFactory *eventFactory;
- (void)_callStatusChanged:(id)arg1;	// IMP=0x0010000000050984
- (id)init;	// IMP=0x00100000000500f5
- (void)notePostedEventForUnitTesting:(id)arg1;	// IMP=0x001000000006020e
- (id)lastPostedEventForUnitTesting;	// IMP=0x00100000000601fd
- (id)currentElementRotorString;	// IMP=0x0010000000060258
- (id)lastScreenChangeTime;	// IMP=0x0010000000060222
- (void)_testFetchWebElementRects;	// IMP=0x00100000000602ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

