//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSURL, PHPhotoLibrary;
@protocol PXRootLibraryNavigationController;

@interface PhotosURLNavigationRequest : NSObject
{
    CDUnknownBlockType _navigationCompletionHandler;	// 8 = 0x8
    NSURL *_destinationURL;	// 16 = 0x10
    id <PXRootLibraryNavigationController> _rootController;	// 24 = 0x18
    PHPhotoLibrary *_photoLibrary;	// 32 = 0x20
    unsigned long long _state;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0020000000042d4e
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) PHPhotoLibrary *photoLibrary; // @synthesize photoLibrary=_photoLibrary;
@property(readonly, nonatomic) id <PXRootLibraryNavigationController> rootController; // @synthesize rootController=_rootController;
@property(readonly, copy, nonatomic) NSURL *destinationURL; // @synthesize destinationURL=_destinationURL;
- (void)_rootUpdatedAvailableDestinations:(id)arg1;	// IMP=0x0010000000042d03
- (void)_contextDidFinishMerge:(id)arg1;	// IMP=0x0010000000042cf1
- (void)_finishNavigationSuccessfully:(_Bool)arg1;	// IMP=0x0010000000042c81
- (void)_processPendingNavigation;	// IMP=0x0010000000042c13
- (void)_schedulePendingNavigation;	// IMP=0x0010000000042ae6
- (void)cancelPendingNavigation;	// IMP=0x0010000000042a89
- (void)navigateAllowingRetry:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000042a3d
- (id)_uuidFromURLParams:(id)arg1 prefix:(id)arg2;	// IMP=0x001000000004286f
- (void)_navigateAllowingRetry:(_Bool)arg1;	// IMP=0x0010000000041568
- (id)_albumForKnownName:(id)arg1 orUUID:(id)arg2 requestIsValid:(_Bool *)arg3;	// IMP=0x00100000000412d8
- (void)dealloc;	// IMP=0x001000000004112a
- (id)initWithDestinationURL:(id)arg1 rootController:(id)arg2;	// IMP=0x0010000000040f5b

@end

