//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface LUIRecentUserGridViewController
{
}

- (void)update;	// IMP=0x002000000001dab6
- (void)bottomLeftVibrantButtonTapped:(id)arg1;	// IMP=0x001000000001da20
- (long long)imageTypeForBottomLeftVibrantButton;	// IMP=0x001000000001da18
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x001000000001d9a3
- (void)viewDidLoad;	// IMP=0x001000000001d928

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

