//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface LUIUserInfoStyle : NSObject
{
}

+ (id)sharedStyle;	// IMP=0x004000000000f299
- (double)bottomPadding;	// IMP=0x004000000000f981
- (double)sidePadding;	// IMP=0x001000000000f973
- (double)stackViewSpacing;	// IMP=0x001000000000f965
- (void)applyRowStackViewPropertiesToStackViews:(id)arg1;	// IMP=0x001000000000f83b
- (void)applyRowStackViewPropertiesToStackView:(id)arg1;	// IMP=0x001000000000f77c
- (void)applyThemeToLabels:(id)arg1;	// IMP=0x001000000000f652
- (void)applyThemeToLabel:(id)arg1;	// IMP=0x001000000000f52b
- (void)applyIndicatorLabelThemeToLabels:(id)arg1;	// IMP=0x001000000000f401
- (void)applyIndicatorLabelThemeToLabel:(id)arg1;	// IMP=0x001000000000f2ee

@end

