//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MADComputeServiceBackgroundSystemTask
{
}

+ (id)identifier;	// IMP=0x00400000000c85ea
+ (id)sharedTask;	// IMP=0x00100000000c855d
- (void)executeWithCancelBlock:(CDUnknownBlockType)arg1 progressHandler:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00400000000c899f
- (void)submitTask:(id *)arg1;	// IMP=0x00100000000c85f7

@end

