//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (VCPLivePhotoEffects)
- (id)vcp_matchingScenes;	// IMP=0x00100000000dc8be
- (id)vcp_gatingDescriptions;	// IMP=0x00100000000dc8a2
- (id)vcp_recipe;	// IMP=0x00100000000dc7f3
- (unsigned long long)vcp_longExposureSugestionState;	// IMP=0x00100000000dc788
- (unsigned long long)vcp_loopSugestionState;	// IMP=0x00100000000dc71d
- (_Bool)vcp_isValidEffectsResult;	// IMP=0x00100000000dc647
- (id)vcp_effectsResult;	// IMP=0x00100000000dc55b
@end

