//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface VCPMADOCRAssetProcessingTask
{
}

+ (unsigned long long)taskID;	// IMP=0x002000000005fa12
+ (id)name;	// IMP=0x001000000005fa05
- (id)batchWithAnalysisDatabase:(id)arg1 allowDownload:(_Bool)arg2 cancelBlock:(CDUnknownBlockType)arg3;	// IMP=0x004000000005faa4
- (_Bool)shouldProcessAsset:(id)arg1;	// IMP=0x001000000005fa8f
- (void)dealloc;	// IMP=0x001000000005fa1d

@end

