//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class SCATModernMenuBackgroundContainerView, UIVisualEffectView;

@interface SCATModernMenuBackgroundView : UIView
{
    struct CGPath *_menuBorderPath;	// 8 = 0x8
    _Bool _shouldRoundMenuCorners;	// 16 = 0x10
    SCATModernMenuBackgroundContainerView *_containerView;	// 24 = 0x18
    UIVisualEffectView *_backdropView;	// 32 = 0x20
    long long _tip;	// 40 = 0x28
    double _normalizedHorizontalTipCenter;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000038c94
@property(nonatomic) _Bool shouldRoundMenuCorners; // @synthesize shouldRoundMenuCorners=_shouldRoundMenuCorners;
@property(nonatomic) double normalizedHorizontalTipCenter; // @synthesize normalizedHorizontalTipCenter=_normalizedHorizontalTipCenter;
@property(nonatomic) long long tip; // @synthesize tip=_tip;
@property(retain, nonatomic) UIVisualEffectView *backdropView; // @synthesize backdropView=_backdropView;
@property(retain, nonatomic) SCATModernMenuBackgroundContainerView *containerView; // @synthesize containerView=_containerView;
- (id)scatOverrideCursorTheme;	// IMP=0x0010000000038bfa
- (_Bool)scatPerformAction:(int)arg1;	// IMP=0x0010000000038b36
- (_Bool)scatSupportsAction:(int)arg1;	// IMP=0x0010000000038b27
- (struct CGPath *)scatPath;	// IMP=0x0010000000038b15
- (id)scatSpeakableDescription;	// IMP=0x0010000000038b04
- (struct CGPath *)_copyMenuPathWithNoTipForRect:(struct CGRect)arg1;	// IMP=0x00100000000389db
- (struct CGPath *)_copyMenuPathWithTipForRect:(struct CGRect)arg1;	// IMP=0x00100000000385c6
- (double)_adjustedXAnchorPositionToClearCornersOfRect:(struct CGRect)arg1;	// IMP=0x001000000003850e
- (void)_updateBackdropWithPath:(struct CGPath *)arg1;	// IMP=0x001000000003844c
- (double)_menuTipBaseCornerRadius;	// IMP=0x001000000003843e
- (double)_menuTipCornerRadius;	// IMP=0x0010000000038430
- (double)_menuTipHeight;	// IMP=0x0010000000038422
- (double)_menuTipBase;	// IMP=0x0010000000038414
- (double)_menuCornerRadius;	// IMP=0x00100000000383f0
- (void)layoutSubviews;	// IMP=0x0010000000038264
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0010000000038212
- (struct CGSize)sizeThatFits:(struct CGSize)arg1 includeTip:(_Bool)arg2;	// IMP=0x0010000000038177
@property(nonatomic) struct CGPath *menuBorderPath;
- (void)dealloc;	// IMP=0x0010000000038077
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000037f53

@end

