//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AXDispatchTimer;

@interface SCATAutomaticDriver
{
    _Bool _forcePause;	// 8 = 0x8
    _Bool _shouldScanToNextFocusContextAfterSpeaking;	// 9 = 0x9
    AXDispatchTimer *_focusTimer;	// 16 = 0x10
    long long _currentCycleCount;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000047cdd
@property(nonatomic) _Bool shouldScanToNextFocusContextAfterSpeaking; // @synthesize shouldScanToNextFocusContextAfterSpeaking=_shouldScanToNextFocusContextAfterSpeaking;
@property(nonatomic) _Bool forcePause; // @synthesize forcePause=_forcePause;
@property(nonatomic) long long currentCycleCount; // @synthesize currentCycleCount=_currentCycleCount;
@property(retain, nonatomic) AXDispatchTimer *focusTimer; // @synthesize focusTimer=_focusTimer;
- (void)resumeAutoscanning:(_Bool)arg1;	// IMP=0x0010000000047c1c
- (void)pauseAutoscanning;	// IMP=0x0010000000047be9
- (void)actionHandlerDidCancelPendingAction:(id)arg1;	// IMP=0x0010000000047ba8
- (void)actionHandlerDidFireAction:(id)arg1;	// IMP=0x0010000000047b67
- (void)_pauseForMaximumNumberOfCycles;	// IMP=0x0010000000047ac5
- (void)_willStepToNextFocusContext:(id)arg1 inDirection:(long long)arg2;	// IMP=0x0010000000047867
- (void)_idleTimerDidFire;	// IMP=0x0010000000047838
- (void)_didWrapInDirection:(long long)arg1;	// IMP=0x00100000000477c1
- (_Bool)_handleStopAction;	// IMP=0x00100000000477ac
- (_Bool)_handleRunAction;	// IMP=0x0010000000047797
- (_Bool)_handleSelectAction;	// IMP=0x0010000000047759
- (void)outputManager:(id)arg1 didSpeakFocusContext:(id)arg2;	// IMP=0x001000000004769d
- (void)_endAutoscanning;	// IMP=0x0010000000047643
- (void)_autoscanToNextFocusContext;	// IMP=0x0010000000047529
- (void)_didTransitionToPhase:(int)arg1;	// IMP=0x00100000000474bd
@property(readonly, nonatomic) unsigned long long maxAutoscanCycles;
@property(readonly, nonatomic) double focusInterval;
- (int)driverType;	// IMP=0x001000000004731f
- (_Bool)pauseScanningForPointPickerNumberOfCycles:(unsigned long long)arg1;	// IMP=0x00100000000472d1
- (void)freezeScanning;	// IMP=0x00100000000472bf
- (void)willDrillOutOfGroup;	// IMP=0x001000000004728f
- (void)willDrillIntoGroup;	// IMP=0x001000000004725f
- (void)willFinishAsScannerDriver;	// IMP=0x0010000000047221
- (id)description;	// IMP=0x001000000004709a
- (void)dealloc;	// IMP=0x001000000004702f
- (id)initWithDelegate:(id)arg1;	// IMP=0x0010000000046f82

@end

