//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionReusableView.h>

@class MISSING_TYPE;

@interface _TtC10FitnessApp45TrophyCaseAwardDetailViewControllerHeaderView : UICollectionReusableView
{
    MISSING_TYPE *label;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x004000000060aa20
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000060a5e0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000060a4a0

@end

