//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC10FitnessApp36ActivitySharingHighlightDataProvider : _TtCs12_SwiftObject
{
    MISSING_TYPE *$defaultActor;	// 4277009103 = 0xfeedfacf
    MISSING_TYPE *_state;	// 0 = 0x0
    MISSING_TYPE *friendListSectionManager;	// 0 = 0x0
    MISSING_TYPE *healthStore;	// 0 = 0x0
    MISSING_TYPE *experienceType;	// 0 = 0x0
}

@end

