//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSFormatter.h>

@class MISSING_TYPE;

@interface _TtC10FitnessApp13PaceFormatter : NSFormatter
{
    MISSING_TYPE *componentsFormatter;	// 8 = 0x8
    MISSING_TYPE *secondsFormatter;	// 16 = 0x10
    MISSING_TYPE *minutesFormatter;	// 24 = 0x18
    MISSING_TYPE *isLocaleAware;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0040000000284810
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000002847b0
- (id)init;	// IMP=0x0010000000284630
- (id)stringForObjectValue:(id)arg1;	// IMP=0x0010000000284420

@end

