//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionViewCell.h>

@class MISSING_TYPE;

@interface _TtC10FitnessApp21TrophyCaseSectionCell : UICollectionViewCell
{
    MISSING_TYPE *tapOnAchievement;	// 8 = 0x8
    MISSING_TYPE *tapOnShowAllAchievements;	// 24 = 0x18
    MISSING_TYPE *templateUniqueName;	// 40 = 0x28
    MISSING_TYPE *stackTemplateUniqueNames;	// 56 = 0x38
    MISSING_TYPE *roundedView;	// 64 = 0x40
    MISSING_TYPE *sectionLabel;	// 72 = 0x48
    MISSING_TYPE *achievementTitleLabel;	// 80 = 0x50
    MISSING_TYPE *pillView;	// 88 = 0x58
    MISSING_TYPE *badgeImageView;	// 96 = 0x60
    MISSING_TYPE *badgeStackImageView;	// 104 = 0x68
    MISSING_TYPE *achievementCountLabel;	// 112 = 0x70
    MISSING_TYPE *showAllButton;	// 120 = 0x78
    MISSING_TYPE *sectionDescriptionLabel;	// 128 = 0x80
    MISSING_TYPE *badgeStackHeightConstraint;	// 136 = 0x88
    MISSING_TYPE *badgeImageViewWidthConstraint;	// 144 = 0x90
    MISSING_TYPE *badgeImageViewTopConstraint;	// 152 = 0x98
    MISSING_TYPE *achievementTitleLabelTopMargin;	// 160 = 0xa0
    MISSING_TYPE *badgeViewToSectionDescriptionMargin;	// 168 = 0xa8
    MISSING_TYPE *achievementTitleLabelToStackViewConstraint;	// 176 = 0xb0
    MISSING_TYPE *achievementTitleLabelToCountLabelConstraint;	// 184 = 0xb8
    MISSING_TYPE *pillViewToStackViewConstraint;	// 192 = 0xc0
    MISSING_TYPE *pillViewToCountLabelConstraint;	// 200 = 0xc8
}

- (void).cxx_destruct;	// IMP=0x004000000023f230
- (void)prepareForReuse;	// IMP=0x001000000023f1b0
- (void)didTapShowAllButton:(id)arg1;	// IMP=0x001000000023db80
- (void)didTapBadgeImageView:(id)arg1;	// IMP=0x001000000023db60
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000023c250
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000023c220

@end

