//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionViewController.h>

@class AAUIBadgeView, MISSING_TYPE;

@interface _TtC10FitnessApp35TrophyCaseAwardDetailViewController : UICollectionViewController
{
    MISSING_TYPE *achievement;	// 8 = 0x8
    MISSING_TYPE *healthStore;	// 16 = 0x10
    MISSING_TYPE *achievementDataProvider;	// 24 = 0x18
    MISSING_TYPE *badgeImageFactory;	// 64 = 0x40
    MISSING_TYPE *resourceProvider;	// 72 = 0x48
    MISSING_TYPE *formattingManager;	// 80 = 0x50
    MISSING_TYPE *localizationProvider;	// 88 = 0x58
    MISSING_TYPE *pauseRingsCoordinator;	// 96 = 0x60
    MISSING_TYPE *fitnessAppContext;	// 104 = 0x68
    MISSING_TYPE *workoutFormattingManager;	// 112 = 0x70
    MISSING_TYPE *workoutDataProvider;	// 120 = 0x78
    MISSING_TYPE *forModalPresentation;	// 128 = 0x80
    MISSING_TYPE *shouldShowCelebration;	// 129 = 0x81
    MISSING_TYPE *shouldShowEarned;	// 130 = 0x82
    MISSING_TYPE *shouldShowAssociatedWorkout;	// 131 = 0x83
    MISSING_TYPE *formatsForFriend;	// 132 = 0x84
    MISSING_TYPE *celebrationVideoContainer;	// 136 = 0x88
    MISSING_TYPE *badgeViewCell;	// 144 = 0x90
    MISSING_TYPE *associatedWorkout;	// 152 = 0x98
    MISSING_TYPE *avPlayer;	// 160 = 0xa0
    MISSING_TYPE *avPlayerLayer;	// 168 = 0xa8
    MISSING_TYPE *celebrationComplete;	// 176 = 0xb0
    MISSING_TYPE *modalBadgeFlipStarted;	// 177 = 0xb1
    MISSING_TYPE *didAppear;	// 178 = 0xb2
    MISSING_TYPE *needToAnimatedBadgeView;	// 179 = 0xb3
    MISSING_TYPE *sharingImage;	// 184 = 0xb8
    MISSING_TYPE *sharingText;	// 192 = 0xc0
    MISSING_TYPE *badgeView;	// 208 = 0xd0
    MISSING_TYPE *friendListManager;	// 216 = 0xd8
    MISSING_TYPE *friendsWithAchievement;	// 224 = 0xe0
}

- (void).cxx_destruct;	// IMP=0x002000000060ae30
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x001000000060d320
- (id)initWithCollectionViewLayout:(id)arg1;	// IMP=0x001000000060d2f0
- (void)appWillResignActive:(id)arg1;	// IMP=0x001000000060bbe0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x001000000060bbb0
- (void)viewDidLayoutSubviews;	// IMP=0x001000000060b7f0
- (void)viewWillLayoutSubviews;	// IMP=0x001000000060b7c0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x001000000060b710
- (void)viewDidLoad;	// IMP=0x001000000060b620
- (void)dealloc;	// IMP=0x001000000060ad70
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000060aca0
- (id)initWithAchievement:(id)arg1 healthStore:(id)arg2 friendListManager:(id)arg3 achievementDataProvider:(id)arg4 badgeImageFactory:(id)arg5 resourceProvider:(id)arg6 formattingManager:(id)arg7 localizationProvider:(id)arg8 pauseRingsCoordinator:(id)arg9 fitnessAppContext:(id)arg10 workoutFormattingManager:(id)arg11 workoutDataProvider:(id)arg12 forModalPresentation:(_Bool)arg13 shouldShowCelebration:(_Bool)arg14 shouldShowEarned:(_Bool)arg15 shouldShowAssociatedWorkout:(_Bool)arg16;	// IMP=0x001000000060ab00
@property(nonatomic, readonly) AAUIBadgeView *badgeView; // @synthesize badgeView;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x001000000060dac0
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x001000000060da20
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x001000000060d970
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x001000000060d3e0
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x001000000060d3d0
- (void)placeBadgeViewInContainer;	// IMP=0x001000000060ded0
@property(nonatomic, readonly) struct CGRect badgeFrame;
- (id)activityViewControllerLinkPresentationMetadata:(id)arg1;	// IMP=0x001000000060dfc0
- (id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;	// IMP=0x001000000060dfb0
- (id)activityViewControllerPlaceholderItem:(id)arg1;	// IMP=0x001000000060df70
- (void)shareTapped:(id)arg1;	// IMP=0x001000000060df20
- (void)doneTapped:(id)arg1;	// IMP=0x001000000060df00
- (void)playerFinished:(id)arg1;	// IMP=0x001000000060e020

@end

