//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ActivityRingsUI/ARUIMetricColors.h>

@interface ARUIMetricColors (FitnessApp)
+ (id)mindfulnessColors;	// IMP=0x00200000003ecbe0
+ (id)raceBehindColors;	// IMP=0x00100000003ecbc0
+ (id)raceAheadColors;	// IMP=0x00100000003ecba0
+ (id)raceColors;	// IMP=0x00100000003ed890
+ (id)intervalColors;	// IMP=0x00100000003ecb80
+ (id)pacerColors;	// IMP=0x00100000003ecb60
+ (id)metricColorsForWorkout:(id)arg1;	// IMP=0x00100000003ecb20
@end

