//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class HKUnit, UIColor;

@interface CHASActivitySetupGoalViewConfiguration : NSObject
{
    UIColor *_goalColor;	// 8 = 0x8
    double _unitTextYOffset;	// 16 = 0x10
    CDUnknownBlockType _goalValueStringFormatter;	// 24 = 0x18
    CDUnknownBlockType _goalUnitStringFormatter;	// 32 = 0x20
    HKUnit *_unit;	// 40 = 0x28
    double _minimumValue;	// 48 = 0x30
    double _maximumValue;	// 56 = 0x38
    double _valueIncrement;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00200000000582b3
@property(nonatomic) double valueIncrement; // @synthesize valueIncrement=_valueIncrement;
@property(nonatomic) double maximumValue; // @synthesize maximumValue=_maximumValue;
@property(nonatomic) double minimumValue; // @synthesize minimumValue=_minimumValue;
@property(retain, nonatomic) HKUnit *unit; // @synthesize unit=_unit;
@property(copy, nonatomic) CDUnknownBlockType goalUnitStringFormatter; // @synthesize goalUnitStringFormatter=_goalUnitStringFormatter;
@property(copy, nonatomic) CDUnknownBlockType goalValueStringFormatter; // @synthesize goalValueStringFormatter=_goalValueStringFormatter;
@property(nonatomic) double unitTextYOffset; // @synthesize unitTextYOffset=_unitTextYOffset;
@property(retain, nonatomic) UIColor *goalColor; // @synthesize goalColor=_goalColor;

@end

