//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class ASCompetitionScoreView, ASCompetitionScoreViewConfiguration, ASFriend;

@interface CHFriendDetailCompetitionScoreCell : UIView
{
    ASCompetitionScoreView *_scoreView;	// 8 = 0x8
    ASCompetitionScoreViewConfiguration *_configuration;	// 16 = 0x10
    ASFriend *_friend;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000a152b
- (double)preferredHeightForFriend:(id)arg1;	// IMP=0x00100000000a1501
- (void)setFriend:(id)arg1 competition:(id)arg2;	// IMP=0x00100000000a14e4
- (void)layoutSubviews;	// IMP=0x00100000000a146f
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000000a139d

@end

