//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class AAUIAchievementDetailTransitionAnimator, AAUIAchievementsDataProvider, AAUIBadgeImageFactory, ACHAchievement, ACHAchievementLocalizationProvider, CHAchievementsDataSource, CHAchievementsRecentAndRelevantDataSource, FIUIFormattingManager, NSString, UIActivityIndicatorView, UICollectionView, UIView, _HKWheelchairUseCharacteristicCache;
@protocol CHTrophyCaseViewControllerDelegate;

@interface CHTrophyCaseViewController : UIViewController
{
    _Bool _observerSetupComplete;	// 8 = 0x8
    _Bool _initialAchievementPresented;	// 9 = 0x9
    _Bool _shouldShowCelebration;	// 10 = 0xa
    id <CHTrophyCaseViewControllerDelegate> _delegate;	// 16 = 0x10
    AAUIAchievementsDataProvider *_dataProvider;	// 24 = 0x18
    _HKWheelchairUseCharacteristicCache *_wheelchairUseCache;	// 32 = 0x20
    UICollectionView *_mainCollectionView;	// 40 = 0x28
    UICollectionView *_recentAndRelevantCollectionView;	// 48 = 0x30
    CHAchievementsDataSource *_mainSectionDataSource;	// 56 = 0x38
    CHAchievementsRecentAndRelevantDataSource *_recentAndRelevantDataSource;	// 64 = 0x40
    AAUIAchievementDetailTransitionAnimator *_transitionAnimator;	// 72 = 0x48
    UIViewController *_transitionAnimatorFromViewController;	// 80 = 0x50
    UIView *_overlayView;	// 88 = 0x58
    AAUIBadgeImageFactory *_badgeImageFactory;	// 96 = 0x60
    FIUIFormattingManager *_formattingManager;	// 104 = 0x68
    ACHAchievementLocalizationProvider *_localizationProvider;	// 112 = 0x70
    ACHAchievement *_initialAchievement;	// 120 = 0x78
    UIView *_loadingView;	// 128 = 0x80
    UIActivityIndicatorView *_spinner;	// 136 = 0x88
}

- (void).cxx_destruct;	// IMP=0x00200000000999d0
@property(nonatomic) _Bool shouldShowCelebration; // @synthesize shouldShowCelebration=_shouldShowCelebration;
@property(nonatomic) _Bool initialAchievementPresented; // @synthesize initialAchievementPresented=_initialAchievementPresented;
@property(nonatomic) _Bool observerSetupComplete; // @synthesize observerSetupComplete=_observerSetupComplete;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) ACHAchievement *initialAchievement; // @synthesize initialAchievement=_initialAchievement;
@property(retain, nonatomic) ACHAchievementLocalizationProvider *localizationProvider; // @synthesize localizationProvider=_localizationProvider;
@property(retain, nonatomic) FIUIFormattingManager *formattingManager; // @synthesize formattingManager=_formattingManager;
@property(retain, nonatomic) AAUIBadgeImageFactory *badgeImageFactory; // @synthesize badgeImageFactory=_badgeImageFactory;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) UIViewController *transitionAnimatorFromViewController; // @synthesize transitionAnimatorFromViewController=_transitionAnimatorFromViewController;
@property(retain, nonatomic) AAUIAchievementDetailTransitionAnimator *transitionAnimator; // @synthesize transitionAnimator=_transitionAnimator;
@property(retain, nonatomic) CHAchievementsRecentAndRelevantDataSource *recentAndRelevantDataSource; // @synthesize recentAndRelevantDataSource=_recentAndRelevantDataSource;
@property(retain, nonatomic) CHAchievementsDataSource *mainSectionDataSource; // @synthesize mainSectionDataSource=_mainSectionDataSource;
@property(retain, nonatomic) UICollectionView *recentAndRelevantCollectionView; // @synthesize recentAndRelevantCollectionView=_recentAndRelevantCollectionView;
@property(retain, nonatomic) UICollectionView *mainCollectionView; // @synthesize mainCollectionView=_mainCollectionView;
@property(retain, nonatomic) _HKWheelchairUseCharacteristicCache *wheelchairUseCache; // @synthesize wheelchairUseCache=_wheelchairUseCache;
@property(retain, nonatomic) AAUIAchievementsDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
@property(nonatomic) __weak id <CHTrophyCaseViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)wheelchairUseCharacteristicCache:(id)arg1 wheelchairUsageDidChange:(_Bool)arg2;	// IMP=0x00100000000996e2
- (void)achievementsDataProviderDidFinishInitialLoad:(id)arg1;	// IMP=0x00100000000994f1
- (_Bool)_navigationControllerShouldUseBuiltinInteractionController:(id)arg1;	// IMP=0x0010000000099472
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;	// IMP=0x0010000000099382
- (void)_presentInitialAchievementIfNeeded;	// IMP=0x001000000009921b
- (void)detachPalette;	// IMP=0x001000000009917f
- (void)presentDetailForAchievement:(id)arg1 badgeRect:(struct CGRect)arg2 conversionView:(id)arg3 cell:(id)arg4;	// IMP=0x0010000000098eb1
- (void)unitPreferencesDidChange:(id)arg1;	// IMP=0x0010000000098e30
- (void)dealloc;	// IMP=0x0010000000098dc2
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0010000000098d35
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000098c3a
- (void)viewDidLoad;	// IMP=0x001000000009789a
- (id)initWithBadgeImageFactory:(id)arg1 formattingManager:(id)arg2 localizationProvider:(id)arg3 initialAchievement:(id)arg4 shouldShowCelebration:(_Bool)arg5;	// IMP=0x0010000000097707

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

