//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ContactsUI/CNContactViewController.h>

@interface _TtC9AirDropUI29CNSecureContactViewController : CNContactViewController
{
}

+ (_Bool)_isSecureForRemoteViewService;	// IMP=0x0020000000083070
- (id)initWithCoder:(id)arg1;	// IMP=0x0040000000083130
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000083090
- (_Bool)_canShowWhileLocked;	// IMP=0x0010000000083080

@end

