//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class CRFileReceiver, NSDictionary;

@protocol CRStatisticsStreamReceiving <NSObject>
- (void)fileReceiver:(CRFileReceiver *)arg1 didReceiveStatistics:(NSDictionary *)arg2;
@end

