//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray, NSString;

@interface CPLCKFeatureAvailabilityResponse : PBCodable
{
    NSMutableArray *_features;	// 8 = 0x8
}

+ (Class)featuresType;	// IMP=0x002000000003d0cb
- (void).cxx_destruct;	// IMP=0x002000000003db45
@property(retain, nonatomic) NSMutableArray *features; // @synthesize features=_features;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000003d9e7
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000003d93a
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000003d776
- (void)copyTo:(id)arg1;	// IMP=0x001000000003d6b1
- (void)writeTo:(id)arg1;	// IMP=0x001000000003d57b
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000003d56e
- (id)dictionaryRepresentation;	// IMP=0x001000000003d18b
@property(readonly, copy) NSString *description;
- (id)featuresAtIndex:(unsigned long long)arg1;	// IMP=0x001000000003d0ae
- (unsigned long long)featuresCount;	// IMP=0x001000000003d091
- (void)addFeatures:(id)arg1;	// IMP=0x001000000003d027
- (void)clearFeatures;	// IMP=0x001000000003d00a
- (void)substituteRecordTransports:(id)arg1;	// IMP=0x0010000000042a03
- (id)extractRecordTransports;	// IMP=0x00100000000429f6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly) Class superclass;

@end

