//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MFMailMessageLibrary, MFMailboxUid;
@protocol MFDeviceStorage, MFMailboxMessageBodyProcessorDelegate, MessageBodyLoader;

@interface MFMailboxMessageBodyProcessor : NSObject
{
    id <MFMailboxMessageBodyProcessorDelegate> _delegate;	// 8 = 0x8
    MFMailboxUid *_mailbox;	// 16 = 0x10
    id <MFDeviceStorage> _deviceStorage;	// 24 = 0x18
    unsigned long long _batchSize;	// 32 = 0x20
    id <MessageBodyLoader> _messageBodyLoader;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0020000000088e00
@property(readonly, nonatomic) id <MessageBodyLoader> messageBodyLoader; // @synthesize messageBodyLoader=_messageBodyLoader;
@property(readonly, nonatomic) unsigned long long batchSize; // @synthesize batchSize=_batchSize;
@property(readonly, nonatomic) id <MFDeviceStorage> deviceStorage; // @synthesize deviceStorage=_deviceStorage;
@property(readonly, nonatomic) MFMailboxUid *mailbox; // @synthesize mailbox=_mailbox;
@property(nonatomic) __weak id <MFMailboxMessageBodyProcessorDelegate> delegate; // @synthesize delegate=_delegate;
- (long long)_spaceIncreaseUrgencyForMessage:(id)arg1;	// IMP=0x0010000000088c6a
- (long long)_freeSpaceGuidanceForSpaceIncreaseForMessage:(id)arg1;	// IMP=0x0010000000088bb0
- (_Bool)_shouldDownloadMessage:(id)arg1;	// IMP=0x0010000000088b97
- (_Bool)_shouldTryToDownloadMessage:(id)arg1;	// IMP=0x0010000000088aea
- (_Bool)_shouldContinueProcessing;	// IMP=0x0010000000088a70
- (void)_enumerateMessagesToDownload:(CDUnknownBlockType)arg1;	// IMP=0x0010000000088413
@property(readonly, nonatomic) MFMailMessageLibrary *library;
- (void)runSynchronously;	// IMP=0x0010000000087fca
- (id)initWithMailbox:(id)arg1 batchSize:(unsigned long long)arg2 deviceStorage:(id)arg3;	// IMP=0x0010000000087d94

@end

