//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ACAccount, _TtC9appstored6LogKey;

@interface _TtC9appstored23AccountCacheCoordinator : NSObject
{
}

- (id)init;	// IMP=0x004000000009a720
- (void)oneAccountDSID:(ACAccount *)arg1 logKey:(_TtC9appstored6LogKey *)arg2 completionHandler:(void (^)(NSNumber *))arg3;	// IMP=0x001000000009a480

@end

