//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AppInstallsDatabaseStore
{
}

+ (_Bool)createOrMigrateStoreUsingSchema:(id)arg1;	// IMP=0x0020000000295c3f
+ (id)storeDescriptor;	// IMP=0x0010000000295be6
+ (id)activeInstallForBundleID:(id)arg1;	// IMP=0x0010000000035390
- (void)readUsingSession:(CDUnknownBlockType)arg1;	// IMP=0x0040000000296cdd
- (void)modifyUsingTransaction:(CDUnknownBlockType)arg1;	// IMP=0x0010000000295c53

@end

