//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AsyncTask
{
    _Bool _executing;	// 8 = 0x8
    _Bool _finished;	// 9 = 0x9
}

- (void)completeWithSuccess;	// IMP=0x0020000000116d91
- (void)completeWithError:(id)arg1;	// IMP=0x0010000000116cad
- (void)mainWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000116c9d
- (void)main;	// IMP=0x0010000000116c25
- (void)start;	// IMP=0x0010000000116b92
- (_Bool)isFinished;	// IMP=0x0010000000116b4e
- (_Bool)isExecuting;	// IMP=0x0010000000116b0a
- (_Bool)isAsynchronous;	// IMP=0x0010000000116b02

@end

