//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MigratorMiscellaneousTask
{
}

- (void)main;	// IMP=0x00400000001af848
- (id)migratorType;	// IMP=0x00100000001af837
- (id)copyConfiguration;	// IMP=0x00100000001af817
- (id)initWithConfiguration:(id)arg1;	// IMP=0x00100000001af7e8

@end

