//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC15assessmentagent39AEAActiveRestrictionUUIDFetchingService : NSObject
{
    MISSING_TYPE *xpc;	// 8 = 0x8
    MISSING_TYPE *sessionManager;	// 16 = 0x10
    MISSING_TYPE *XPCListener;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000188d0
- (id)init;	// IMP=0x0010000000018a10
- (void)dealloc;	// IMP=0x0010000000018870
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0010000000018b10
- (void)fetchSetOfActiveRestrictionUUIDsWithClientType:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000018b80

@end

