//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UINavigationController.h>

@class DDAction, EKICSPreviewController, NSString;
@protocol DDRemoteActionPresenter;

@interface DDEventAddViewController : UINavigationController
{
    id <DDRemoteActionPresenter> _proxy;	// 8 = 0x8
    DDAction *_action;	// 16 = 0x10
    EKICSPreviewController *_eventAddController;	// 24 = 0x18
}

+ (id)_exportedInterface;	// IMP=0x00200000000088f0
+ (id)_remoteViewControllerInterface;	// IMP=0x00100000000088b0
- (void).cxx_destruct;	// IMP=0x00200000000096f0
@property(retain) DDAction *action; // @synthesize action=_action;
- (void)icsPreviewControllerWantsDismissal:(id)arg1;	// IMP=0x0010000000009630
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x0010000000009360
- (void)doneWithAddingEvent;	// IMP=0x00100000000092f0
- (void)adaptForPresentationInPopover:(_Bool)arg1;	// IMP=0x00100000000092d0
- (void)setCancellable:(_Bool)arg1;	// IMP=0x0010000000009270
- (void)prepareForAction:(id)arg1;	// IMP=0x0010000000008930

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

