//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@protocol _BMRapportActivation <NSObject>
@property(copy, nonatomic) CDUnknownBlockType invalidationHandler;
- (void)invalidate;
- (void)activateWithCompletion:(void (^)(NSError *))arg1;
@end

