//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BMSyncDatabase, BMSyncDevicePeerStatusTracker, BMSyncSessionMetricsCollector, NSDictionary;

@interface BMDistributedSyncMultiStreamManager : NSObject
{
    BMSyncDatabase *_accountDatabase;	// 8 = 0x8
    NSDictionary *_distributedSyncManagers;	// 16 = 0x10
    BMSyncDevicePeerStatusTracker *_peerStatusTracker;	// 24 = 0x18
    BMSyncSessionMetricsCollector *_metricsCollector;	// 32 = 0x20
}

+ (id)multiStreamManagerWithPrimaryDatabase:(id)arg1 account:(id)arg2 queue:(id)arg3;	// IMP=0x004000000003a1bc
- (void).cxx_destruct;	// IMP=0x002000000003c02c
@property(retain, nonatomic) BMSyncSessionMetricsCollector *metricsCollector; // @synthesize metricsCollector=_metricsCollector;
@property(readonly, nonatomic) BMSyncDevicePeerStatusTracker *peerStatusTracker; // @synthesize peerStatusTracker=_peerStatusTracker;
@property(readonly, nonatomic) NSDictionary *distributedSyncManagers; // @synthesize distributedSyncManagers=_distributedSyncManagers;
- (_Bool)supportsSyncingWithPlatform:(long long)arg1 overTransport:(unsigned long long)arg2 inDirection:(unsigned long long)arg3;	// IMP=0x001000000003bdcd
- (id)deletedLocationsForTransportType:(unsigned long long)arg1;	// IMP=0x001000000003b9f5
- (void)mergeAtomBatches:(id)arg1 deletedLocations:(id)arg2 sessionContext:(id)arg3;	// IMP=0x001000000003b56f
- (id)atomBatchesForChangesSinceClockVector:(id)arg1 targetPlatform:(long long)arg2 transportType:(unsigned long long)arg3 direction:(unsigned long long)arg4 ckFormatVersion:(unsigned char)arg5 chunker:(id)arg6;	// IMP=0x001000000003b06c
- (id)rangeClockVectorForStreamsSupportingTransportType:(unsigned long long)arg1 direction:(unsigned long long)arg2 device:(id)arg3;	// IMP=0x001000000003ac49
- (id)clockVectorForStreamsSupportingTransportType:(unsigned long long)arg1 direction:(unsigned long long)arg2 device:(id)arg3;	// IMP=0x001000000003a826
- (void)dealloc;	// IMP=0x001000000003a7e4
- (id)initWithDistributedSyncManagers:(id)arg1 peerStatusTracker:(id)arg2 accountDatabase:(id)arg3;	// IMP=0x001000000003a71c

@end

