//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface UAClientController
{
}

- (double)intervalToDelaySuspensionOfAdvertisingForItem:(id)arg1;	// IMP=0x004000000002ba5c
- (id)recentEligibleItemsInOrder:(double)arg1;	// IMP=0x001000000002ba54
- (id)eligibleAdvertiseableItemsInOrder;	// IMP=0x001000000002b9cc
- (id)userActivityInfoForUUID:(id)arg1;	// IMP=0x001000000002b7f9
- (id)items;	// IMP=0x001000000002b7f1
- (id)initWithManager:(id)arg1 name:(id)arg2;	// IMP=0x001000000002b7c2

@end

