//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CARSettingsCellSpecifier, CARSettingsGroupCellSpecifier, CRSSiriPreferences, NSArray, NSString;

@interface CARAnnounceNotificationsMuteOptionsPanel
{
    CARSettingsCellSpecifier *_cellSpecifier;	// 8 = 0x8
    NSArray *_modes;	// 16 = 0x10
    CARSettingsGroupCellSpecifier *_groupSpecifier;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000236da
@property(readonly, nonatomic) CARSettingsGroupCellSpecifier *groupSpecifier; // @synthesize groupSpecifier=_groupSpecifier;
@property(readonly, nonatomic) NSArray *modes; // @synthesize modes=_modes;
- (long long)_userNotificationSettingForAnnounceType:(long long)arg1;	// IMP=0x001000000002369e
- (id)_modeForSiriPreferences:(id)arg1;	// IMP=0x0010000000023529
- (void)_updateSettingsForMode:(id)arg1;	// IMP=0x00100000000233bd
- (void)_updateCurrentMode;	// IMP=0x00100000000232ea
- (void)preferences:(id)arg1 carPlayAnnounceEnablementTypeChanged:(long long)arg2;	// IMP=0x001000000002326c
@property(readonly, nonatomic) CRSSiriPreferences *siriPreferences;
- (id)specifierSections;	// IMP=0x0010000000023070
- (id)cellSpecifier;	// IMP=0x0010000000022ef8
- (id)initWithPanelController:(id)arg1;	// IMP=0x0010000000022c6a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

