//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLOdometerNotifierAdapter
{
}

+ (_Bool)isSupported;	// IMP=0x002000000026580c
+ (id)getSilo;	// IMP=0x00100000002655f7
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000002655de
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000265581
- (void)unregisterForCyclingWorkoutDistanceUpdates:(byref id)arg1;	// IMP=0x0020000000265a88
- (void)registerForCyclingWorkoutDistanceUpdates:(byref id)arg1;	// IMP=0x0010000000265a5a
- (void)updatePhoneWorkoutElevationSubscription:(_Bool)arg1;	// IMP=0x0010000000265a2e
- (void)querySignificantElevationDeltaFromDate:(id)arg1 toDate:(id)arg2 withReply:(CDUnknownBlockType)arg3;	// IMP=0x0010000000265852
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00100000002657e4
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00100000002657b7
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x001000000026578f
- (void *)adaptee;	// IMP=0x001000000026575c
- (void)endService;	// IMP=0x0010000000265741
- (void)beginService;	// IMP=0x0010000000265690
- (id)init;	// IMP=0x0010000000265653

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

