//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableDictionary;
@protocol CLIntersiloUniverse, CLWorkoutRecordingDelegate;

@interface CLWMHeadsetDeviceMotion
{
    struct unique_ptr<CLMotionNotifier::Dispatcher, std::default_delete<CLMotionNotifier::Dispatcher>> _accessoryDeviceMotionDispatcher;	// 8 = 0x8
    struct unique_ptr<CLMotionNotifier::Dispatcher, std::default_delete<CLMotionNotifier::Dispatcher>> _accessoryDeviceMotionConfigDispatcher;	// 16 = 0x10
    shared_ptr_da0ccc6f _writer;	// 24 = 0x18
    id <CLWorkoutRecordingDelegate> _delegate;	// 40 = 0x28
    NSMutableDictionary *_metadata;	// 48 = 0x30
    id <CLIntersiloUniverse> _universe;	// 56 = 0x38
    double _headsetDMupdateInterval;	// 64 = 0x40
    _Bool _lowLatencyMode;	// 72 = 0x48
    unsigned int _dmBufferSize;	// 76 = 0x4c
    int _sampleCount;	// 80 = 0x50
}

- (id).cxx_construct;	// IMP=0x002000000134c5be
- (void).cxx_destruct;	// IMP=0x001000000134c55d
- (void)dealloc;	// IMP=0x001000000134c3a3
- (id)metadata;	// IMP=0x001000000134c37e
- (void)setWriter:(shared_ptr_da0ccc6f)arg1;	// IMP=0x001000000134c36a
- (int)getSampleCount;	// IMP=0x001000000134c35a
- (void)onAccessoryDeviceMotionConfig:(const void *)arg1 buffersize:(unsigned int)arg2;	// IMP=0x001000000134c19c
- (void)onAccessoryDeviceMotionData:(const void *)arg1 buffersize:(unsigned int)arg2;	// IMP=0x001000000134bd50
- (void)teardownListeners;	// IMP=0x001000000134b9ed
- (void)setupListener;	// IMP=0x001000000134b599
- (id)initWithDelegate:(id)arg1 universeCopy:(id)arg2 settings:(struct SettingStructure)arg3;	// IMP=0x001000000134b4d6

@end

