//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class SSSDebugScreenshotMangerView;

@interface SSSDittoRemoteView : UIView
{
    SSSDebugScreenshotMangerView *_debugScreenshotManagerView;	// 8 = 0x8
    _Bool _acceptsTouches;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000604b4
@property(nonatomic) _Bool acceptsTouches; // @synthesize acceptsTouches=_acceptsTouches;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0010000000060408
- (void)layoutSubviews;	// IMP=0x0010000000060356
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000000602cc

@end

