//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface SSSScreenshotItemProviderImage
{
}

- (id)activityViewControllerSuggestionAssetLocalIdentifier:(id)arg1;	// IMP=0x0020000000003758
- (id)imageData;	// IMP=0x00100000000036bd
- (id)activityViewController:(id)arg1 thumbnailImageDataForActivityType:(id)arg2 suggestedSize:(struct CGSize)arg3;	// IMP=0x00100000000036ab
- (id)activityViewController:(id)arg1 attachmentNameForActivityType:(id)arg2;	// IMP=0x0010000000003654
- (id)activityViewController:(id)arg1 subjectForActivityType:(id)arg2;	// IMP=0x0010000000003642
- (id)activityViewControllerLinkMetadata:(id)arg1;	// IMP=0x001000000000316a
- (id)item;	// IMP=0x00100000000030f0
- (id)placeholderItemForScreenshot:(id)arg1;	// IMP=0x001000000000309d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

