//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, STDeviceID, STUserID;

@interface STCheckinContent : NSObject
{
    STUserID *_userID;	// 8 = 0x8
    STDeviceID *_deviceID;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000011dd6
+ (long long)contentType;	// IMP=0x0010000000011b90
- (void).cxx_destruct;	// IMP=0x0020000000012050
@property(readonly, copy) STDeviceID *deviceID; // @synthesize deviceID=_deviceID;
@property(readonly, copy) STUserID *userID; // @synthesize userID=_userID;
@property(readonly) unsigned long long hash;
- (_Bool)isEqualToCheckinContent:(id)arg1;	// IMP=0x0010000000011e8e
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000011e2b
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000011dde
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000011d28
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000011c66
@property(readonly, copy) NSString *description;
- (id)initWithUserID:(id)arg1 deviceID:(id)arg2;	// IMP=0x0010000000011ad9

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly) Class superclass;

@end

