//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface STEyeReliefClientShim : NSObject
{
}

+ (_Bool)toggleDistanceSampling;	// IMP=0x00400000000174be
+ (_Bool)isScreenDistanceEnabled;	// IMP=0x00100000000174b6

@end

