//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BKDisplayAnnotationDisplayController, BKNamespaceNode, CAContext, CADisplay, CALayer, NSMutableArray, NSString;
@protocol BSInvalidatable;

@interface BKDisplayAnnotationController : NSObject
{
    BKDisplayAnnotationDisplayController *_displayController;	// 8 = 0x8
    id <BSInvalidatable> _displayObserver;	// 16 = 0x10
    id <BSInvalidatable> _orientationObserver;	// 24 = 0x18
    struct os_unfair_lock_s _lock;	// 32 = 0x20
    long long _lock_externalReferenceCount;	// 40 = 0x28
    NSMutableArray *_annotations;	// 48 = 0x30
    BKNamespaceNode *_rootNode;	// 56 = 0x38
    CADisplay *_display;	// 64 = 0x40
    CAContext *_context;	// 72 = 0x48
    CALayer *_rootLayer;	// 80 = 0x50
    CALayer *_transformLayer;	// 88 = 0x58
    CALayer *_referenceSpaceLayer;	// 96 = 0x60
}

+ (void)performBlockForEveryAnnotationController:(CDUnknownBlockType)arg1;	// IMP=0x0020000000070c84
+ (id)annotationControllerForDisplay:(id)arg1;	// IMP=0x0010000000070855
- (void).cxx_destruct;	// IMP=0x002000000006faac
@property(retain, nonatomic) CALayer *referenceSpaceLayer; // @synthesize referenceSpaceLayer=_referenceSpaceLayer;
@property(retain, nonatomic) CALayer *transformLayer; // @synthesize transformLayer=_transformLayer;
@property(retain, nonatomic) CALayer *rootLayer; // @synthesize rootLayer=_rootLayer;
@property(retain, nonatomic) CAContext *context; // @synthesize context=_context;
@property(retain, nonatomic) CADisplay *display; // @synthesize display=_display;
- (void)_configureReferenceSpaceLayerTransformWithScale:(double)arg1;	// IMP=0x001000000006f759
- (void)_lock_locationDidChanges;	// IMP=0x001000000006f724
- (void)_lock_removeAnnotation:(id)arg1;	// IMP=0x001000000006f6a6
- (void)_lock_CATransaction:(CDUnknownBlockType)arg1;	// IMP=0x001000000006f636
- (id)_lock_supernodeForRenderingAtKeyPath:(id)arg1;	// IMP=0x001000000006f518
- (void)performSynchronizedWithCATransaction:(CDUnknownBlockType)arg1;	// IMP=0x001000000006f46c
- (void)performSynchronized:(CDUnknownBlockType)arg1;	// IMP=0x001000000006f42e
- (void)_lock_tearDownLayerTree;	// IMP=0x001000000006f3b5
- (void)_lock_setupLayerTree;	// IMP=0x001000000006ec0f
- (void)_lock_updateLayerTree;	// IMP=0x001000000006eb5d
- (void)monitor:(id)arg1 displayDidBecomeInactive:(id)arg2;	// IMP=0x001000000006eaf1
- (void)monitor:(id)arg1 displayDidBecomeActive:(id)arg2;	// IMP=0x001000000006ea5c
- (void)monitor:(id)arg1 activeDisplayPropertiesDidChange:(id)arg2;	// IMP=0x001000000006e9c7
- (void)orientationManager:(id)arg1 deviceOrientationMayHaveChanged:(long long)arg2 changeSource:(long long)arg3 isDeviceOrientationLocked:(_Bool)arg4;	// IMP=0x001000000006e97b
- (void)removeAnnotationsForKeyPath:(id)arg1 afterDelay:(double)arg2 queue:(id)arg3;	// IMP=0x001000000006e826
- (void)removeAnnotationsForKeyPath:(id)arg1;	// IMP=0x001000000006e80f
- (void)setAnnotation:(id)arg1 forKeyPath:(id)arg2;	// IMP=0x001000000006e758
- (id)allAnnotationsForKeyPath:(id)arg1;	// IMP=0x001000000006e676
- (id)annotationForKeyPath:(id)arg1;	// IMP=0x001000000006e562
- (void)_lock_invalidate;	// IMP=0x001000000006e4de
- (void)invalidate;	// IMP=0x001000000006e4ac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

