//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BKDisplayController, BKIOHIDService, BKIOHIDServicePersistentPropertyController, BKIOHIDServiceSimplePersistentPropertySupport, BKTouchEventServer, BSContinuousMachTimer, BSProcessDeathWatcher, NSArray, NSMutableDictionary, NSMutableOrderedSet, NSString;
@protocol BKHIDEventHitTestDispatcher, BSInvalidatable, OS_dispatch_queue;

@interface BKHIDDirectTouchEventProcessor : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    BKTouchEventServer *_touchEventServer;	// 16 = 0x10
    id <BKHIDEventHitTestDispatcher> _dispatcher;	// 24 = 0x18
    BKIOHIDServicePersistentPropertyController *_persistentPropertyController;	// 32 = 0x20
    NSArray *_matchers;	// 40 = 0x28
    BKIOHIDServiceSimplePersistentPropertySupport *_pencilOpaqueTouchPersistentPropertySupport;	// 48 = 0x30
    BKIOHIDService *_queue_mainDisplayDigitizerService;	// 56 = 0x38
    BKIOHIDService *_queue_mainDisplayAOPDigitizerService;	// 64 = 0x40
    BKIOHIDService *_queue_mainDisplayPencilDigitizerService;	// 72 = 0x48
    double _queue_startMainDisplayDigitizerMatchingTime;	// 80 = 0x50
    BSContinuousMachTimer *_queue_mainDisplayDigitizerSentinelTimer;	// 88 = 0x58
    long long _queue_interfaceOrientation;	// 96 = 0x60
    long long _queue_activeModifiers;	// 104 = 0x68
    id <BSInvalidatable> _globalKeyboardObserver;	// 112 = 0x70
    NSMutableDictionary *_queue_perDisplayInfo;	// 120 = 0x78
    NSMutableDictionary *_queue_referenceToTouchStreamClient;	// 128 = 0x80
    unsigned int _queue_previousVendedTouchStreamReference;	// 136 = 0x88
    NSMutableDictionary *_queue_slotIDToSlotRecord;	// 144 = 0x90
    NSMutableOrderedSet *_queue_touchEnterSlotIDs;	// 152 = 0x98
    BSProcessDeathWatcher *_queue_zoomDeathWatcher;	// 160 = 0xa0
    NSArray *_queue_zoomExcludedContextIDs;	// 168 = 0xa8
    long long _queue_zoomExcludedContextsSeed;	// 176 = 0xb0
    struct os_unfair_lock_s _lock;	// 184 = 0xb8
    _Bool _lock_shouldIgnoreTouchesWhileObjectInProximity;	// 188 = 0xbc
    BKDisplayController *_defaultDisplayController;	// 192 = 0xc0
}

+ (id)digitizerMatchingDictionaries;	// IMP=0x002000000004ffff
- (void).cxx_destruct;	// IMP=0x002000000004a5b9
- (id)_queue_servicesMatchingSenderDescriptor:(id)arg1;	// IMP=0x001000000004a222
- (void)_queue_addServicesMatchingSenderDescriptor:(id)arg1 inPerDisplayInfo:(id)arg2 toArray:(id)arg3;	// IMP=0x001000000004a002
- (id)_determineServiceForEvent:(struct __IOHIDEvent *)arg1 sender:(id)arg2 fromTouchPad:(_Bool *)arg3;	// IMP=0x0010000000049c9d
- (void)_handleDirectTouchEvent:(struct __IOHIDEvent *)arg1 service:(id)arg2;	// IMP=0x0010000000049a98
- (id)_queue_contextIDsToIgnoreForZoomSenders;	// IMP=0x0010000000049a74
- (id)_queue_slotRecordForSlotID:(unsigned int)arg1;	// IMP=0x00100000000499dd
- (_Bool)_queue_hasTouchEnterSlots;	// IMP=0x00100000000499bd
- (id)_queue_applyCachedPropertiesToMultitouchService:(id)arg1;	// IMP=0x00100000000496d1
- (id)_queue_touchStreamClientForReference:(unsigned int)arg1;	// IMP=0x0010000000049643
- (unsigned int)_queue_addTouchStreamClient:(id)arg1 toDisplayUUID:(id)arg2 versionedPID:(long long)arg3;	// IMP=0x001000000004925c
- (id)_queue_touchStreamInfoForDisplayUUID:(id)arg1 createIfNeeded:(_Bool)arg2;	// IMP=0x001000000004911e
- (id)_queue_digitizerStateForService:(id)arg1;	// IMP=0x0010000000048ffe
- (id)_queue_addDigitizerStateForService:(id)arg1;	// IMP=0x0010000000048555
- (id)_queue_displayInfoForDisplay:(id)arg1 createIfNeeded:(_Bool)arg2;	// IMP=0x0010000000048397
- (void)globalKeyboardModifiersDidChange:(long long)arg1;	// IMP=0x0010000000048348
- (void)serviceDidDisappear:(id)arg1;	// IMP=0x0010000000047ff1
- (void)matcher:(id)arg1 servicesDidMatch:(id)arg2;	// IMP=0x001000000004795d
- (long long)processEvent:(inout struct __IOHIDEvent **)arg1 sender:(id)arg2 dispatcher:(id)arg3;	// IMP=0x001000000004762b
- (long long)setPersistentProperties:(id)arg1 forServicesMatchingDescriptor:(id)arg2;	// IMP=0x00100000000470a8
- (id)_persistentPropertyKeyDenylist;	// IMP=0x0010000000047078
- (_Bool)handlesPersistentPropertiesForSenderDescriptor:(id)arg1;	// IMP=0x0010000000046ded
- (void)_queue_enumerateTouchStreamsForAllDisplaysUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000046d80
- (void)_queue_enumerateDigitizersForAllDisplaysUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000046d13
- (void)_queue_enumerateDigitizersForDisplay:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000046b13
- (void)_queue_windowServerDidDeleteSlotID:(unsigned int)arg1;	// IMP=0x00100000000469d6
- (void)applyExtendedHitTestInformationForCAScreenCoordinates:(struct CGPoint)arg1 displayUUID:(id)arg2 toPathAttributes:(id)arg3 secureName:(unsigned int)arg4 excludeContextIDs:(id)arg5;	// IMP=0x0010000000046933
- (void)_queue_resetTouchAuthenticationInitialSampleEvent;	// IMP=0x001000000004672d
- (void)addTouchAuthenticationSpecifications:(id)arg1 registrantEntitled:(_Bool)arg2;	// IMP=0x00100000000466da
- (id)authenticationSpecificationForSlotID:(unsigned int)arg1 registrantEntitled:(out _Bool *)arg2;	// IMP=0x0010000000046609
- (void)setBuiltInDisplayInterfaceOrientation:(long long)arg1;	// IMP=0x0010000000046481
- (void)setExcludedZoomContextIDs:(id)arg1 fromVersionedPID:(long long)arg2;	// IMP=0x001000000004642d
@property(nonatomic) _Bool shouldIgnoreTouchesWhileObjectInProximity;
- (void)postTouchAnnotations:(id)arg1 sourcePID:(int)arg2;	// IMP=0x0010000000046375
- (void)setOffset:(struct CGPoint)arg1 forTouchesWithUserIdentifier:(unsigned int)arg2;	// IMP=0x00100000000462be
- (void)setRoutingPolicy:(id)arg1 forTouchesWithUserIdentifier:(unsigned int)arg2;	// IMP=0x001000000004620c
- (_Bool)detachTouchIdentifiers:(unsigned int *)arg1 count:(long long)arg2 assignUserIdentifier:(unsigned int)arg3 policy:(id)arg4 offset:(struct CGPoint)arg5;	// IMP=0x001000000004615a
- (void)transferTouchIdentifiers:(unsigned int *)arg1 count:(long long)arg2 toContextID:(unsigned int)arg3;	// IMP=0x0010000000046102
- (void)setEventDispatchMode:(unsigned char)arg1 ambiguityRecommendation:(unsigned char)arg2 lastTouchTimestamp:(double)arg3 forTouchStreamIdentifier:(unsigned int)arg4;	// IMP=0x001000000004604c
- (void)invalidateTouchStreamReference:(unsigned int)arg1;	// IMP=0x0010000000045ffe
- (unsigned int)addTouchStreamForContextID:(unsigned int)arg1 display:(id)arg2 versionedPID:(long long)arg3 identifier:(unsigned int)arg4 shouldSendAmbiguityRecommendations:(_Bool)arg5;	// IMP=0x0010000000045f55
- (void)setHitTestRegions:(id)arg1 forDisplay:(id)arg2;	// IMP=0x0010000000045f01
- (id)cancelAndSuppressTouchesOnDisplay:(id)arg1 reason:(id)arg2;	// IMP=0x0010000000045d30
- (void)cancelTouchesOnAllDisplays;	// IMP=0x0010000000045c3f
- (void)cancelTouchesOnMainDisplay;	// IMP=0x0010000000045c2b
- (void)cancelTouchesOnDisplay:(id)arg1;	// IMP=0x0010000000045a92
- (void)cancelTouchesWithIdentifiers:(id)arg1;	// IMP=0x0010000000045949
@property(readonly, retain) BKIOHIDService *mainDisplayPencilDigitizerService;
@property(readonly, retain) BKIOHIDService *mainDisplayAOPDigitizerService;
@property(readonly, retain) BKIOHIDService *mainDisplayDigitizerService;
- (void)appendDescriptionToFormatter:(id)arg1;	// IMP=0x001000000004568f
- (void)didInitializeRegistryWithContext:(id)arg1;	// IMP=0x00100000000455da
- (void)dealloc;	// IMP=0x0010000000045563
- (id)initWithContext:(id)arg1;	// IMP=0x0010000000044a45

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

