//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface BKMigrator : NSObject
{
}

- (_Bool)_moveRestoredFileAtPath:(id)arg1;	// IMP=0x00400000000963f2
- (void)_removeUnusedFiles;	// IMP=0x00100000000961ab
- (void)_migrateBackBoard;	// IMP=0x001000000009615d
- (void)migrateIfNecessary;	// IMP=0x00100000000960a3

@end

