//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BKTouchContact, NSMutableArray;

@interface BKTouchContactSet : NSObject
{
    NSMutableArray *_contacts;	// 8 = 0x8
    BKTouchContact *_unsafeIndexedContacts[30];	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000006996f
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;	// IMP=0x0010000000069959
- (id)copy;	// IMP=0x0010000000069903
- (long long)count;	// IMP=0x00100000000698ed
- (id)description;	// IMP=0x00100000000698cd
- (id)init;	// IMP=0x0010000000069877

@end

