//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtCV20ColorPickerUIService11PageControl11Coordinator : NSObject
{
    MISSING_TYPE *parent;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00400000000153f0
- (id)init;	// IMP=0x0010000000015390
- (void)valueChanged:(id)arg1;	// IMP=0x00100000000152e0

@end

