//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, RPPerson;

@protocol RPPeopleXPCClientInterface
- (MISSING_TYPE *)xpcPersonChanged:changes: /* Error: Ran out of types for this method. */;
- (void)xpcPersonLost:(RPPerson *)arg1;
- (void)xpcPersonFound:(RPPerson *)arg1;
- (void)xpcPeopleStatusChanged:(unsigned int)arg1;
@end

