//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CKRecord, NSData, NSDate, NSString;
@protocol BCCloudDataPrivacyDelegate;

@interface BCCollectionMember
{
}

+ (id)collectionIDFromCollectionMemberID:(id)arg1;	// IMP=0x002000000008e6fa
+ (id)assetIDFromCollectionMemberID:(id)arg1;	// IMP=0x001000000008e686
+ (id)collectionMemberIDWithCollectionID:(id)arg1 assetID:(id)arg2;	// IMP=0x001000000008e65e
+ (id)propertyIDKey;	// IMP=0x001000000008e560
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

- (id)zoneName;	// IMP=0x001000000008e56d
- (id)identifier;	// IMP=0x001000000008e54e
- (id)recordType;	// IMP=0x001000000008e541
- (void)resolveConflictsFromRecord:(id)arg1 withResolvers:(id)arg2;	// IMP=0x001000000008de37
- (void)_configureFromCollectionMember:(id)arg1 withMergers:(id)arg2;	// IMP=0x001000000008dc1a
- (_Bool)isEqualExceptForDate:(id)arg1 ignoringEmptySalt:(_Bool)arg2;	// IMP=0x001000000008dafd
- (void)configureFromCloudData:(id)arg1 withMergers:(id)arg2;	// IMP=0x001000000008da58
- (id)mutableCopy;	// IMP=0x001000000008da2a

// Remaining properties
@property(readonly, copy, nonatomic) NSData *ckSystemFields;
@property(copy, nonatomic) NSString *collectionMemberID; // @dynamic collectionMemberID;
@property(readonly, nonatomic) _Bool deletedFlag;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) long long editGeneration;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSDate *modificationDate;
@property(nonatomic) __weak id <BCCloudDataPrivacyDelegate> privacyDelegate;
@property(nonatomic) int sortOrder; // @dynamic sortOrder;
@property(readonly) Class superclass;
@property(readonly, nonatomic) long long syncGeneration;
@property(readonly, copy, nonatomic) CKRecord *systemFields;

@end

