//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface BDSICloudIdentityToken : NSObject
{
    NSString *_token;	// 8 = 0x8
}

+ (id)tokenForCurrentIdentityIfICloudDriveEnabled;	// IMP=0x0040000000015adb
+ (id)tokenForCurrentIdentityIfCloudKitEnabled;	// IMP=0x0010000000015a7e
- (void).cxx_destruct;	// IMP=0x0020000000015f4b
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
- (id)_hashFor:(id)arg1;	// IMP=0x0010000000015eda
- (id)description;	// IMP=0x0010000000015e65
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000015dff
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000015d45
- (id)initWithCurrentIdentity;	// IMP=0x0010000000015ca0
- (id)initFromArchive:(id)arg1;	// IMP=0x0010000000015c26
- (id)initWithToken:(id)arg1;	// IMP=0x0010000000015b88

@end

