//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BDSClientConnectionManager, BDSICloudIdentityTokenTracker, BDSReachability, NSString;
@protocol BDSServiceConnectionClient;

@interface BDSServiceDelegate : NSObject
{
    int _tccNotifyToken;	// 8 = 0x8
    BDSClientConnectionManager *_clientConnectionManager;	// 16 = 0x10
    BDSICloudIdentityTokenTracker *_iCloudIdentityTokenTracker;	// 24 = 0x18
    id <BDSServiceConnectionClient> _serviceConnectionClient;	// 32 = 0x20
    BDSReachability *_networkReachability;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000008492b
@property(nonatomic) int tccNotifyToken; // @synthesize tccNotifyToken=_tccNotifyToken;
@property(retain, nonatomic) BDSReachability *networkReachability; // @synthesize networkReachability=_networkReachability;
@property(nonatomic) __weak id <BDSServiceConnectionClient> serviceConnectionClient; // @synthesize serviceConnectionClient=_serviceConnectionClient;
@property(retain, nonatomic) BDSICloudIdentityTokenTracker *iCloudIdentityTokenTracker; // @synthesize iCloudIdentityTokenTracker=_iCloudIdentityTokenTracker;
@property(retain, nonatomic) BDSClientConnectionManager *clientConnectionManager; // @synthesize clientConnectionManager=_clientConnectionManager;
- (void)deleteCloudDataWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000845a7
- (void)_deleteLocaliCloudDataIfUserLoggedOutFromiCloudCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000008437e
- (void)_dieIfUnacknowledgediCloudLogoutOcccurred;	// IMP=0x001000000008425d
- (id)_bdsService;	// IMP=0x001000000008412b
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0010000000083843
- (void)dealloc;	// IMP=0x0010000000083743
- (id)initWithServiceConnectionClient:(id)arg1;	// IMP=0x00100000000833b9

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

