//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSOperationQueue, NSString, RMActivationEngine, RMStatusEngine;
@protocol RMClientDelegate, RMConduit;

@interface RMClient : NSObject
{
    NSObject *_needsSyncingLock;	// 8 = 0x8
    MISSING_TYPE *_syncLock;	// 16 = 0x10
    _Bool _needsSyncing;	// 24 = 0x18
    _Bool _firstSync;	// 25 = 0x19
    id <RMClientDelegate> _delegate;	// 32 = 0x20
    NSString *_managementSourceIdentifier;	// 40 = 0x28
    id <RMConduit> _conduit;	// 48 = 0x30
    RMActivationEngine *_activationEngine;	// 56 = 0x38
    RMStatusEngine *_statusEngine;	// 64 = 0x40
    NSOperationQueue *_operationQueue;	// 72 = 0x48
}

+ (id)_makeConduitWithManagementSourceObjectID:(id)arg1 inContext:(id)arg2;	// IMP=0x0020000000010783
- (void).cxx_destruct;	// IMP=0x0020000000014048
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) RMStatusEngine *statusEngine; // @synthesize statusEngine=_statusEngine;
@property(retain, nonatomic) RMActivationEngine *activationEngine; // @synthesize activationEngine=_activationEngine;
@property(retain, nonatomic) id <RMConduit> conduit; // @synthesize conduit=_conduit;
@property(readonly, nonatomic) NSString *managementSourceIdentifier; // @synthesize managementSourceIdentifier=_managementSourceIdentifier;
@property(nonatomic) __weak id <RMClientDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_syncIfNeeded;	// IMP=0x0010000000013eed
- (void)_setNeedsSyncing:(_Bool)arg1;	// IMP=0x0010000000013c4f
- (void)statusEngineHasUnacknowledgedSubscription:(id)arg1;	// IMP=0x0010000000013be8
- (void)conduitNeedsToSendStatusForKeyPaths:(id)arg1;	// IMP=0x0010000000013b25
- (void)conduitNeedsToSync:(id)arg1;	// IMP=0x0010000000013abe
- (void)_processConduitErrorState:(short)arg1;	// IMP=0x00100000000139d6
- (void)_handleConduitError;	// IMP=0x0010000000013933
- (_Bool)_haltSyncing;	// IMP=0x00100000000138e3
- (void)_sendStatusQueryResultIfNeeded:(id)arg1 fullReport:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000013687
- (void)sendStatusForSubscriptionsWithIdentifiers:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000013348
- (id)queryForStatusSubscriptionsWithIdentifiers:(id)arg1;	// IMP=0x0010000000012f4c
- (void)sendStatusData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000012bbf
- (void)updateWithTokensResponse:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000012945
- (void)updateWithPushMessage:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000126cb
- (void)applyNowWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000012662
- (void)_syncConduitOnlyIfNeeded:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000123ce
- (void)_syncOnlyIfNeeded:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000118dd
- (void)syncIfNeededWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000001183d
- (void)syncWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000000117a0
- (void)unenrollWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000011546
- (void)reenrollWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000001118f
- (void)enrollWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000010da5
- (void)startWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000000109e9
- (id)initWithConduit:(id)arg1 activationEngine:(id)arg2 statusEngine:(id)arg3 managementSourceIdentifier:(id)arg4;	// IMP=0x00100000000105a2
- (id)initWithManagementSourceObjectID:(id)arg1 managementSourceIdentifier:(id)arg2 statusQuerier:(id)arg3 persistentContainer:(id)arg4;	// IMP=0x0010000000010357

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

