//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString, PSDSchedulerAWDSessionState;
@protocol OS_dispatch_queue;

@interface PSDSchedulerAWDLogger : NSObject
{
    NSMutableDictionary *_cumulativeStatisticsCollections;	// 8 = 0x8
    NSMutableDictionary *_segmentStartingStatisticsCollections;	// 16 = 0x10
    PSDSchedulerAWDSessionState *_sessionState;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_queue;	// 32 = 0x20
}

+ (id)defaultLogger;	// IMP=0x002000000000727c
+ (_Bool)supportsSecureCoding;	// IMP=0x0010000000007274
- (void).cxx_destruct;	// IMP=0x002000000000a32c
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) PSDSchedulerAWDSessionState *sessionState; // @synthesize sessionState=_sessionState;
- (void)accumulateStatisticsForSegment:(id)arg1;	// IMP=0x0010000000009d00
- (void)bookmarkCurrentStatistics:(id)arg1;	// IMP=0x0000000000009aed
- (id)AWDKeyForActivityIdentifier:(id)arg1;	// IMP=0x0010000000009ac8
- (void)logAWDDurationsForSync;	// IMP=0x0010000000008384
- (void)clearSessionState;	// IMP=0x0010000000008216
- (void)saveSessionState;	// IMP=0x00100000000080d3
- (void)scheduler:(id)arg1 didUpdateSyncSessionWithUpdate:(id)arg2;	// IMP=0x0010000000007b85
- (void)scheduler:(id)arg1 willStartSyncSession:(id)arg2;	// IMP=0x0010000000007a2d
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000000079ac
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000007620
- (id)init;	// IMP=0x00100000000075d4
- (void)initialize;	// IMP=0x0010000000007519

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

