//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ICCloudThrottlingLevel, ICUserDefaults, NSArray, NSDate, NSTimer;

@interface ICCloudThrottlingPolicy : NSObject
{
    NSArray *_throttlingLevels;	// 8 = 0x8
    double _resetInterval;	// 16 = 0x10
    ICUserDefaults *_icUserDefaults;	// 24 = 0x18
    unsigned long long _currentBatchCount;	// 32 = 0x20
    unsigned long long _currentLevelIndex;	// 40 = 0x28
    NSDate *_policyStartDate;	// 48 = 0x30
    NSTimer *_policyResetTimer;	// 56 = 0x38
}

+ (void)resetSavedPolicyState;	// IMP=0x0040000000007633
- (void).cxx_destruct;	// IMP=0x0020000000007a18
@property(retain) NSTimer *policyResetTimer; // @synthesize policyResetTimer=_policyResetTimer;
@property(retain) NSDate *policyStartDate; // @synthesize policyStartDate=_policyStartDate;
@property(nonatomic) unsigned long long currentLevelIndex; // @synthesize currentLevelIndex=_currentLevelIndex;
@property(nonatomic) unsigned long long currentBatchCount; // @synthesize currentBatchCount=_currentBatchCount;
@property(retain, nonatomic) ICUserDefaults *icUserDefaults; // @synthesize icUserDefaults=_icUserDefaults;
@property double resetInterval; // @synthesize resetInterval=_resetInterval;
@property(retain, nonatomic) NSArray *throttlingLevels; // @synthesize throttlingLevels=_throttlingLevels;
- (void)savePolicyState;	// IMP=0x001000000000781d
- (void)loadSavedPolicyState;	// IMP=0x00100000000076c0
- (void)startPolicyResetTimer;	// IMP=0x0010000000007497
- (void)resetPolicy;	// IMP=0x0010000000007287
@property(readonly, nonatomic) ICCloudThrottlingLevel *currentLevel;
@property(readonly, nonatomic) double batchInterval;
- (void)changeLevelIfNecessary;	// IMP=0x0010000000006ec9
- (void)incrementBatchCount;	// IMP=0x0010000000006bfc
- (void)dealloc;	// IMP=0x0010000000006af2
- (id)initWithThrottlingLevels:(id)arg1 resetInterval:(double)arg2;	// IMP=0x0010000000006959

@end

