//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface NPSFullBackupMsg : PBCodable
{
}

- (void)mergeFrom:(id)arg1;	// IMP=0x004000000002be6d
- (unsigned long long)hash;	// IMP=0x001000000002be65
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000002be22
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000002bde9
- (void)copyTo:(id)arg1;	// IMP=0x001000000002bde3
- (void)writeTo:(id)arg1;	// IMP=0x001000000002bddd
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000002bdd0
- (id)dictionaryRepresentation;	// IMP=0x001000000002bcbb
- (id)description;	// IMP=0x001000000002bc0c

@end

