//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;
@protocol OS_dispatch_queue, OS_xpc_object;

@interface RMConnectionListener : NSObject
{
    NSString *_deprecatedEntitlement;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSMutableArray *_connections;	// 24 = 0x18
    NSObject<OS_xpc_object> *_listener;	// 32 = 0x20
    CDUnknownBlockType _messageHandlerConstructor;	// 40 = 0x28
    NSString *_entitlement;	// 48 = 0x30
    NSString *_tccService;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000005dc5
@property(copy, nonatomic) NSString *tccService; // @synthesize tccService=_tccService;
@property(copy, nonatomic) NSString *entitlement; // @synthesize entitlement=_entitlement;
@property(copy, nonatomic) CDUnknownBlockType messageHandlerConstructor; // @synthesize messageHandlerConstructor=_messageHandlerConstructor;
@property(retain, nonatomic) NSObject<OS_xpc_object> *listener; // @synthesize listener=_listener;
@property(retain, nonatomic) NSMutableArray *connections; // @synthesize connections=_connections;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) NSString *deprecatedEntitlement; // @synthesize deprecatedEntitlement=_deprecatedEntitlement;
- (void)endpointWasInvalidated:(id)arg1;	// IMP=0x0010000000005bf2
- (void)endpointWasInterrupted:(id)arg1;	// IMP=0x00100000000059d6
- (void)invalidate;	// IMP=0x00100000000058cd
- (void)traverseEndpointsAsynchronously:(CDUnknownBlockType)arg1;	// IMP=0x001000000000569a
- (void)startListeningForService:(id)arg1;	// IMP=0x0010000000004f36
- (_Bool)isEndpointConnectionAllowed:(id)arg1;	// IMP=0x0010000000004b40
- (id)initWithQueue:(id)arg1 entitlement:(id)arg2 tccService:(id)arg3 messageHandlerConstructor:(CDUnknownBlockType)arg4;	// IMP=0x0010000000004a5e
- (id)initWithQueue:(id)arg1 entitlement:(id)arg2 messageHandlerConstructor:(CDUnknownBlockType)arg3;	// IMP=0x0010000000004a46
- (id)_initWithQueue:(id)arg1 entitlement:(id)arg2 tccService:(id)arg3 messageHandlerConstructor:(CDUnknownBlockType)arg4;	// IMP=0x0010000000004936

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

