//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSString;

@interface _TtCV9stickersd21StickerIndexingClient8Provider : NSObject
{
    MISSING_TYPE *logger;	// 5 = 0x5
    MISSING_TYPE *store;	// 21 = 0x15
}

- (void).cxx_destruct;	// IMP=0x004000000000ad30
- (id)init;	// IMP=0x001000000000acd0
- (void)reindexItemsWithIdentifiers:(NSArray *)arg1 bundleID:(NSString *)arg2 protectionClass:(NSString *)arg3 acknowledgementHandler:(void (^)(void))arg4;	// IMP=0x001000000000aa00
- (void)reindexAllItemsForBundleID:(NSString *)arg1 protectionClass:(NSString *)arg2 acknowledgementHandler:(void (^)(void))arg3;	// IMP=0x001000000000a100
- (void)provideFileURLForBundleID:(id)arg1 protectionClass:(id)arg2 itemIdentifier:(id)arg3 typeIdentifier:(id)arg4 options:(long long)arg5 completionHandler:(CDUnknownBlockType)arg6;	// IMP=0x0010000000009d60
- (void)provideDataForBundleID:(id)arg1 protectionClass:(id)arg2 itemIdentifier:(id)arg3 typeIdentifier:(id)arg4 options:(long long)arg5 completionHandler:(CDUnknownBlockType)arg6;	// IMP=0x00100000000094c0

@end

