//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class SBSLockScreenBackgroundContentAssertion;

@interface MRUILockScreenAssertion : NSObject
{
    _Bool _valid;	// 8 = 0x8
    _Bool _animated;	// 9 = 0x9
    SBSLockScreenBackgroundContentAssertion *_backgroundContentAssertion;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000002f10
@property(retain, nonatomic) SBSLockScreenBackgroundContentAssertion *backgroundContentAssertion; // @synthesize backgroundContentAssertion=_backgroundContentAssertion;
@property(readonly, nonatomic, getter=isAnimated) _Bool animated; // @synthesize animated=_animated;
@property(readonly, nonatomic, getter=isValid) _Bool valid; // @synthesize valid=_valid;
- (void)dealloc;	// IMP=0x0010000000002ea5
- (void)invalidate;	// IMP=0x0010000000002e48
- (void)delayAcquire;	// IMP=0x0010000000002db5
- (void)acquire;	// IMP=0x0010000000002b8a
- (id)init;	// IMP=0x0010000000002b76
- (id)initWithAnimated:(_Bool)arg1;	// IMP=0x0010000000002b20

@end

