//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSBundle, NSString, UIViewController, XBApplicationLaunchCompatibilityInfo, XBLaunchCaptureInformation, XBLaunchImageError, XBLaunchInterface, XBLaunchStateRequest, _XBWrapperWindow;

@interface XBLaunchImageContextWrapper : NSObject
{
    UIViewController *_rootViewController;	// 8 = 0x8
    XBLaunchInterface *_launchInterface;	// 16 = 0x10
    _XBWrapperWindow *_wrapperWindow;	// 24 = 0x18
    XBApplicationLaunchCompatibilityInfo *_appInfo;	// 32 = 0x20
    XBLaunchStateRequest *_launchRequest;	// 40 = 0x28
    NSBundle *_bundle;	// 48 = 0x30
    long long _captureOptions;	// 56 = 0x38
    XBLaunchImageError *_error;	// 64 = 0x40
    XBLaunchCaptureInformation *_captureInformation;	// 72 = 0x48
}

+ (id)contextWrapperForApplicationWithCompatibilityInfo:(id)arg1 launchRequest:(id)arg2 captureOptions:(long long)arg3;	// IMP=0x0020000000001cb1
- (void).cxx_destruct;	// IMP=0x0020000000004e62
@property(retain, nonatomic) XBLaunchCaptureInformation *captureInformation; // @synthesize captureInformation=_captureInformation;
@property(readonly, nonatomic) XBLaunchImageError *error; // @synthesize error=_error;
@property(retain, nonatomic) XBLaunchStateRequest *launchRequest; // @synthesize launchRequest=_launchRequest;
@property(retain, nonatomic) XBApplicationLaunchCompatibilityInfo *appInfo; // @synthesize appInfo=_appInfo;
@property(retain, nonatomic) _XBWrapperWindow *wrapperWindow; // @synthesize wrapperWindow=_wrapperWindow;
@property(readonly, nonatomic) XBLaunchInterface *launchInterface; // @synthesize launchInterface=_launchInterface;
@property(readonly, nonatomic) UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void)invalidate;	// IMP=0x0010000000004d3d
- (void)updateLaunchRequest:(id)arg1;	// IMP=0x0010000000004ce7
- (unsigned long long)_estimatedMemorySizeOfViewHierarchy:(id)arg1;	// IMP=0x0010000000004591
- (id)_ioSurfaceForLayerContents:(void *)arg1;	// IMP=0x001000000000453b
- (void)_update;	// IMP=0x001000000000406f
- (void)_configureNewWindow;	// IMP=0x00100000000039ac
- (_Bool)_verifyMemoryImpactOfViewHierarchy:(id)arg1 bundleID:(id)arg2 size:(unsigned long long *)arg3 error:(id *)arg4;	// IMP=0x0010000000003718
- (void)_configureRootViewForRTL:(id)arg1 bundle:(id)arg2;	// IMP=0x001000000000348a
- (id)_parseLaunchInterface:(id)arg1 bundle:(id)arg2 bundlePath:(id)arg3 bundleID:(id)arg4 error:(id *)arg5;	// IMP=0x00100000000030bc
- (id)_parseInterfaceConfiguration:(id)arg1 bundle:(id)arg2 bundleID:(id)arg3 error:(id *)arg4;	// IMP=0x00100000000026e1
- (id)_parseInterfaceWithNibName:(id)arg1 bundle:(id)arg2 bundleID:(id)arg3 error:(id *)arg4;	// IMP=0x0010000000002299
- (id)_parseInterfaceWithStoryboardName:(id)arg1 bundle:(id)arg2 bundleID:(id)arg3 error:(id *)arg4;	// IMP=0x00100000000020eb
- (id)_errorForParsingException:(id)arg1 bundleID:(id)arg2;	// IMP=0x0010000000001fa2
@property(readonly, nonatomic) unsigned int contextID;
- (id)initWithApplicationCompatibilityInfo:(id)arg1 launchRequest:(id)arg2 captureOptions:(long long)arg3;	// IMP=0x0010000000001d4e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

