//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDClearRestrictionsPasswordOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x004000000002c3a2
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000002c370
- (void)runWithRequest:(id)arg1;	// IMP=0x002000000002c3af

@end

