//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreRoutine/RTHint.h>

@class NSString;

@interface RTHint (RTCoreDataTransformable)
+ (id)createWithHintMO:(id)arg1;	// IMP=0x0010000000494edd
+ (id)createWithManagedObject:(id)arg1;	// IMP=0x0010000000494db5
+ (long long)convertHintSource:(int)arg1;	// IMP=0x001000000058996c
- (id)managedObjectWithContext:(id)arg1;	// IMP=0x00100000004951cc
- (id)initWithRTPHint:(id)arg1;	// IMP=0x0010000000589983

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

