//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKRealTimeMultiplayerCancelBulletin
{
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x0040000000184d31
- (id)removeAndReturnAssociatedInvite;	// IMP=0x0040000000185815
- (void)assembleBulletin;	// IMP=0x00100000001855e0
- (void)copyDataFromAssociatedBulletin:(id)arg1;	// IMP=0x0010000000185488

@end

