//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKTTRInitiationBulletin
{
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x00400000000ef6d9
+ (id)packFakeTTRBulletinWithInfo:(id)arg1;	// IMP=0x00100000000ef523
- (void)assembleBulletin;	// IMP=0x00400000000ef68e

@end

