//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface OpsValidationCategoryAndStatus : NSObject
{
    unsigned int _category;	// 8 = 0x8
    unsigned int _status;	// 12 = 0xc
}

@property(nonatomic) unsigned int status; // @synthesize status=_status;
@property(nonatomic) unsigned int category; // @synthesize category=_category;
- (id)initWithOpsValidationCategory:(unsigned int)arg1 status:(unsigned int)arg2;	// IMP=0x0010000000165417

@end

