//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSNumber, NSString, NSXPCConnection;
@protocol OS_dispatch_queue, SYDDaemonToClientConnectionDelegate;

@interface SYDDaemonToClientConnection : NSObject
{
    _Bool _didRefreshBundleMap;	// 8 = 0x8
    NSString *_applicationIdentifier;	// 16 = 0x10
    NSXPCConnection *_xpcConnection;	// 24 = 0x18
    id <SYDDaemonToClientConnectionDelegate> _delegate;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_callbackQueue;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_queue;	// 48 = 0x30
    NSMutableSet *_registeredStoreIDs;	// 56 = 0x38
    NSMutableSet *_entitledStoreIDs;	// 64 = 0x40
    NSMutableSet *_notEntitledStoreIDs;	// 72 = 0x48
    NSNumber *_ignoreQuotaEntitlementValue;	// 80 = 0x50
    unsigned long long _manualSyncCount;	// 88 = 0x58
}

+ (id)errorForUnknownStore:(id)arg1;	// IMP=0x0020000000026ad0
+ (id)changeDictionaryWithChangedKeys:(id)arg1 reason:(long long)arg2 changeToken:(id)arg3;	// IMP=0x0010000000024de7
+ (id)changedKeysForStoreIdentifier:(id)arg1 sinceChangeTokenIfValid:(id)arg2 inCoreDataStore:(id)arg3 error:(id *)arg4;	// IMP=0x0010000000024c62
+ (id)errorNotEntitledForStoreConfiguration:(id)arg1;	// IMP=0x0010000000021985
+ (_Bool)isXPCConnection:(id)arg1 entitledForStoreConfiguration:(id)arg2;	// IMP=0x00100000000213e2
+ (id)valueForEntitlement:(id)arg1 xpcConnection:(id)arg2 storeConfiguration:(id)arg3;	// IMP=0x0010000000020fb5
- (void).cxx_destruct;	// IMP=0x0020000000026f65
@property(nonatomic) _Bool didRefreshBundleMap; // @synthesize didRefreshBundleMap=_didRefreshBundleMap;
@property(nonatomic) unsigned long long manualSyncCount; // @synthesize manualSyncCount=_manualSyncCount;
@property(retain, nonatomic) NSNumber *ignoreQuotaEntitlementValue; // @synthesize ignoreQuotaEntitlementValue=_ignoreQuotaEntitlementValue;
@property(retain) NSMutableSet *notEntitledStoreIDs; // @synthesize notEntitledStoreIDs=_notEntitledStoreIDs;
@property(retain) NSMutableSet *entitledStoreIDs; // @synthesize entitledStoreIDs=_entitledStoreIDs;
@property(retain) NSMutableSet *registeredStoreIDs; // @synthesize registeredStoreIDs=_registeredStoreIDs;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(nonatomic) __weak id <SYDDaemonToClientConnectionDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
@property(retain, nonatomic) NSString *applicationIdentifier; // @synthesize applicationIdentifier=_applicationIdentifier;
- (_Bool)isPerformingManualSync;	// IMP=0x0010000000026dd7
- (void)decrementManualSyncCount;	// IMP=0x0010000000026ced
- (void)incrementManualSyncCount;	// IMP=0x0010000000026c03
- (_Bool)isKnownStore:(id)arg1;	// IMP=0x0010000000026962
- (id)changeTokenURLForStoreConfiguration:(id)arg1 xpcConnection:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000026738
- (id)client;	// IMP=0x00100000000266e8
- (void)daemonToClientConnectionDidChangeValues:(id)arg1;	// IMP=0x0010000000026084
- (void)notifyAccountDidChangeFromAccountID:(id)arg1 toAccountID:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000258b6
- (void)notifyAccountDidChangeWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000002589d
- (void)syncManagerDidChangeNotification:(id)arg1;	// IMP=0x0010000000025133
- (void)processAccountChangesWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000024f62
- (void)saveChangeToken:(id)arg1 forStoreWithConfiguration:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0010000000024605
- (void)changeTokenForStoreWithConfiguration:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000024076
- (void)changeDictionarySinceChangeToken:(id)arg1 inStoreWithConfiguration:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0010000000023bd0
- (void)registerForChangeNotificationsForStoreWithConfiguration:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000023835
- (void)setCloudSyncUserDefaultEnabled:(_Bool)arg1 storeIdentifier:(id)arg2;	// IMP=0x00100000000237b0
- (void)isCloudSyncUserDefaultEnabledForStoreIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000023705
- (_Bool)isCloudSyncEnablementEntitledForStoreIdentifier:(id)arg1;	// IMP=0x0010000000023619
- (void)allStoreIdentifiersWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000023428
- (void)dictionaryRepresentationForStoreWithConfiguration:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000231ab
- (void)synchronizeStoresWithIdentifiers:(id)arg1 type:(long long)arg2 testConfiguration:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0010000000022a73
- (void)synchronizeStoreWithConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000224e9
- (void)removeObjectForKey:(id)arg1 inStoreWithConfiguration:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0010000000022270
- (void)objectForKey:(id)arg1 inStoreWithConfiguration:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0010000000021fda
- (void)setObject:(id)arg1 forKey:(id)arg2 inStoreWithConfiguration:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x0010000000021bce
- (_Bool)shouldEnforceQuotaForStoreConfiguration:(id)arg1;	// IMP=0x0010000000021ab8
- (_Bool)isEntitledForStoreConfiguration:(id)arg1;	// IMP=0x0010000000020fca
- (void)resume;	// IMP=0x0010000000020b34
- (void)dealloc;	// IMP=0x0010000000020809
- (id)description;	// IMP=0x0010000000020674
- (id)initWithXPCConnection:(id)arg1 delegate:(id)arg2;	// IMP=0x00100000000203a8

@end

