//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Dec 27 2024 14:18:54).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSIndexPath.h>

@interface NSIndexPath (FRAdditions)
+ (id)fr_indexPathsForRows:(id)arg1 inSection:(long long)arg2;	// IMP=0x0010000000055553
+ (id)fr_firstIndexPath;	// IMP=0x00100000000554ae
- (id)indexPathInvalidatingIndexesFollowingPosition:(long long)arg1;	// IMP=0x00200000000554cb
@end

