//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, RDLaunchEvents, SRSensorWriter;
@protocol OS_dispatch_queue;

@interface StrideCalibrationRecorder : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    RDLaunchEvents *_launchEvents;	// 16 = 0x10
    SRSensorWriter *_sensorWriter;	// 24 = 0x18
}

+ (MISSING_TYPE *)initialize;	// IMP=0x0020000000005b37
- (void)launchEventRunActivity:(id)arg1;	// IMP=0x0020000000005e25
- (void)sensorWriterDidStopMonitoring:(id)arg1;	// IMP=0x0010000000005d64
- (void)sensorWriterWillStartMonitoring:(id)arg1;	// IMP=0x0010000000005ca8
- (void)dealloc;	// IMP=0x0010000000005c44

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

