//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, SHLShazamLibrary, SHMediaLibraryContext, SHMediaLibraryDataStore, SHMediaLibraryInfoFetcher, SHMediaLibrarySnapshot, SHMediaLibrarySnapshotUpdater;
@protocol SHMediaLibrarySyncDelegate;

@interface SHMediaLibraryController : NSObject
{
    MISSING_TYPE *delegate;	// 8 = 0x8
    SHLShazamLibrary *_remoteLibrary;	// 16 = 0x10
    SHMediaLibraryDataStore *_dataStore;	// 24 = 0x18
    SHMediaLibraryInfoFetcher *_libraryInfoFetcher;	// 32 = 0x20
    SHMediaLibrarySnapshotUpdater *_snapshotUpdater;	// 40 = 0x28
    SHMediaLibrarySnapshot *_currentSnapshot;	// 48 = 0x30
    SHMediaLibrarySnapshot *_syncSnapshot;	// 56 = 0x38
    SHMediaLibraryContext *_currentContext;	// 64 = 0x40
    NSString *_syncID;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x002000000002af35
@property(retain, nonatomic) NSString *syncID; // @synthesize syncID=_syncID;
@property(retain, nonatomic) SHMediaLibraryContext *currentContext; // @synthesize currentContext=_currentContext;
@property(retain, nonatomic) SHMediaLibrarySnapshot *syncSnapshot; // @synthesize syncSnapshot=_syncSnapshot;
@property(retain, nonatomic) SHMediaLibrarySnapshot *currentSnapshot; // @synthesize currentSnapshot=_currentSnapshot;
@property(retain, nonatomic) SHMediaLibrarySnapshotUpdater *snapshotUpdater; // @synthesize snapshotUpdater=_snapshotUpdater;
@property(retain, nonatomic) SHMediaLibraryInfoFetcher *libraryInfoFetcher; // @synthesize libraryInfoFetcher=_libraryInfoFetcher;
@property(retain, nonatomic) SHMediaLibraryDataStore *dataStore; // @synthesize dataStore=_dataStore;
@property(retain, nonatomic) SHLShazamLibrary *remoteLibrary; // @synthesize remoteLibrary=_remoteLibrary;
@property(nonatomic) __weak id <SHMediaLibrarySyncDelegate> delegate; // @synthesize delegate;
- (void)_synchronizeSnapshot:(id)arg1 startCondition:(id)arg2;	// IMP=0x001000000002add6
- (void)libraryDataStore:(id)arg1 didUpdateWithChange:(id)arg2;	// IMP=0x001000000002ad15
- (void)removeInvalidChangesFromSnapshot:(id)arg1;	// IMP=0x001000000002aa07
- (void)failedToSyncContext:(id)arg1;	// IMP=0x001000000002a8a6
- (void)finishLibrarySync;	// IMP=0x001000000002a7bc
- (id)mapInternalLibraryErrorToMediaLibrary:(id)arg1 keyOverrides:(id)arg2;	// IMP=0x001000000002a57e
- (void)resetDataIfNeededForSyncError:(id)arg1;	// IMP=0x001000000002a49a
- (void)handleLibraryError:(id)arg1 failedItemIdentifiers:(id)arg2;	// IMP=0x001000000002a251
- (void)persistChangesAndCompleteSyncWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000029e54
- (void)beginLibrarySync;	// IMP=0x0010000000029ce8
- (void)library:(id)arg1 didCompleteSyncWithCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000002999e
- (void)library:(id)arg1 didProduceError:(id)arg2 withFailedItemIdentifiers:(id)arg3 syncAction:(long long)arg4;	// IMP=0x0010000000029986
- (void)library:(id)arg1 didDeleteItemsWithIdentifiers:(id)arg2 syncAction:(long long)arg3;	// IMP=0x0010000000029817
- (void)library:(id)arg1 didChangeGroups:(id)arg2 syncAction:(long long)arg3;	// IMP=0x001000000002946f
- (void)library:(id)arg1 didChangeTracks:(id)arg2 syncAction:(long long)arg3;	// IMP=0x0010000000028c8f
- (void)libraryWillBeginSync:(id)arg1;	// IMP=0x0010000000028c3f
- (id)shazamLibrarySyncStartConditionForMediaLibraryStartCondition:(id)arg1;	// IMP=0x0010000000028b50
- (id)unsyncedTrackChangeset;	// IMP=0x0010000000028904
- (id)unsyncedGroupChangeset;	// IMP=0x00100000000286bd
- (void)_synchronizeRemoteSnapshot:(id)arg1 startCondition:(id)arg2;	// IMP=0x0010000000027f66
- (void)synchronizeRemoteSnapshot:(id)arg1 startCondition:(id)arg2;	// IMP=0x0010000000027b4b
- (_Bool)_synchronizeLocalSnapshot:(id)arg1 error:(id *)arg2;	// IMP=0x001000000002709d
- (void)_queryLibraryWithParameters:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000266e6
- (void)_libraryInfoWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000002667d
- (void)synchronizeWithContext:(id)arg1;	// IMP=0x0010000000026168
- (void)commonInitWithDataStore:(id)arg1 remoteLibrary:(id)arg2 libraryInfoFetcher:(id)arg3 snapshotUpdater:(id)arg4;	// IMP=0x001000000002606c
- (id)initWithDataStore:(id)arg1 remoteLibrary:(id)arg2 libraryInfoFetcher:(id)arg3 snapshotUpdater:(id)arg4;	// IMP=0x0010000000025fb2
- (id)initWithBundleIdentifier:(id)arg1 clientType:(long long)arg2;	// IMP=0x0010000000025e9d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

