//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface IXSCoordinatorManager : NSObject
{
    NSObject<OS_dispatch_queue> *_mapQueue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_createQueue;	// 16 = 0x10
    NSMutableDictionary *_identityToCoordinatorMap;	// 24 = 0x18
    NSMutableDictionary *_uuidToCoordinatorMap;	// 32 = 0x20
    NSMutableDictionary *_connectionToProcessScopedCoordinatorMap;	// 40 = 0x28
    NSMutableArray *_identityPriority;	// 48 = 0x30
}

+ (id)sharedInstance;	// IMP=0x002000000000c6a0
+ (id)prioritySaveURL;	// IMP=0x001000000000c616
+ (id)saveDir;	// IMP=0x001000000000c589
+ (id)savePathForCoordinator:(id)arg1;	// IMP=0x001000000000c48f
- (void).cxx_destruct;	// IMP=0x00200000000115d4
@property(readonly, nonatomic) NSMutableArray *identityPriority; // @synthesize identityPriority=_identityPriority;
@property(readonly, nonatomic) NSMutableDictionary *connectionToProcessScopedCoordinatorMap; // @synthesize connectionToProcessScopedCoordinatorMap=_connectionToProcessScopedCoordinatorMap;
@property(readonly, nonatomic) NSMutableDictionary *uuidToCoordinatorMap; // @synthesize uuidToCoordinatorMap=_uuidToCoordinatorMap;
@property(readonly, nonatomic) NSMutableDictionary *identityToCoordinatorMap; // @synthesize identityToCoordinatorMap=_identityToCoordinatorMap;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *createQueue; // @synthesize createQueue=_createQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *mapQueue; // @synthesize mapQueue=_mapQueue;
- (void)convertProcessScopedCoordinatorToGlobalScoped:(id)arg1;	// IMP=0x00100000000113c1
- (void)connectionInvalidated:(id)arg1;	// IMP=0x0010000000010e81
- (void)clearAllCoordinatorsForCreator:(unsigned long long)arg1;	// IMP=0x0010000000010acf
- (void)_enumerateCoordinatorsForConnection:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000000105a1
- (void)enumerateCoordinatorsApplicableToConnection:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000001058f
- (void)enumerateCoordinators:(CDUnknownBlockType)arg1;	// IMP=0x0010000000010578
- (_Bool)prioritizeCoordinator:(id)arg1;	// IMP=0x0010000000010522
- (_Bool)prioritizeCoordinatorWithIdentity:(id)arg1;	// IMP=0x001000000001027a
- (void)unregisterCoordinator:(id)arg1;	// IMP=0x0010000000010071
- (void)performCreationBlockingOperation:(CDUnknownBlockType)arg1;	// IMP=0x001000000000ffbc
- (id)coordinatorForIdentity:(id)arg1 connection:(id)arg2 error:(id *)arg3 creatingIfNotExisting:(CDUnknownBlockType)arg4;	// IMP=0x001000000000f54a
- (id)_lookupCoordinatorForIdentity:(id)arg1 checkingScopeForConnection:(id)arg2 error:(id *)arg3;	// IMP=0x001000000000f031
- (id)_lookupCoordinatorForIdentity:(id)arg1;	// IMP=0x001000000000ee81
- (id)coordinatorsForBundleIdentifier:(id)arg1;	// IMP=0x001000000000ec3f
- (id)coordinatorForIdentity:(id)arg1;	// IMP=0x001000000000ec2d
- (id)coordinatorForUUID:(id)arg1;	// IMP=0x001000000000ea58
- (_Bool)_coordinator:(id)arg1 isApplicableToConnection:(id)arg2;	// IMP=0x001000000000e953
- (void)_onMapQueue_saveIdentityPriority;	// IMP=0x001000000000e6ff
- (_Bool)_onMapQueue_removeCoordinatorFromMaps:(id)arg1;	// IMP=0x001000000000e3c8
- (id)init;	// IMP=0x001000000000c83e
@property(readonly, nonatomic) unsigned long long coordinatorCount;

@end

