//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface IXSMoveOrDeleteAlert
{
}

- (void)otherButtonActionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0040000000007747
- (id)otherButtonLabel;	// IMP=0x0010000000007727
- (id)cancelButtonLabel;	// IMP=0x0010000000007707
- (id)defaultButtonLabel;	// IMP=0x0010000000007678
- (id)message;	// IMP=0x00100000000075e9
- (id)title;	// IMP=0x00100000000074bf
- (id)initWithAppRecord:(id)arg1 bundleIdentifier:(id)arg2 removability:(unsigned long long)arg3 deletionIsRestricted:(_Bool)arg4;	// IMP=0x0010000000007452

@end

