//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CLLocation, CLVisit, NSString;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface MCPOIBusynessProcessor : NSObject
{
    _Bool _isWaiting;	// 8 = 0x8
    NSObject<OS_dispatch_group> *_waitGroup;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    CLLocation *_location;	// 32 = 0x20
    CLVisit *_visit;	// 40 = 0x28
}

+ (id)sharedProcessor;	// IMP=0x0020000000002ae8
- (void).cxx_destruct;	// IMP=0x002000000000339b
- (void)finished;	// IMP=0x001000000000323f
- (void)noLocationAuth;	// IMP=0x00100000000031ca
- (void)didUpdateVisit:(id)arg1;	// IMP=0x0010000000003089
- (void)didUpdateLocation:(id)arg1;	// IMP=0x0010000000002e96
- (void)leechLocation;	// IMP=0x0010000000002c05
- (id)init;	// IMP=0x0010000000002b3d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

