//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;
@protocol DOCNode;

@interface _TtC5Files15DOCNodeObserver : NSObject
{
    MISSING_TYPE *collection;	// 8 = 0x8
    MISSING_TYPE *deepObserving;	// 16 = 0x10
    MISSING_TYPE *node;	// 24 = 0x18
    MISSING_TYPE *subscribers;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000004943f0
- (id)init;	// IMP=0x0010000000494430
- (void)dealloc;	// IMP=0x0010000000494390
- (id)initWithObservedNode:(id)arg1 source:(id)arg2 enableDeepObserving:(_Bool)arg3;	// IMP=0x00100000004942e0
@property(nonatomic, retain) id <DOCNode> node; // @synthesize node;
- (void)removeSubscriber:(id)arg1;	// IMP=0x0010000000494560
- (id)addDidFinishGatheringSubscriber:(CDUnknownBlockType)arg1;	// IMP=0x0010000000494480
- (id)addSubscriber:(CDUnknownBlockType)arg1;	// IMP=0x0010000000494460

@end

