//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIDocumentSharingController.h>

@interface _TtC5FilesP33_9E9EA9120FD3595FAD4BD2167103835628DOCDocumentSharingController : UIDocumentSharingController
{
}

- (id)initWithCoder:(id)arg1;	// IMP=0x0040000000086f50
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000086eb0
- (id)initWithFileURL:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000086e10
- (id)initWithFileURL:(id)arg1;	// IMP=0x0010000000086d70
- (void)presentationControllerWillDismiss:(id)arg1;	// IMP=0x0010000000086d20

@end

