//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIBarButtonItem.h>

@class MISSING_TYPE;

@interface _TtC5Files27DOCSymbolImageBarButtonItem : UIBarButtonItem
{
    MISSING_TYPE *symbolDescriptor;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00400000003ece70
- (id)init;	// IMP=0x00100000003ece10
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000003ecd30
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000003ec8a0

@end

