//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSURLComponents.h"

@class NSArray, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface _NSURLComponentsBridge : NSURLComponents
{
}

@property(readonly) NSString *_percentEncodedFragment;
- (id)percentEncodedFragment;	// IMP=0x0000000000861a7e
@property(readonly) NSArray *_percentEncodedQueryItems;
- (id)percentEncodedQueryItems;	// IMP=0x0000000000861a45
@property(readonly) NSString *_percentEncodedQuery;
- (id)percentEncodedQuery;	// IMP=0x0000000000861a0c
@property(readonly) NSString *_percentEncodedPath;
- (id)percentEncodedPath;	// IMP=0x00000000008619ce
@property(readonly) NSNumber *_port;
- (id)port;	// IMP=0x0000000000861995
@property(readonly) NSString *_encodedHost;
- (id)encodedHost;	// IMP=0x000000000086195c
@property(readonly) NSString *_percentEncodedHost;
- (id)percentEncodedHost;	// IMP=0x0000000000861923
@property(readonly) NSString *_percentEncodedPassword;
- (id)percentEncodedPassword;	// IMP=0x00000000008618ea
@property(readonly) NSString *_percentEncodedUser;
- (id)percentEncodedUser;	// IMP=0x00000000008618b1
@property(readonly) NSString *_scheme;
- (id)scheme;	// IMP=0x0000000000861878
- (_Bool)_setPercentEncodedFragment:(id)arg1;	// IMP=0x0000000000861851
- (void)setPercentEncodedFragment:(id)arg1;	// IMP=0x00000000008617be
- (_Bool)_setPercentEncodedQueryItems:(id)arg1;	// IMP=0x0000000000861797
- (void)setPercentEncodedQueryItems:(id)arg1;	// IMP=0x0000000000861704
- (_Bool)_setPercentEncodedQuery:(id)arg1;	// IMP=0x00000000008616dd
- (void)setPercentEncodedQuery:(id)arg1;	// IMP=0x000000000086164a
- (_Bool)_setPercentEncodedPath:(id)arg1;	// IMP=0x0000000000861623
- (void)setPercentEncodedPath:(id)arg1;	// IMP=0x0000000000861590
- (_Bool)_setPort:(id)arg1;	// IMP=0x0000000000861569
- (void)setPort:(id)arg1;	// IMP=0x00000000008614d6
- (_Bool)_setEncodedHost:(id)arg1;	// IMP=0x00000000008614af
- (void)setEncodedHost:(id)arg1;	// IMP=0x000000000086141c
- (_Bool)_setPercentEncodedHost:(id)arg1;	// IMP=0x00000000008613f5
- (void)setPercentEncodedHost:(id)arg1;	// IMP=0x0000000000861362
- (_Bool)_setPercentEncodedPassword:(id)arg1;	// IMP=0x000000000086133b
- (void)setPercentEncodedPassword:(id)arg1;	// IMP=0x00000000008612a8
- (_Bool)_setPercentEncodedUser:(id)arg1;	// IMP=0x0000000000861281
- (void)setPercentEncodedUser:(id)arg1;	// IMP=0x00000000008611ee
- (_Bool)_setScheme:(id)arg1;	// IMP=0x00000000008611c7
- (void)setScheme:(id)arg1;	// IMP=0x0000000000861134

@end

