//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface ICCollaborationLeaveRequest
{
    NSString *_globalPlaylistID;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000e7f26
- (id)_requestBody;	// IMP=0x00100000000e7ec9
- (id)canonicalResponseForResponse:(id)arg1;	// IMP=0x00100000000e7db3
- (id)initWithDatabaseID:(unsigned int)arg1 globalPlaylistID:(id)arg2;	// IMP=0x00100000000e7cb9

@end

